site_name: Kubernetes入门实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜迎难而上，做云原生时代的弄潮儿.md
  
   - 课前准备｜动手实践才是最好的学习方式.md
  
   - 01｜初识容器_万事开头难.md
  
   - 02｜被隔离的进程_一起来看看容器的本质.md
  
   - 03｜容器化的应用_会了这些你就是Docker高手.md
  
   - 04｜创建容器镜像_如何编写正确、高效的Dockerfile.md
  
   - 05｜镜像仓库_该怎样用好DockerHub这个宝藏.md
  
   - 06｜打破次元壁_容器该如何与外界互联互通.md
  
   - 07｜实战演练_玩转Docker.md
  
   - 08｜视频_入门篇实操总结.md
  
   - 09｜走近云原生_如何在本机搭建小巧完备的Kubernetes环境.md
  
   - 10｜自动化的运维管理_探究Kubernetes工作机制的奥秘.md
  
   - 加餐｜Kubernetes“弃用Docker”是怎么回事_.md
  
   - 11｜YAML_Kubernetes世界里的通用语.md
  
   - 12｜Pod_如何理解这个Kubernetes里最核心的概念_.md
  
   - 13｜Job_CronJob_为什么不直接用Pod来处理业务_.md
  
   - 14｜ConfigMap_Secret_怎样配置、定制我的应用.md
  
   - 15｜实战演练_玩转Kubernetes（1）.md
  
   - 16｜视频_初级篇实操总结.md
  
   - 17｜更真实的云原生_实际搭建多节点的Kubernetes集群.md
  
   - 18｜Deployment_让应用永不宕机.md
  
   - 19｜Daemonset_忠实可靠的看门狗.md
  
   - 20｜Service_微服务架构的应对之道.md
  
   - 21｜Ingress_集群进出流量的总管.md
  
   - 22｜实战演练_玩转Kubernetes（2）.md
  
   - 23｜视频_中级篇实操总结.md
  
   - 加餐｜docker-compose_单机环境下的容器编排工具.md
  
   - 24｜PersistentVolume_怎么解决数据持久化的难题_.md
  
   - 25｜PersistentVolume&#43;NFS_怎么使用网络共享存储_.md
  
   - 26｜StatefulSet_怎么管理有状态的应用_.md
  
   - 27｜滚动更新_如何做到平滑的应用升级降级_.md
  
   - 28｜应用保障_如何让Pod运行得更健康_.md
  
   - 29｜集群管理_如何用名字空间分隔系统资源_.md
  
   - 30｜系统监控_如何使用MetricsServer和Prometheus_.md
  
   - 31｜网络通信_CNI是怎么回事_又是怎么工作的_.md
  
   - 32｜实战演练_玩转Kubernetes（3）.md
  
   - 33｜视频_高级篇实操总结.md
  
   - 结束语｜是终点，更是起点.md
  
   - 期末测试｜来赴一场满分之约！.md
  
   - 加餐｜谈谈KongIngressController.md
  
   - 加餐｜尝鲜GatewayAPI_更强大、更灵活、面向未来的Ingress.md
  