site_name: 现代C&#43;&#43;20实战高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜为什么掌握现代C&#43;&#43;新特性如此重要_.md
  
   - 01｜Modules（上）_C&#43;&#43;模块化问题的前世今生.md
  
   - 02｜Modules（中）_解决编译性能和符号隔离的银弹.md
  
   - 03｜Modules（下）_实战写个多模块图像处理服务.md
  
   - 04｜Concepts背景_C&#43;&#43;泛型编程之殇.md
  
   - 05｜Concepts_解决模板接口的类型与约束定义难题.md
  
   - 06｜Concepts实战_写个向量计算模板库.md
  
   - 07｜Coroutines背景_异步I_O的复杂性.md
  
   - 08｜Coroutines_“零”开销降低异步编程复杂度.md
  
   - 09｜Coroutines实战（一）_异步文件操作库.md
  
   - 10｜Coroutines实战（二）_异步文件操作库.md
  
   - 期中周｜扩展现有协程框架，实现高级任务调度.md
  
   - 期中周｜期中测试题，你做对了么_.md
  
   - 11｜Ranges（一）_数据序列处理的新工具.md
  
   - 12｜Ranges（二）_用“视图”破除函数式编程之困.md
  
   - 13｜Ranges实战_数据序列函数式编程.md
  
   - 14｜Formatting_千呼万唤始出来的新format标准.md
  
   - 15｜Formatting实战_如何构建一个数据流处理实例_.md
  
   - 16｜Bitlibrary（一）_如何利用新bit操作库释放编程生产力_.md
  
   - 17｜Bitlibrary（二）_如何利用新bit操作库释放编程生产力_.md
  
   - 18｜其他重要标准库特性_还有哪些库变更值得关注_.md
  
   - 19｜其他重要标准库特性实战_利用日历应用熟悉新特性.md
  
   - 20｜漫游C&#43;&#43;23_更好的C&#43;&#43;20.md
  
   - 21｜重大变更（一）_关于C&#43;&#43;26的十大猜想.md
  
   - 22｜重大变更（二）_关于C&#43;&#43;26的十大猜想.md
  
   - 23｜未来展望_透过未来标准演进看C&#43;&#43;设计哲学.md
  
   - 结束语｜这只长颈鹿在我家后院生活得不错.md
  
   - 期末测试｜来赴一场满分之约！.md
  
   - 加餐｜软件工程师在AIGC浪潮下的生存指南.md
  