site_name: 图解GoogleV8

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_如何学习谷歌高性能JavaScript引擎V8_.md
  
   - 01_V8是如何执行一段JavaScript代码的_.md
  
   - 02_函数即对象_一篇文章彻底搞懂JavaScript的函数特点.md
  
   - 03_快属性和慢属性_V8是怎样提升对象属性访问速度的_.md
  
   - 04_函数表达式_涉及大量概念，函数表达式到底该怎么学_.md
  
   - 05｜原型链_V8是如何实现对象继承的_.md
  
   - 06｜作用域链_V8是如何查找变量的_.md
  
   - 07｜类型转换_V8是怎么实现1&#43;“2”的_.md
  
   - 08｜答疑_如何构建和使用V8的调试工具d8_.md
  
   - 09_运行时环境_运行JavaScript代码的基石.md
  
   - 10_机器代码_二进制机器码究竟是如何被CPU执行的_.md
  
   - 11_堆和栈_函数调用是如何影响到内存布局的_.md
  
   - 12_延迟解析_V8是如何实现闭包的_.md
  
   - 13_字节码（一）_V8为什么又重新引入字节码_.md
  
   - 14｜字节码（二）_解释器是如何解释执行字节码的_.md
  
   - 15_隐藏类_如何在内存中快速查找对象属性_.md
  
   - 16_答疑_V8是怎么通过内联缓存来提升函数执行效率的_.md
  
   - 17_消息队列_V8是怎么实现回调函数的_.md
  
   - 18_异步编程（一）_V8是如何实现微任务的_.md
  
   - 19｜异步编程（二）_V8是如何实现async_await的_.md
  
   - 20_垃圾回收（一）_V8的两个垃圾回收器是如何工作的_.md
  
   - 21_垃圾回收（二）_V8是如何优化垃圾回收器执行效率的_.md
  
   - 22｜答疑_几种常见内存问题的解决策略.md
  
   - 结束语_我的前端学习踩坑史.md
  
   - 结课测试_这些V8的知识你都掌握了吗_.md
  