site_name: 大数据经典论文解读

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_读论文是成为优秀工程师的成年礼.md
  
   - 01_什么是大数据_从GFS到Dataflow，12年大数据生态演化图.md
  
   - 02_学习方法_建立你的大数据知识网络.md
  
   - 03_TheGoogleFileSystem（一）_Master的三个身份.md
  
   - 04_TheGoogleFileSystem（二）_如何应对网络瓶颈_.md
  
   - 05_TheGoogleFileSystem（三）_多写几次也没关系.md
  
   - 06_MapReduce（一）_源起Unix的设计思想.md
  
   - 07_MapReduce（二）_不怕失败的计算框架.md
  
   - 08_Bigtable（一）_错失百亿的Friendster.md
  
   - 09_Bigtable（二）_不认识“主人”的分布式架构.md
  
   - 10_Bigtable（三）_SSTable存储引擎详解.md
  
   - 11_通过Thrift序列化_我们要预知未来才能向后兼容吗_.md
  
   - 12_分布式锁Chubby（一）_交易之前先签合同.md
  
   - 13_分布式锁Chubby（二）_众口铄金的真相.md
  
   - 14_分布式锁Chubby（三）_移形换影保障高可用.md
  
   - 15_Hive_来来去去的DSL，永生不死的SQL.md
  
   - 16_从Dremel到Parquet（一）_深入剖析列式存储.md
  
   - 17_从Dremel到Parquet（二）_他山之石的MPP数据库.md
  
   - 18_Spark_别忘了内存比磁盘快多少.md
  
   - 19_Megastore（一）_全国各地都能写入的数据库.md
  
   - 20_Megastore（二）_把Bigtable玩出花来.md
  
   - 21_Megastore（三）_让Paxos跨越“国界”.md
  
   - 22_Spanner（一）_“重写”Bigtable和Megastore.md
  
   - 23_Spanner（二）_时间的悖论.md
  
   - 24_Spanner（三）_严格串行化的分布式系统.md
  
   - 25_从S4到Storm（一）_当分布式遇上实时计算.md
  
   - 26_从S4到Storm（二）_位运算是个好东西.md
  
   - 27_Kafka（一）_消息队列的新标准.md
  
   - 28_Kafka（二）_从Lambda到Kappa，流批一体计算的起源.md
  
   - 29_Dataflow（一）_正确性、容错和时间窗口.md
  
   - 30_Dataflow（二）_MillWheel，一个早期实现.md
  
   - 31_Dataflow（三）_一个统一的编程模型.md
  
   - 复习课（一）_TheGoogleFileSystem.md
  
   - 复习课（二）_MapReduce.md
  
   - 复习课（三）_Bigtable.md
  
   - 复习课（四）_Thrift.md
  
   - 复习课（五）_Chubby.md
  
   - 复习课（六）_Hive.md
  
   - 复习课（七）_Dremel.md
  
   - 复习课（八）_ResilientDistributedDatasets.md
  
   - 复习课（九）_Megastore.md
  
   - 复习课（十）_Spanner.md
  
   - 加餐1_选择和努力同样重要_聊聊如何读论文和选论文.md
  
   - 加餐2_设置你的学习“母题”_如何选择阅读材料_.md
  
   - 加餐3_我该使用什么样的大数据系统_.md
  
   - 32_Raft（一）_不会背叛的信使.md
  
   - 33_Raft（二）_服务器增减的“自举”实现.md
  
   - 34_Borg（一）_当电力成为成本瓶颈.md
  
   - 35_Borg（二）_互不“信任”的调度系统.md
  
   - 36_从Omega到Kubernetes_哺育云原生的开源项目.md
  
   - 用户故事_陈煌_唯有自强不息，方能屹立不倒.md
  
   - 用户故事_黄涛_水滴石穿、坚持不懈，必能有所精进.md
  
   - 用户故事_许灵_不抛弃不放弃.md
  
   - 用户故事_核桃_95后的技术成长之路.md
  
   - 37_当数据遇上AI，Twitter的数据挖掘实战（一）.md
  
   - 38_当数据遇上AI，Twitter的数据挖掘实战（二）.md
  
   - 39_十年一梦，一起来看Facebook的数据仓库变迁（一）.md
  
   - 40_十年一梦，一起来看Facebook的数据仓库变迁（二）.md
  
   - 结束语_长风破浪会有时，直挂云帆济沧海.md
  