site_name: 从0开始学微服务

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_微服务，从放弃到入门.md
  
   - 01_到底什么是微服务_.md
  
   - 02_从单体应用走向服务化.md
  
   - 03_初探微服务架构.md
  
   - 04_如何发布和引用服务_.md
  
   - 05_如何注册和发现服务_.md
  
   - 06_如何实现RPC远程服务调用_.md
  
   - 07_如何监控微服务调用_.md
  
   - 08_如何追踪微服务调用_.md
  
   - 09_微服务治理的手段有哪些_.md
  
   - 10_Dubbo框架里的微服务组件.md
  
   - 11_服务发布和引用的实践.md
  
   - 12_如何将注册中心落地_.md
  
   - 13_开源服务注册中心如何选型_.md
  
   - 14_开源RPC框架如何选型_.md
  
   - 15_如何搭建一个可靠的监控系统_.md
  
   - 16_如何搭建一套适合你的服务追踪系统_.md
  
   - 17_如何识别服务节点是否存活_.md
  
   - 18_如何使用负载均衡算法_.md
  
   - 19_如何使用服务路由_.md
  
   - 20_服务端出现故障时该如何应对_.md
  
   - 21_服务调用失败时有哪些处理手段_.md
  
   - 22_如何管理服务配置_.md
  
   - 23_如何搭建微服务治理平台_.md
  
   - 24_微服务架构该如何落地_.md
  
   - 25_微服务为什么要容器化_.md
  
   - 26_微服务容器化运维_镜像仓库和资源调度.md
  
   - 27_微服务容器化运维_容器调度和服务编排.md
  
   - 28_微服务容器化运维_微博容器运维平台DCP.md
  
   - 29_微服务如何实现DevOps_.md
  
   - 30_如何做好微服务容量规划_.md
  
   - 31_微服务多机房部署实践.md
  
   - 32_微服务混合云部署实践.md
  
   - 33_下一代微服务架构ServiceMesh.md
  
   - 34_Istio_ServiceMesh的代表产品.md
  
   - 35_微博ServiceMesh实践之路（上）.md
  
   - 36_微博ServiceMesh实践之路（下）.md
  
   - 阿忠伯的特别放送_答疑解惑01.md
  
   - 阿忠伯的特别放送_答疑解惑02.md
  
   - 微博技术解密（上）_微博信息流是如何实现的_.md
  
   - 微博技术解密（下）_微博存储的那些事儿.md
  
   - 结束语_微服务，从入门到精通.md
  
   - 结课测试｜这些微服务知识你都掌握了吗_.md
  