site_name: 罗剑锋的C&#43;&#43;实战笔记

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_把C&#43;&#43;从“神坛”上拉下来，这次咱这么学.md
  
   - 课前准备_搭建实验环境.md
  
   - 01_重新认识C&#43;&#43;_生命周期和编程范式.md
  
   - 02_编码阶段能做什么_秀出好的codestyle.md
  
   - 03_预处理阶段能做什么_宏定义和条件编译.md
  
   - 04_编译阶段能做什么_属性和静态断言.md
  
   - 05_面向对象编程_怎样才能写出一个“好”的类_.md
  
   - 06_auto_decltype_为什么要有自动类型推导_.md
  
   - 07_const_volatile_mutable_常量_变量究竟是怎么回事_.md
  
   - 08_smart_ptr_智能指针到底“智能”在哪里_.md
  
   - 09_exception_怎样才能用好异常_.md
  
   - 10_lambda_函数式编程带来了什么_.md
  
   - 11_一枝独秀的字符串_C&#43;&#43;也能处理文本_.md
  
   - 12_三分天下的容器_恰当选择，事半功倍.md
  
   - 13_五花八门的算法_不要再手写for循环了.md
  
   - 14_十面埋伏的并发_多线程真的很难吗_.md
  
   - 15_序列化_简单通用的数据交换格式有哪些_.md
  
   - 16_网络通信_我不想写原生Socket.md
  
   - 17_脚本语言_搭建高性能的混合系统.md
  
   - 18_性能分析_找出程序的瓶颈.md
  
   - 19_设计模式（上）_C&#43;&#43;与设计模式有啥关系_.md
  
   - 20_设计模式（下）_C&#43;&#43;是怎么应用设计模式的_.md
  
   - 21_知识串讲（上）_带你开发一个书店应用.md
  
   - 22_知识串讲（下）_带你开发一个书店应用.md
  
   - 期末测试_这些C&#43;&#43;核心知识，你都掌握了吗_.md
  
   - 结束语_路远，未有穷期.md
  
   - 轻松话题（一）_4本值得一读再读的经典好书.md
  
   - 轻松话题（二）_给你分享我的工作百宝箱.md
  
   - 轻松话题（三）_提高生活质量的App.md
  
   - 轻松话题（四）_真正高效的生活，是张弛有度.md
  
   - 特别放送_和你聊聊现代C&#43;&#43;里的“特殊容器”.md
  
   - 罗剑锋老师出新课了_.md
  