site_name: 软件设计之美

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_软件设计，应对需求规模的“算法”.md
  
   - 01_软件设计到底是什么_.md
  
   - 02_分离关注点_软件设计至关重要的第一步.md
  
   - 03_可测试性_一个影响软件设计的重要因素.md
  
   - 04_三步走_如何了解一个软件的设计_.md
  
   - 05_SpringDI容器_如何分析一个软件的模型_.md
  
   - 06_RubyonRails_如何分析一个软件的接口_.md
  
   - 07_Kafka_如何分析一个软件的实现_.md
  
   - 08_语言的模型_如何打破单一语言局限，让设计更好地落地_.md
  
   - 09_语言的接口_语法和程序库，软件设计的发力点.md
  
   - 10_语言的实现_运行时，软件设计的地基.md
  
   - 11_DSL_你也可以设计一门自己的语言.md
  
   - 加餐_再八卦几门语言！.md
  
   - 12_编程范式_明明写的是Java，为什么被人说成了C代码_.md
  
   - 13_结构化编程_为什么做设计时仅有结构化编程是不够的_.md
  
   - 14_面向对象之封装_怎样的封装才算是高内聚_.md
  
   - 15_面向对象之继承_继承是代码复用的合理方式吗_.md
  
   - 16_面向对象之多态_为什么“稀疏平常”的多态，是软件设计的大杀器_.md
  
   - 17_函数式编程_不用函数式编程语言，怎么写函数式的程序_.md
  
   - 18_函数式编程之组合性_函数式编程为什么如此吸引人_.md
  
   - 19_函数式编程之不变性_怎样保证我的代码不会被别人破坏_.md
  
   - 加餐_函数式编程拾遗.md
  
   - 20_单一职责原则_你的模块到底为谁负责_.md
  
   - 21_开放封闭原则_不改代码怎么写新功能_.md
  
   - 22_Liskov替换原则_用了继承，子类就设计对了吗_.md
  
   - 23_接口隔离原则_接口里的方法，你都用得到吗_.md
  
   - 24_依赖倒置原则_高层代码和底层代码，到底谁该依赖谁_.md
  
   - 25_设计模式_每一种都是一个特定问题的解决方案.md
  
   - 26_简单设计_难道一开始就要把设计做复杂吗_.md
  
   - 27_领域驱动设计_如何从零开始设计一个软件_.md
  
   - 28_战略设计_如何划分系统的模块_.md
  
   - 29_战术设计_如何像写故事一样找出模型_.md
  
   - 30_程序库的设计_Moco是如何解决集成问题的_.md
  
   - 31_应用的设计_如何设计一个数据采集平台_.md
  
   - 32_应用的改进_如何改进我们的软件设计_.md
  
   - 结束语｜那些没讲的事儿.md
  
   - 结课测试｜这些软件设计的知识你都掌握了吗_.md
  
   - 第三季回归_我们一起来写好代码！.md
  
   - 第四季回归_通向高质量代码之路.md
  
   - 特别加餐｜ChatGPT来了，工程师何去何从_.md
  
   - 私享直播｜1小时参透程序员的AI三重境界.md
  
   - 私享直播｜程序员的上限、下限和第二曲线.md
  
   - 第五季回归｜让我们一起共赴AI时代！.md
  