site_name: 分布式数据库30讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜为什么要学习分布式数据库_.md
  
   - 01｜什么是分布式数据库_.md
  
   - 02｜强一致性_那么多数据一致性模型，究竟有啥不一样_.md
  
   - 03｜强一致性_别再用BASE做借口，来看看什么是真正的事务一致性.md
  
   - 04_架构风格_NewSQL和PGXC到底有啥不一样_.md
  
   - 05_全局时钟_物理时钟和逻辑时钟你Pick谁_.md
  
   - 06_分片机制_为什么说Range是更好的分片策略_.md
  
   - 07_数据复制_为什么有时候Paxos不是最佳选择_.md
  
   - 08_基础篇大串讲_重难点回顾&#43;思考题答疑&#43;知识全景图.md
  
   - 09｜原子性_2PC还是原子性协议的王者吗_.md
  
   - 10_原子性_如何打破事务高延迟的魔咒_.md
  
   - 11｜隔离性_读写冲突时，快照是最好的办法吗_.md
  
   - 12_隔离性_看不见的读写冲突，要怎么处理_.md
  
   - 13_隔离性_为什么使用乐观协议的分布式数据库越来越少_.md
  
   - 14_隔离性_实现悲观协议，除了锁还有别的办法吗_.md
  
   - 15_分布式事务串讲_重难点回顾&#43;思考题答疑&#43;知识全景图.md
  
   - 16_为什么不建议你使用存储过程_.md
  
   - 17_为什么不建议你使用自增主键_.md
  
   - 18_HTAP是不是赢者通吃的游戏_.md
  
   - 19_查询性能优化_计算与存储分离架构下有哪些优化思路_.md
  
   - 20_关联查询_如何提升多表Join能力_.md
  
   - 21_查询执行引擎_如何让聚合计算加速_.md
  
   - 22｜RUM猜想_想要读写快还是存储省_又是三选二.md
  
   - 23_数据库查询串讲_重难点回顾&#43;思考题答疑&#43;知识全景图.md
  
   - 24_全球化部署_如何打造近在咫尺且永不宕机的数据库_.md
  
   - 25_容灾与备份_如何设计逃生通道保证业务连续性_.md
  
   - 26_容器化_分布式数据库要不要上云，你想好了吗_.md
  
   - 27_产品测试_除了性能跑分，还能测个啥_.md
  
   - 28_选型案例_银行是怎么选择分布式数据库的_.md
  
   - 29_产品图鉴_哪些分布式数据库值得看_.md
  
   - 30_实践篇大串讲_重难点回顾&#43;思考题答疑&#43;知识全景图.md
  
   - 结束语_享受职业带给你的快乐.md
  
   - 结课测试｜这些分布式数据库的问题，你都掌握了吗_.md
  
   - 用户故事_李兆龙_博观而约取，厚积而薄发.md
  