site_name: Flutter核心技术与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_为什么每一位大前端从业者都应该学习Flutter_.md
  
   - 01_预习篇·从0开始搭建Flutter工程环境.md
  
   - 02_预习篇·Dart语言概览.md
  
   - 03_深入理解跨平台方案的历史发展逻辑.md
  
   - 04_Flutter区别于其他方案的关键技术是什么_.md
  
   - 05_从标准模板入手，体会Flutter代码是如何运行在原生系统上的.md
  
   - 06_基础语法与类型变量_Dart是如何表示信息的_.md
  
   - 07_函数、类与运算符_Dart是如何处理信息的_.md
  
   - 08_综合案例_掌握Dart核心特性.md
  
   - 09_Widget，构建Flutter界面的基石.md
  
   - 10_Widget中的State到底是什么_.md
  
   - 11_提到生命周期，我们是在说什么_.md
  
   - 12_经典控件（一）_文本、图片和按钮在Flutter中怎么用_.md
  
   - 13_经典控件（二）_UITableView_ListView在Flutter中是什么_.md
  
   - 14_经典布局_如何定义子控件在父容器中排版的位置_.md
  
   - 15_组合与自绘，我该选用何种方式自定义Widget_.md
  
   - 16_从夜间模式说起，如何定制不同风格的App主题_.md
  
   - 17_依赖管理（一）_图片、配置和字体在Flutter中怎么用_.md
  
   - 18_依赖管理（二）_第三方组件库在Flutter中要如何管理_.md
  
   - 19_用户交互事件该如何响应_.md
  
   - 20_关于跨组件传递数据，你只需要记住这三招.md
  
   - 21_路由与导航，Flutter是这样实现页面切换的.md
  
   - 22_如何构造炫酷的动画效果_.md
  
   - 23_单线程模型怎么保证UI运行流畅_.md
  
   - 24_HTTP网络编程与JSON解析.md
  
   - 25_本地存储与数据库的使用和优化.md
  
   - 26_如何在Dart层兼容Android_iOS平台特定实现_（一）.md
  
   - 27_如何在Dart层兼容Android_iOS平台特定实现_（二）.md
  
   - 28_如何在原生应用中混编Flutter工程_.md
  
   - 29_混合开发，该用何种方案管理导航栈_.md
  
   - 30_为什么需要做状态管理，怎么做_.md
  
   - 31_如何实现原生推送能力_.md
  
   - 32_适配国际化，除了多语言我们还需要注意什么_.md
  
   - 33_如何适配不同分辨率的手机屏幕_.md
  
   - 34_如何理解Flutter的编译模式_.md
  
   - 35_HotReload是怎么做到的_.md
  
   - 36_如何通过工具链优化开发调试效率_.md
  
   - 37_如何检测并优化FlutterApp的整体性能表现_.md
  
   - 38_如何通过自动化测试提高交付质量_.md
  
   - 39_线上出现问题，该如何做好异常捕获与信息采集_.md
  
   - 40_衡量FlutterApp线上质量，我们需要关注这三个指标.md
  
   - 41_组件化和平台化，该如何组织合理稳定的Flutter工程结构_.md
  
   - 42_如何构建高效的FlutterApp打包发布环境_.md
  
   - 43_如何构建自己的Flutter混合开发框架（一）_.md
  
   - 44_如何构建自己的Flutter混合开发框架（二）_.md
  
   - 结束语_勿畏难，勿轻略.md
  
   - 结课测试_关于Flutter的这些知识，你都掌握了吗_.md
  
   - 特别放送｜温故而知新，与你说说专栏的那些思考题.md
  