site_name: WebAssembly入门课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_我们为什么要了解WebAssembly_.md
  
   - 01_基础篇_学习此课程你需要了解哪些基础知识_.md
  
   - 02_历史篇_为什么会有WebAssembly这样一门技术_.md
  
   - 03_WebAssembly是一门新的编程语言吗_.md
  
   - 04_WebAssembly模块的基本组成结构到底有多简单_.md
  
   - 05_二进制编码_WebAssembly微观世界的基本数据规则是什么_.md
  
   - 06_WAT_如何让一个WebAssembly二进制模块的内容易于解读_.md
  
   - 07_WASI_你听说过WebAssembly操作系统接口吗_.md
  
   - 08_API_在WebAssemblyMVP标准下你能做到哪些事_.md
  
   - 09_WebAssembly能够为Web前端框架赋能吗_.md
  
   - 10_有哪些已经投入生产的WebAssembly真实案例_.md
  
   - 11_WebAssembly在物联网、多媒体与云技术方面有哪些创新实践_.md
  
   - 12_有哪些优秀的WebAssembly编译器与运行时_.md
  
   - 13_LLVM_如何将自定义的语言编译到WebAssembly_.md
  
   - 14_有哪些正在行进中的WebAssemblyPost-MVP提案_.md
  
   - 15_如何实现一个WebAssembly在线多媒体处理应用（一）_.md
  
   - 16_如何实现一个WebAssembly在线多媒体处理应用（二）_.md
  
   - 17_如何实现一个WebAssembly在线多媒体处理应用（三）_.md
  
   - 18_如何进行Wasm应用的调试与分析_.md
  
   - 19_如何应用WASI及其相关生态_.md
  
   - 20_总结与答疑.md
  
   - 结束语_WebAssembly，未来已来.md
  
   - 期末测试｜这些WebAssembly的问题，你都掌握了吗_.md
  