site_name: Redis核心技术与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_这样学Redis，才能技高一筹.md
  
   - 01_基本架构_一个键值数据库包含什么_.md
  
   - 02_数据结构_快速的Redis有哪些慢操作_.md
  
   - 03_高性能IO模型_为什么单线程Redis能那么快_.md
  
   - 04_AOF日志_宕机了，Redis如何避免数据丢失_.md
  
   - 05_内存快照_宕机后，Redis如何实现快速恢复_.md
  
   - 06_数据同步_主从库如何实现数据一致_.md
  
   - 07_哨兵机制_主库挂了，如何不间断服务_.md
  
   - 08_哨兵集群_哨兵挂了，主从库还能切换吗_.md
  
   - 09_切片集群_数据增多了，是该加内存还是加实例_.md
  
   - 10_第1～9讲课后思考题答案及常见问题答疑.md
  
   - 11_“万金油”的String，为什么不好用了_.md
  
   - 12_有一亿个keys要统计，应该用哪种集合_.md
  
   - 13_GEO是什么_还可以定义新的数据类型吗_.md
  
   - 14_如何在Redis中保存时间序列数据_.md
  
   - 15_消息队列的考验_Redis有哪些解决方案_.md
  
   - 16_异步机制_如何避免单线程模型的阻塞_.md
  
   - 17_为什么CPU结构也会影响Redis的性能_.md
  
   - 18_波动的响应延迟_如何应对变慢的Redis_（上）.md
  
   - 19_波动的响应延迟_如何应对变慢的Redis_（下）.md
  
   - 20_删除数据后，为什么内存占用率还是很高_.md
  
   - 21_缓冲区_一个可能引发“惨案”的地方.md
  
   - 22_第11～21讲课后思考题答案及常见问题答疑.md
  
   - 23_旁路缓存_Redis是如何工作的_.md
  
   - 24_替换策略_缓存满了怎么办_.md
  
   - 25_缓存异常（上）_如何解决缓存和数据库的数据不一致问题_.md
  
   - 26_缓存异常（下）_如何解决缓存雪崩、击穿、穿透难题_.md
  
   - 27_缓存被污染了，该怎么办_.md
  
   - 28_Pika_如何基于SSD实现大容量Redis_.md
  
   - 29_无锁的原子操作_Redis如何应对并发访问_.md
  
   - 30_如何使用Redis实现分布式锁_.md
  
   - 31_事务机制_Redis能实现ACID属性吗_.md
  
   - 32_Redis主从同步与故障切换，有哪些坑_.md
  
   - 33_脑裂_一次奇怪的数据丢失.md
  
   - 34_第23~33讲课后思考题答案及常见问题答疑.md
  
   - 35_CodisVSRedisCluster_我该选择哪一个集群方案_.md
  
   - 36_Redis支撑秒杀场景的关键技术和实践都有哪些_.md
  
   - 37_数据分布优化_如何应对数据倾斜_.md
  
   - 38_通信开销_限制RedisCluster规模的关键因素.md
  
   - 期中测试题_一套习题，测出你的掌握程度.md
  
   - 期中测试题答案_这些问题，你都答对了吗_.md
  
   - 39_Redis6.0的新特性_多线程、客户端缓存与安全.md
  
   - 40_Redis的下一步_基于NVM内存的实践.md
  
   - 41_第35～40讲课后思考题答案及常见问题答疑.md
  
   - 加餐（一）_经典的Redis学习资料有哪些_.md
  
   - 加餐（二）_用户Kaito_我是如何学习Redis的_.md
  
   - 加餐（三）_用户Kaito_我希望成为在压力中成长的人.md
  
   - 加餐（四）_Redis客户端如何与服务器端交换命令和数据_.md
  
   - 加餐（五）_Redis有哪些好用的运维工具_.md
  
   - 加餐（六）_Redis的使用规范小建议.md
  
   - 加餐（七）_从微博的Redis实践中，我们可以学到哪些经验_.md
  
   - 期末测试_这些Redis核心知识，你都掌握了吗_.md
  
   - 结束语_从学习Redis到向Redis学习.md
  