site_name: 软件工程之美

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_你为什么应该学好软件工程_.md
  
   - 特别放送_从软件工程的角度解读任正非的新年公开信.md
  
   - 学习攻略_怎样学好软件工程_.md
  
   - 01_到底应该怎样理解软件工程_.md
  
   - 02_工程思维_把每件事都当作一个项目来推进.md
  
   - 03_瀑布模型_像工厂流水线一样把软件开发分层化.md
  
   - 04_瀑布模型之外，还有哪些开发模型_.md
  
   - 05_敏捷开发到底是想解决什么问题_.md
  
   - 06_大厂都在用哪些敏捷方法_（上）.md
  
   - 07_大厂都在用哪些敏捷方法_（下）.md
  
   - 08_怎样平衡软件质量与时间成本范围的关系_.md
  
   - “一问一答”第1期_30个软件开发常见问题解决策略.md
  
   - 09_为什么软件工程项目普遍不重视可行性分析_.md
  
   - 10_如果你想技术转管理，先来试试管好一个项目.md
  
   - 11_项目计划_代码未动，计划先行.md
  
   - 12_流程和规范_红绿灯不是约束，而是用来提高效率.md
  
   - 13_白天开会，加班写代码的节奏怎么破_.md
  
   - 14_项目管理工具_一切管理问题，都应思考能否通过工具解决.md
  
   - 15_风险管理_不能盲目乐观，凡事都应该有B计划.md
  
   - 16_怎样才能写好项目文档_.md
  
   - 17_需求分析到底要分析什么_怎么分析_.md
  
   - 18_原型设计_如何用最小的代价完成产品特性_.md
  
   - 19_作为程序员，你应该有产品意识.md
  
   - 20_如何应对让人头疼的需求变更问题_.md
  
   - “一问一答”第2期_30个软件开发常见问题解决策略.md
  
   - 21_架构设计_普通程序员也能实现复杂系统_.md
  
   - 22_如何为项目做好技术选型_.md
  
   - 23_架构师_不想当架构师的程序员不是好程序员.md
  
   - 24_技术债务_是继续修修补补凑合着用，还是推翻重来_.md
  
   - 25_有哪些方法可以提高开发效率_.md
  
   - 26_持续交付_如何做到随时发布新版本到生产环境_.md
  
   - 27_软件工程师的核心竞争力是什么_（上）.md
  
   - 28_软件工程师的核心竞争力是什么_（下）.md
  
   - 29_自动化测试_如何把Bug杀死在摇篮里_.md
  
   - 30_用好源代码管理工具，让你的协作更高效.md
  
   - “一问一答”第3期_18个软件开发常见问题解决策略.md
  
   - 31_软件测试要为产品质量负责吗_.md
  
   - 32_软件测试_什么样的公司需要专职测试_.md
  
   - 33_测试工具_为什么不应该通过QQ_微信_邮件报Bug_.md
  
   - 34_账号密码泄露成灾，应该怎样预防_.md
  
   - 35_版本发布_软件上线只是新的开始.md
  
   - 36_DevOps工程师到底要做什么事情_.md
  
   - 37_遇到线上故障，你和高手的差距在哪里_.md
  
   - 38_日志管理_如何借助工具快速发现和定位产品问题_.md
  
   - 39_项目总结_做好项目复盘，把经验变成能力.md
  
   - “一问一答”第4期_14个软件开发常见问题解决策略.md
  
   - 40_最佳实践_小团队如何应用软件工程_.md
  
   - 41_为什么程序员的业余项目大多都死了_.md
  
   - 42_反面案例_盘点那些失败的软件项目.md
  
   - 43_以VSCode为例，看大型开源项目是如何应用软件工程的_.md
  
   - 44_微软、谷歌、阿里巴巴等大厂是怎样应用软件工程的_.md
  
   - 45_从软件工程的角度看微服务、云计算、人工智能这些新技术.md
  
   - “一问一答”第5期（内含彩蛋）_22个软件开发常见问题解决策略.md
  
   - 结束语_万事皆项目，软件工程无处不在.md
  
   - 结课测试_这些软件工程知识，你都掌握了吗_.md
  