site_name: 商业思维案例笔记

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 热点解读｜练习课_GPT、市场和我，究竟何去何从_.md
  
   - 开篇词｜商业思维是每个互联网人都应具备的升维能力.md
  
   - 01_导读_我们说商业思维时，到底在说什么_.md
  
   - 02_成本_马斯克的猎鹰火箭为什么可以这么便宜_.md
  
   - 03_效率_为什么Facebook的客户以中小为主_.md
  
   - 04_收益（上）_阳光养猪场等网赚游戏为什么在19年后突然火了_.md
  
   - 05_收益（下）_阳光养猪场等网赚游戏为什么在19年后突然火了_.md
  
   - 06_体验_链家为什么可以从线下起家反超所有互联网房企_.md
  
   - 07_练习课_如何判断自己的业务是否靠谱_.md
  
   - 复习加餐｜4组图看懂价值创造！.md
  
   - 08_二维解构_社区团购为什么成为2020年巨头必争的赛道_.md
  
   - 09_二八法则_为什么Flipboard等免费精品阅读领域做不大呢_.md
  
   - 10_盐铁官营_手机厂商为什么可以在移动互联网时代闷声发大财_.md
  
   - 11_分层运营_外卖市场上为什么美团可以后发制人_.md
  
   - 12_时间刻度（上）_为什么优酷土豆会从行业第一下滑到行业第三_.md
  
   - 13_时间刻度（下）_为什么优酷土豆会从行业第一下滑到行业第三_.md
  
   - 14_练习课（上）_如何用结构性思考去理解20多年中国互联网发展的变化_.md
  
   - 15_练习课（下）_如何用结构性思考去理解20多年中国互联网发展的变化_.md
  
   - 复习加餐｜5组图读懂商业洞察！.md
  
   - 16｜权限_为什么360在移动端没有延续PC端的辉煌_.md
  
   - 17｜环境_为什么百度在移动时代坐视字节的崛起_.md
  
   - 18｜规则_豌豆荚做不起来应用内搜索_.md
  
   - 19｜资本（上）_为什么杨浩涌二次创业一定要融大钱_.md
  
   - 20｜资本（下）_为什么杨浩涌二次创业一定要融大钱_.md
  
   - 21｜角色（上）_失败的来往和成功的钉钉后面为什么都是陈航（无招）_.md
  
   - 22｜角色（下）_失败的来往和成功的钉钉后面为什么都是陈航（无招）_.md
  
   - 大咖助阵｜演进_YY诞生17年，微信诞生11年，为什么语音类产品依旧层出不穷_.md
  
   - 23｜练习课_如何在实际工作中规避方法论的过度影响_.md
  
   - 复习加餐｜5组图摸透非规律世界！.md
  
   - 24｜错位_拼多多缘何在电商市场的红海中再杀出一片天_.md
  
   - 25｜玩法_大逃杀电影出了那么多年，为什么才诞生绝地求生_.md
  
   - 26｜边界（上）_没有任何硬件基础的小米，为什么可以成为国内第一手机厂商_.md
  
   - 27｜边界（下）_没有任何硬件基础的小米，为什么可以成为国内第一手机厂商_.md
  
   - 28｜练习课_如何用开放的心态来挖掘非共识机会_.md
  
   - 复习加餐｜3组图探寻非共识机会！.md
  
   - 29｜平台_91手机助手卖掉为什么是明智的选择_.md
  
   - 30｜盈利_哈啰单车为什么可以在一地鸡毛的共享单车中逆势杀出_.md
  
   - 31｜基础_WiFi万能钥匙为什么崛起又为什么落寞_.md
  
   - 32｜需求_为什么大部分O2O项目都是漫天烟花_.md
  
   - 33｜竞争_为什么共享充电宝不是一个好生意_.md
  
   - 34｜练习课_终局思维还可以运用在日常生活哪些方面_.md
  
   - 复习加餐｜5组图收获终局思维！.md
  
   - 35｜行业_如何在一周内快速了解一个行业_.md
  
   - 36｜呈现_对上汇报方案什么样的结构最有效_.md
  
   - 37｜目标_如果目标是让猪上树，最好的方式是什么_.md
  
   - 结束语｜橘子不是唯一的水果.md
  
   - 双周行业热点追踪｜字节去肥增瘦，抖音爱奇艺联姻，每日优鲜破产.md
  
   - 双周行业热点评论｜字节去肥增瘦，抖音爱奇艺联姻，每日优鲜破产.md
  
   - 中秋加餐｜《商业思维案例笔记》推荐书单.md
  
   - 中秋加餐｜直播回顾_B站的商业化之路到底难在哪_.md
  
   - 热点速递｜《羊了个羊》原来根本没想让我过关！.md
  