site_name: 邱岳的产品实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_和自己较劲，一个产品经理的实战历程.md
  
   - 01_如何验证你的产品创意_.md
  
   - 02_如何锤炼你的产品创意.md
  
   - 03_要不要相信你的调查问卷.md
  
   - 04_用最少的资源给你的产品试试水.md
  
   - 05_如何快速利用MVP思想.md
  
   - 06_如何做好产品立项.md
  
   - 07_产品发布的那些坑儿.md
  
   - 08_产品增长越来越难，到底应该怎么办_.md
  
   - 09_产品增长的核心，究竟是什么_.md
  
   - 10_你需要组建增长团队吗，应该如何组建呢_.md
  
   - 11_产品增长有哪些业务公式与关键指标_（上）.md
  
   - 12_产品增长有哪些业务公式与关键指标_（下）.md
  
   - 13_产品做增长的过程中，有哪些关键套路_.md
  
   - 14_实战增长，我们要知道哪些事儿_.md
  
   - 15_增长执行时，需要哪些关键的能力_.md
  
   - 16_当钩子靠不住时，如何提高用户留存_（上）.md
  
   - 17_当钩子靠不住时，如何提高用户留存_（下）.md
  
   - 18_如何把你的新用户转化为忠实的长期用户_.md
  
   - 19_满眼尽是“病毒”“裂变”，到底什么是传播和获客的正确姿势_（上）.md
  
   - 20_满眼尽是“病毒”“裂变”，到底什么是传播和获客的正确姿势_（下）.md
  
   - 21_增长黑客的阴暗面.md
  
   - 22_产品经理需要具备哪些基本的数据能力和意识_.md
  
   - 23_突发式流量数据暴跌，产品经理应该如何应对_【分析篇】.md
  
   - 24_突发式流量数据暴跌，产品经理应该如何应对_【拆解篇】.md
  
   - 25_突发式流量数据暴跌，产品经理应该如何应对_【处理篇】.md
  
   - 26_当收集数据的前后，我们应该做什么_.md
  
   - 27_从具体业务出发，如何利用数据辅助你的决策_.md
  
   - 28_那些数据不能告诉你的事儿_尽信“数”不如无“数”.md
  
   - 29_每个产品经理都要掌握的基本商业概念是什么_.md
  
   - 30_如何提高你的商业产品收入_（上）.md
  
   - 31_如何提高你的商业产品收入（下）.md
  
   - 32_“烧钱获客”中有哪些值得学习的商业逻辑_.md
  
   - 33_“烧钱获客”的正确姿势有哪些_.md
  
   - 34_如何具备赚钱的意识与能力_.md
  
   - 35_对产品经理来说，做小程序有什么价值_.md
  
   - 36_如何利用小程序去做传播_.md
  
   - 37_关于小程序，一些你应该知道的事儿.md
  
   - 产品会客厅_千万级用户的产品是如何打造的_.md
  
   - 产品会客厅_极客时间产品规划大揭秘.md
  
   - 产品会客厅_没有项目管理经验，如何推动团队一起完成任务_.md
  
   - 产品会客厅_需求评审怎么做，如何区分什么是真的用户需求_.md
  
   - 产品会客厅_一次简洁并有效的产品分析需要怎么做_.md
  
   - 产品会客厅_从“分享有赏”案例讲起，如何做关键决策_.md
  
   - 产品会客厅_从案例出发，如何利用数据分析来验证新功能的效果_.md
  
   - 产品会客厅_产品经理面试究竟考什么_.md
  
   - 产品会客厅_产品经理的职业发展，你在哪个阶段_.md
  
   - 产品会客厅_在产品的获客与传播上，“极客时间”做了些什么_.md
  
   - 产品会客厅_从流量型平台转到资源匮乏平台，如何应对业务变化_.md
  
   - 产品会客厅_面向大众的通用型产品VS受众面少的垂直领域，二者如何博弈_（上）.md
  
   - 产品会客厅_面向大众的通用型产品VS受众面少的垂直领域，二者如何博弈_（下）.md
  
   - 产品会客厅_未来的产品会有怎样的发展趋势_.md
  
   - 产品会客厅_产品经理如何上手体验一个App_（上）.md
  
   - 产品会客厅_产品经理如何上手体验一个App（下）.md
  
   - 产品会客厅_从“极客时间”App的信息架构上，我们能学到什么_.md
  
   - 产品会客厅_专栏销量过万是一种什么样的感受_.md
  
   - 尾声_祝你胸怀远大，心狠手辣.md
  
   - 结课测试_关于产品的这些知识，你都掌握了吗_.md
  