site_name: 前端全链路优化实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜前端全链路是提升解决问题效率的关键.md
  
   - 01｜前世今生_前端全链路的演进历程.md
  
   - 02｜重要性_为什么要对前端服务做全链路的监控和优化_.md
  
   - 03｜全链路流程_前端全链路的关键路径有哪些_.md
  
   - 04｜数据结构（上）_如何设计全链路数据模型.md
  
   - 05｜数据结构（下）_如何设计页面业务问题相关的数据结构_.md
  
   - 06｜指纹ID_如何通过指纹ID关联全链路日志_.md
  
   - 07｜网页指标_为何要用WebVitals分析Web应用的用户体验_.md
  
   - 08｜网页指标_如何快速把WebVitals集成到实际项目_.md
  
   - 09｜接口指标_监听接口状态，收集页面接口异常数据.md
  
   - 10｜资源和脚本异常指标_监听资源和脚本状态，收集异常数据.md
  
   - 11｜用户行为指标_如何有效监听用户交互行为_.md
  
   - 12｜自定义指标_如何通过自定义指标，监控前端页面更多状态.md
  
   - 13｜关联后端_如何通过Skywalking把接口关联到后端服务_.md
  
   - 14｜数据上报方案_如何在不影响用户体验下实现数据上报_.md
  
   - 15｜何为监控_让监控成为快速发现问题的重要方法.md
  
   - 16_监控规则_设定有效的查询条件规则.md
  
   - 17｜数据可视化_可视化监控真的重要吗_.md
  
   - 18｜告警与决策_如何解决监控警告中焦虑的问题_.md
  
   - 19_卡顿_页面响应卡顿是什么原因造成的_.md
  
   - 20｜渲染_如何优化布局和渲染，提升网页响应速度_.md
  
   - 21｜首字节_有效衡量网页首字节时间指标.md
  
   - 22｜加载速度_提升网页首字节时间的问题.md
  
   - 23｜白屏_如何优化APP内前端白屏时间_.md
  
   - 24｜跳出率_如何快速显示页面内容，降低跳出率_.md
  
   - 25｜字体_解决自定义字体加载问题.md
  
   - 26｜视口_可视内容对全链路的重要性.md
  
   - 27｜图片_调整策略，优化图片加载问题.md
  
   - 28｜视觉_避免发生布局偏移影响用户交互.md
  
   - 29｜经验_优化就是减少请求数量和质量.md
  
   - 30｜工具_最容易被忽视的工具和定位问题路径.md
  
   - 结束语｜持续成长，成为最好的自己.md
  
   - 结课测试｜来赴一场满分之约.md
  