site_name: 跟着高手学复盘

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_为什么每个人都应该学会复盘_.md
  
   - 01_CLAP模型_一个优秀的复盘模型是什么样的_.md
  
   - 02_OPTM框架_怎么使用CLAP模型_.md
  
   - 03_教练技术_怎么做复盘才能化解冲突_.md
  
   - 04_制度和文化_怎么营造复盘环境_.md
  
   - 05_三角法_怎么组建复盘团队_.md
  
   - 06_MECE原则_怎么准备复盘资料_.md
  
   - 07_五步法_如何召开一次高效的复盘会议_.md
  
   - 08_事实比较_如何快速比较目标与结果_.md
  
   - 09_分析原因_梳理逻辑时怎样找到切入点_.md
  
   - 10_洞察规律_怎样更新认知才能找准发力点_.md
  
   - 11_OKR_怎样根据复盘结论制定计划_.md
  
   - 12_DoubleCheck_怎么检查评估一次复盘的效果_.md
  
   - 13_案例导学_我是怎么帮助企业做复盘的_.md
  
   - 14_战略升级_5年增长100倍的跨境电商做对了什么_.md
  
   - 15_业务关键点_改进一个点业绩增长50%_.md
  
   - 16_组织结构设计_变动一个职位，就能带来100万_月的增量吗_.md
  
   - 17_高效赋能_怎么建立流程才能把人效提升3倍_.md
  
   - 18_人才培养_怎么把人才转化成实际生产力_.md
  
   - 19_预算制定_人头和财务预算到底怎么定_.md
  
   - 结束语_复盘，见天地见众生见自己.md
  
   - 结课测试题｜这些关于复盘的知识你都掌握了吗_.md
  
   - 春节荐书（一）_《原则》_在不确定中找到确定.md
  
   - 春节荐书（二）_《人类简史》_故事的力量.md
  