site_name: 深度学习推荐系统实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_从0开始搭建一个深度学习推荐系统.md
  
   - 01_技术架构_深度学习推荐系统的经典技术架构长啥样_.md
  
   - 02_SparrowRecSys_我们要实现什么样的推荐系统_.md
  
   - 03_深度学习基础_你打牢深度学习知识的地基了吗_.md
  
   - 国庆策划_关于深度学习推荐系统，我有这些资料想推荐给你.md
  
   - 国庆策划_深度学习推荐系统基础，你掌握了多少_.md
  
   - 04_特征工程_推荐系统有哪些可供利用的特征_.md
  
   - 05_特征处理_如何利用Spark解决特征处理问题_.md
  
   - 06_Embedding基础_所有人都在谈的Embedding技术到底是什么_.md
  
   - 07_Embedding进阶_如何利用图结构数据生成GraphEmbedding_.md
  
   - 08_Embedding实战_如何使用Spark生成Item2vec和GraphEmbedding_.md
  
   - 答疑_基础架构篇&#43;特征工程篇常见问题解答.md
  
   - 09_线上服务_如何在线上提供高并发的推荐服务_.md
  
   - 10_存储模块_如何用Redis解决推荐系统特征的存储问题_.md
  
   - 11_召回层_如何快速又准确地筛选掉不相关物品_.md
  
   - 12_局部敏感哈希_如何在常数时间内搜索Embedding最近邻_.md
  
   - 13_模型服务_怎样把你的离线模型部署到线上_.md
  
   - 14_融会贯通_SparrowRecSys中的电影相似推荐功能是如何实现的_.md
  
   - 答疑_线上服务篇留言问题详解.md
  
   - 15_协同过滤_最经典的推荐模型，我们应该掌握什么_.md
  
   - 16_深度学习革命_深度学习推荐模型发展的整体脉络是怎样的_.md
  
   - 模型实战准备（一）_TensorFlow入门和环境配置.md
  
   - 模型实战准备（二）_模型特征、训练样本的处理.md
  
   - 17_Embedding&#43;MLP_如何用TensorFlow实现经典的深度学习模型_.md
  
   - 18｜Wide&amp;amp;Deep_怎样让你的模型既有想象力又有记忆力_.md
  
   - 19｜NeuralCF_如何用深度学习改造协同过滤_.md
  
   - 20_DeepFM_如何让你的模型更好地处理特征交叉_.md
  
   - 21｜注意力机制、兴趣演化_推荐系统如何抓住用户的心_.md
  
   - 22｜强化学习_让推荐系统像智能机器人一样自主学习.md
  
   - 特别加餐_“银弹”不可靠，最优的模型结构该怎么找_.md
  
   - 23｜实战_如何用深度学习模型实现SparrowRecSys的个性化推荐功能_.md
  
   - 24_离线评估_常用的推荐系统离线评估方法有哪些_.md
  
   - 25_评估指标_我们可以用哪些指标来衡量模型的好坏_.md
  
   - 特别加餐｜TensorFlow的模型离线评估实践怎么做_.md
  
   - 26_在线测试_如何在推荐服务器内部实现A_B测试_.md
  
   - 27_评估体系_如何解决A_B测试资源紧张的窘境_.md
  
   - 28_业界经典_YouTube深度学习推荐系统的经典架构长什么样_.md
  
   - 29_图神经网络_Pinterest是如何应用图神经网络的_.md
  
   - 30_流处理平台_Flink是如何快速识别用户兴趣，实现实时推荐的_.md
  
   - 31｜模型迭代_阿里巴巴是如何迭代更新推荐模型的_.md
  
   - 32_强化学习案例_美团是如何在推荐系统中落地强化学习的_.md
  
   - 33｜技术权衡_解决方案这么多，哪个最合适_.md
  
   - 结束语｜深度学习时代需要什么样的推荐工程师_.md
  
   - 期末考试_“深度学习推荐系统”100分试卷等你来挑战！.md
  