site_name: 黄勇的OKR实战笔记

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_神奇的OKR工作法.md
  
   - 入学测验_你对OKR了解有多少_.md
  
   - 01_你想要快速理解OKR吗_看这篇文章就够了.md
  
   - 02_如果有人再问你，OKR与KPI有何区别_你可以这样告诉他.md
  
   - 03_如何在企业中有效落地OKR_你必须掌握这些技巧.md
  
   - 04_在落地OKR之前，需要具备哪些先决条件_.md
  
   - 05_OKR好用，但一不小心就容易被误用，为什么呢_.md
  
   - 06_OKR大咖说_产品技术部门的OKR从何而来.md
  
   - 07_热点问题答疑（一）_你的OKR用对了吗_.md
  
   - 08_如何轻松制定OKR_方法原来如此简单.md
  
   - 09_推动团队高效执行OKR，你知道这些技巧吗_.md
  
   - 10_OKR评估没你想象的那么难，其实你可以这么做！.md
  
   - 11_都说OKR赢在复盘，为何大家都忽略了这个重要环节_.md
  
   - 12_落地OKR效果不理想_可能是你身边缺少一位“教练”.md
  
   - 13_OKR大咖说_一个可供创业公司参考的OKR落地实践.md
  
   - 14_热点问题答疑（二）_你该如何看待OKR_（文末有彩蛋）.md
  
   - 15_技术团队真的是“成本中心”吗_如何改变这一现状_.md
  
   - 16_大家都说“向上管理”很重要，你想学一些“套路”吗_.md
  
   - 17_跨部门协同费劲，沟通效率低，如何粉碎“部门墙”_.md
  
   - 18_企业“腰部力量”不够，如何提升中层领导力_.md
  
   - 19_敏捷与OKR都是为了“拥抱变化”，两者如何无缝整合_.md
  
   - 20_OKR大咖说_OKR还有哪些应用场景_.md
  
   - 21_热点问题答疑（三）_如何计算研发团队人效_.md
  
   - 22_面试人才好纠结，新人试用难考核_你其实可以这样做.md
  
   - 23_人才激励方式众多，哪种方式最有效_.md
  
   - 24_敏捷时代下你该如何做绩效管理_.md
  
   - 25_如何告别无效会议_不妨试试这六招.md
  
   - 26_OKR最容易踩的10个坑，你踩过几个_.md
  
   - 27_OKR大咖说_在硅谷公司使用OKR时，一个资深员工的体验和感悟.md
  
   - 28_如何避免“跳槽”变“跳坑”_.md
  
   - 29_他们落地OKR都失败了，原因出在哪儿_.md
  
   - 30_用什么工具，能加强OKR落地效果_.md
  
   - 31_工作之外如何应用OKR_以真实案例为例.md
  
   - 32_积分制、游戏化，一种新型的团队管理和协同方式.md
  
   - 33_无所不能的OKR，它会变成“银弹”吗_.md
  
   - 34_OKR大咖说_为何有些文化的因，结不出OKR的果_.md
  
   - 35_OKR学习测验_你是否真的学会了OKR_.md
  
   - 结束语_OKR助我一路成长.md
  
   - 加餐_一幅图，让你快速入门OKR.md
  
   - 加餐_OKR思维能助你学会向上管理_.md
  
   - 加餐_如何灵活运用OKR_.md
  
   - 加餐_新型的团队管理和协作方式是怎样的_.md
  