site_name: Go语言项目开发实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_从0开始搭建一个企业级Go应用.md
  
   - 01_IAM系统概述_我们要实现什么样的Go项目_.md
  
   - 02_环境准备_如何安装和配置一个基本的Go开发环境_.md
  
   - 03_项目部署_如何快速部署IAM系统_.md
  
   - 04_规范设计（上）_项目开发杂乱无章，如何规范_.md
  
   - 05_规范设计（下）_commit信息风格迥异、难以阅读，如何规范_.md
  
   - 06_目录结构设计_如何组织一个可维护、可扩展的代码目录_.md
  
   - 07_工作流设计_如何设计合理的多人开发模式_.md
  
   - 08_研发流程设计（上）_如何设计Go项目的开发流程_.md
  
   - 09_研发流程设计（下）_如何管理应用的生命周期_.md
  
   - 10_设计方法_怎么写出优雅的Go项目_.md
  
   - 11_设计模式_Go常用设计模式概述.md
  
   - 12_API风格（上）_如何设计RESTfulAPI_.md
  
   - 13_API风格（下）_RPCAPI介绍.md
  
   - 14_项目管理_如何编写高质量的Makefile_.md
  
   - 15_研发流程实战_IAM项目是如何进行研发流程管理的_.md
  
   - 16_代码检查_如何进行静态代码检查_.md
  
   - 17_API文档_如何生成SwaggerAPI文档_.md
  
   - 18_错误处理（上）_如何设计一套科学的错误码_.md
  
   - 19_错误处理（下）_如何设计错误包_.md
  
   - 20_日志处理（上）_如何设计日志包并记录日志_.md
  
   - 21_日志处理（下）_手把手教你从0编写一个日志包.md
  
   - 22_应用构建三剑客_Pflag、Viper、Cobra核心功能介绍.md
  
   - 23_应用构建实战_如何构建一个优秀的企业应用框架_.md
  
   - 24_Web服务_Web服务核心功能有哪些，如何实现_.md
  
   - 25_认证机制_应用程序如何进行访问认证_.md
  
   - 26_IAM项目是如何设计和实现访问认证功能的_.md
  
   - 27_权限模型_5大权限模型是如何进行资源授权的_.md
  
   - 28_控制流（上）_通过iam-apiserver设计，看Web服务的构建.md
  
   - 29｜控制流（下）_iam-apiserver服务核心功能实现讲解.md
  
   - 30_ORM_CURD神器GORM包介绍及实战.md
  
   - 31_数据流_通过iam-authz-server设计，看数据流服务的设计.md
  
   - 32_数据处理_如何高效处理应用程序产生的数据_.md
  
   - 33_SDK设计（上）_如何设计出一个优秀的GoSDK_.md
  
   - 34_SDK设计（下）_IAM项目GoSDK设计和实现.md
  
   - 35_效率神器_如何设计和实现一个命令行客户端工具_.md
  
   - 36_代码测试（上）_如何编写Go语言单元测试和性能测试用例_.md
  
   - 37_代码测试（下）_Go语言其他测试类型及IAM测试介绍.md
  
   - 38｜性能分析（上）_如何分析Go语言代码的性能_.md
  
   - 39｜性能分析（下）_APIServer性能测试和调优实战.md
  
   - 40_软件部署实战（上）_部署方案及负载均衡、高可用组件介绍.md
  
   - 41_软件部署实战（中）_IAM系统生产环境部署实战.md
  
   - 42_软件部署实战（下）_IAM系统安全加固、水平扩缩容实战.md
  
   - 43｜技术演进（上）_虚拟化技术演进之路.md
  
   - 44｜技术演进（下）_软件架构和应用生命周期技术演进之路.md
  
   - 45｜基于Kubernetes的云原生架构设计.md
  
   - 46_如何制作Docker镜像_.md
  
   - 47_如何编写Kubernetes资源定义文件_.md
  
   - 48_IAM容器化部署实战.md
  
   - 49_服务编排（上）_Helm服务编排基础知识.md
  
   - 50_服务编排（下）_基于Helm的服务编排部署实战.md
  
   - 51_基于GitHubActions的CI实战.md
  
   - 特别放送_给你一份清晰、可直接套用的Go编码规范.md
  
   - 特别放送_给你一份Go项目中最常用的Makefile核心语法.md
  
   - 特别放送_GoModules依赖包管理全讲.md
  
   - 特别放送_IAM排障指南.md
  
   - 特别放送_GoModules实战.md
  
   - 特别放送_分布式作业系统设计和实现.md
  
   - 直播加餐｜如何从小白进阶成Go语言专家_.md
  
   - 结束语_如何让自己的Go研发之路走得更远_.md
  
   - 期末考试｜《Go语言项目开发实战》满分试卷，等你来挑战！.md
  