site_name: Java性能调优实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_怎样才能做好性能调优_.md
  
   - 01_如何制定性能调优标准_.md
  
   - 02_如何制定性能调优策略_.md
  
   - 03_字符串性能优化不容小觑，百M内存轻松存储几十G数据.md
  
   - 04_慎重使用正则表达式.md
  
   - 05_ArrayList还是LinkedList_使用不当性能差千倍.md
  
   - 加餐_推荐几款常用的性能测试工具.md
  
   - 06_Stream如何提高遍历集合效率_.md
  
   - 07_深入浅出HashMap的设计与优化.md
  
   - 08_网络通信优化之I_O模型_如何解决高并发下I_O瓶颈_.md
  
   - 09_网络通信优化之序列化_避免使用Java序列化.md
  
   - 10_网络通信优化之通信协议_如何优化RPC网络通信_.md
  
   - 11_答疑课堂_深入了解NIO的优化实现原理.md
  
   - 12_多线程之锁优化（上）_深入了解Synchronized同步锁的优化方法.md
  
   - 13_多线程之锁优化（中）_深入了解Lock同步锁的优化方法.md
  
   - 14_多线程之锁优化（下）_使用乐观锁优化并行操作.md
  
   - 15_多线程调优（上）_哪些操作导致了上下文切换_.md
  
   - 16_多线程调优（下）_如何优化多线程上下文切换_.md
  
   - 17_并发容器的使用_识别不同场景下最优容器.md
  
   - 18_如何设置线程池大小_.md
  
   - 19_如何用协程来优化多线程业务_.md
  
   - 20_答疑课堂_模块三热点问题解答.md
  
   - 加餐_什么是数据的强、弱一致性_.md
  
   - 21_磨刀不误砍柴工_欲知JVM调优先了解JVM内存模型.md
  
   - 22_深入JVM即时编译器JIT，优化Java编译.md
  
   - 23_如何优化垃圾回收机制_.md
  
   - 24_如何优化JVM内存分配_.md
  
   - 25_内存持续上升，我该如何排查问题_.md
  
   - 26_答疑课堂_模块四热点问题解答.md
  
   - 27_单例模式_如何创建单一对象优化系统性能_.md
  
   - 28_原型模式与享元模式_提升系统性能的利器.md
  
   - 29_如何使用设计模式优化并发编程_.md
  
   - 30_生产者消费者模式_电商库存设计优化.md
  
   - 31_装饰器模式_如何优化电商系统中复杂的商品价格策略_.md
  
   - 32_答疑课堂_模块五思考题集锦.md
  
   - 33_MySQL调优之SQL语句_如何写出高性能SQL语句_.md
  
   - 34_MySQL调优之事务_高并发场景下的数据库事务调优.md
  
   - 35_MySQL调优之索引_索引的失效与优化.md
  
   - 36_记一次线上SQL死锁事故_如何避免死锁_.md
  
   - 37_什么时候需要分表分库_.md
  
   - 38_电商系统表设计优化案例分析.md
  
   - 39_数据库参数设置优化，失之毫厘差之千里.md
  
   - 40_答疑课堂_MySQL中InnoDB的知识点串讲.md
  
   - 41_如何设计更优的分布式锁_.md
  
   - 42_电商系统的分布式事务调优.md
  
   - 43_如何使用缓存优化系统性能_.md
  
   - 44_记一次双十一抢购性能瓶颈调优.md
  
   - 结束语_栉风沐雨，砥砺前行！.md
  
   - 期末测试_有关Java性能调优，你掌握了多少呢_.md
  