site_name: 业务开发算法50讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜真实世界的算法，和你想的不一样.md
  
   - 先导篇｜诶，这个gitdiff好像不是很直观_.md
  
   - 01｜动态数组_按需分配的vector为什么要二倍扩容_.md
  
   - 02｜双向链表_list如何实现高效地插入与删除_.md
  
   - 03｜双端队列_并行计算中的工作窃取算法如何实现_.md
  
   - 04｜栈_函数调用的秘密究竟是什么_.md
  
   - 05｜HashMap_一个优秀的散列表是怎么来的_.md
  
   - 06｜TreeMap_红黑树真的有那么难吗_.md
  
   - 07｜堆_如何实现一个高效的优先队列_.md
  
   - 08｜外部排序_如何为TB级数据排序_.md
  
   - 09｜二分_如何高效查询Kafka中的消息_.md
  
   - 10｜搜索算法_一起来写一个简单的爬虫_.md
  
   - 11｜字符串匹配_如何实现最快的grep工具.md
  
   - 12｜拓扑排序_Webpack是如何确定构建顺序的_.md
  
   - 13｜哈夫曼树_HTTP2.0是如何更快传输协议头的_.md
  
   - 14｜调度算法_操作系统中的进程是如何调度的_.md
  
   - 15｜LRU_在虚拟内存中页面是如何置换的_.md
  
   - 16｜日志型文件系统_写入文件的时候断电了会发生什么_.md
  
   - 17｜选路算法_Dijkstra是如何解决最短路问题的_.md
  
   - 18｜选路算法_链路状态算法是如何分发全局信息的.md
  
   - 19｜选路算法_距离矢量算法为什么会产生无穷计算问题_.md
  
   - 20｜滑动窗口_TCP是如何进行流量控制和拥塞控制的_.md
  
   - 21｜分而治之_MapReduce如何解决大规模分布式计算问题.md
  
   - 22｜PageRank_谷歌是如何计算网页排名的.md
  
   - 23｜Raft_分布式系统间如何达成共识_.md
  
   - 24｜UUID_如何高效生成全局的唯一ID_.md
  
   - 25｜一致性哈希_如何在集群上合理分配流量_.md
  
   - 26｜B+Tree_PostgreSQL的索引是如何建立的_.md
  
   - 27｜LSMTree_LevelDB的索引是如何建立的_.md
  
   - 28｜MVCC_如何突破数据库并发读写性能瓶颈_.md
  
   - 29｜位图_如何用更少空间对大量数据进行去重和排序_.md
  
   - 30｜布隆过滤器_如何解决Redis缓存穿透问题_.md
  
   - 31｜跳表_Redis是如何存储有序集合的_.md
  
   - 32｜时间轮_Kafka是如何实现定时任务的_.md
  
   - 33｜限流算法_如何防止系统过载_.md
  
   - 34｜前缀树_Web框架中如何实现路由匹配_.md
  
   - 特别策划｜面试_BAT面试三关准备方法大揭秘.md
  
   - 即学即练｜基础数据结构篇_复习卡&amp;amp;算法题特训.md
  
   - 即学即练｜基础算法思想篇_复习卡&amp;amp;算法题特训.md
  
   - 即学即练｜操作系统篇_复习卡&amp;amp;算法题特训.md
  
   - 即学即练｜计算机网络篇_复习卡&amp;amp;算法题特训.md
  
   - 即学即练｜分布式篇_复习卡一键直达.md
  
   - 即学即练｜工程实战篇_复习卡一键直达.md
  
   - 35｜洗牌算法_随机的哲学，如何用程序来洗一副牌_.md
  
   - 36｜分布式事务_如何理解两阶段提交_.md
  
   - 37｜Thrift编码方法_为什么RPC往往不采用JSON作为网络传输格式_.md
  
   - 38｜倒排索引_搜索引擎是如何做全文检索的_.md
  
   - 39｜Geohash_点外卖时我们是如何查找到附近餐厅的_.md
  
   - 40｜垃圾回收_现代语言是如何自动管理回收内存的_.md
  
   - 结束语｜在技术的世界里享受思维的乐趣.md
  
   - 期末测试｜来赴一场满分之约！.md
  