site_name: SQL必知必会

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 旅程再启｜SQLCopilot_AI时代下的SQL查询与优化.md
  
   - 加餐01｜TexttoSQL_自然语言写SQL查询.md
  
   - 加餐02｜SQL实战_银行场景的数据查询与优化.md
  
   - 开篇词丨SQL可能是你掌握的最有用的技能.md
  
   - 01丨了解SQL_一门半衰期很长的语言.md
  
   - 02丨DBMS的前世今生.md
  
   - 03丨学会用数据库的方式思考SQL是如何执行的.md
  
   - 04丨使用DDL创建数据库&amp;amp;数据表时需要注意什么_.md
  
   - 05丨检索数据_你还在SELECT_么_.md
  
   - 06丨数据过滤_SQL数据过滤都有哪些方法_.md
  
   - 07丨什么是SQL函数_为什么使用SQL函数可能会带来问题_.md
  
   - 08丨什么是SQL的聚集函数，如何利用它们汇总表的数据_.md
  
   - 09丨子查询_子查询的种类都有哪些，如何提高子查询的性能_.md
  
   - 10丨常用的SQL标准有哪些，在SQL92中是如何使用连接的_.md
  
   - 11丨SQL99是如何使用连接的，与SQL92的区别是什么_.md
  
   - 12丨视图在SQL中的作用是什么，它是怎样工作的_.md
  
   - 13丨什么是存储过程，在实际项目中用得多么_.md
  
   - 14丨什么是事务处理，如何使用COMMIT和ROLLBACK进行操作_.md
  
   - 15丨初识事务隔离_隔离的级别有哪些，它们都解决了哪些异常问题_.md
  
   - 16丨游标_当我们需要逐条处理数据时，该怎么做_.md
  
   - 17丨如何使用Python操作MySQL_.md
  
   - 18丨SQLAlchemy_如何使用PythonORM框架来操作MySQL_.md
  
   - 19丨基础篇总结_如何理解查询优化、通配符以及存储过程_.md
  
   - 20丨当我们思考数据库调优的时候，都有哪些维度可以选择_.md
  
   - 21丨范式设计_数据表的范式有哪些，3NF指的是什么_.md
  
   - 22丨反范式设计_3NF有什么不足，为什么有时候需要反范式设计_.md
  
   - 23丨索引的概览_用还是不用索引，这是一个问题.md
  
   - 24丨索引的原理_我们为什么用B&#43;树来做索引_.md
  
   - 25丨Hash索引的底层原理是什么_.md
  
   - 26丨索引的使用原则_如何通过索引让SQL查询效率最大化_.md
  
   - 27丨从数据页的角度理解B&#43;树查询.md
  
   - 28丨从磁盘I_O的角度理解SQL查询的成本.md
  
   - 29丨为什么没有理想的索引_.md
  
   - 30丨锁_悲观锁和乐观锁是什么_.md
  
   - 31丨为什么大部分RDBMS都会支持MVCC_.md
  
   - 32丨查询优化器是如何工作的_.md
  
   - 33丨如何使用性能分析工具定位SQL执行慢的原因_.md
  
   - 34丨答疑篇_关于索引以及缓冲池的一些解惑.md
  
   - 35丨数据库主从同步的作用是什么，如何解决数据不一致问题_.md
  
   - 36丨数据库没有备份，没有使用Binlog的情况下，如何恢复数据_.md
  
   - 37丨SQL注入_你的SQL是如何被注入的_.md
  
   - 38丨如何在Excel中使用SQL语言_.md
  
   - 39丨WebSQL_如何在H5中存储一个本地数据库_.md
  
   - 40丨SQLite_为什么微信用SQLite存储聊天记录_.md
  
   - 41丨初识Redis_Redis为什么会这么快_.md
  
   - 42丨如何使用Redis来实现多用户抢票问题.md
  
   - 43丨如何使用Redis搭建玩家排行榜_.md
  
   - 44丨DBMS篇总结和答疑_用SQLite做词云.md
  
   - 45丨数据清洗_如何使用SQL对数据进行清洗_.md
  
   - 46丨数据集成_如何对各种数据库进行集成和转换_.md
  
   - 47丨如何利用SQL对零售数据进行分析_.md
  
   - 结束语_互联网的下半场是数据驱动的时代.md
  
   - 期末测试丨对于SQL的有关内容，你掌握了多少呢_.md
  