site_name: 深入拆解Tomcat&amp;amp;Jetty

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_Java程序员如何快速成长_.md
  
   - 01_Web容器学习路径.md
  
   - 02_HTTP协议必知必会.md
  
   - 03_你应该知道的Servlet规范和Servlet容器.md
  
   - 04_实战_纯手工打造和运行一个Servlet.md
  
   - 05_Tomcat系统架构（上）_ 连接器是如何设计的_.md
  
   - 06_Tomcat系统架构（下）_聊聊多层容器的设计.md
  
   - 07_Tomcat如何实现一键式启停_.md
  
   - 08_Tomcat的“高层们”都负责做什么_.md
  
   - 09_比较_Jetty架构特点之Connector组件.md
  
   - 10_比较_Jetty架构特点之Handler组件.md
  
   - 11_总结_从Tomcat和Jetty中提炼组件化设计规范.md
  
   - 12_实战_优化并提高Tomcat启动速度.md
  
   - 13_热点问题答疑（1）_如何学习源码_.md
  
   - 14_NioEndpoint组件_Tomcat如何实现非阻塞I_O_.md
  
   - 15_Nio2Endpoint组件_Tomcat如何实现异步I_O_.md
  
   - 16_AprEndpoint组件_TomcatAPR提高I_O性能的秘密.md
  
   - 17_Executor组件_Tomcat如何扩展Java线程池_.md
  
   - 18_新特性_Tomcat如何支持WebSocket_.md
  
   - 19_比较_Jetty的线程策略EatWhatYouKill.md
  
   - 20_总结_Tomcat和Jetty中的对象池技术.md
  
   - 21_总结_Tomcat和Jetty的高性能、高并发之道.md
  
   - 22_热点问题答疑（2）_内核如何阻塞与唤醒进程_.md
  
   - 23_Host容器_Tomcat如何实现热部署和热加载_.md
  
   - 24_Context容器（上）_Tomcat如何打破双亲委托机制_.md
  
   - 25_Context容器（中）_Tomcat如何隔离Web应用_.md
  
   - 26_Context容器（下）_Tomcat如何实现Servlet规范_.md
  
   - 27_新特性_Tomcat如何支持异步Servlet_.md
  
   - 28_新特性_SpringBoot如何使用内嵌式的Tomcat和Jetty_.md
  
   - 29_比较_Jetty如何实现具有上下文信息的责任链_.md
  
   - 30_热点问题答疑（3）_Spring框架中的设计模式.md
  
   - 31_Logger组件_Tomcat的日志框架及实战.md
  
   - 32_Manager组件_Tomcat的Session管理机制解析.md
  
   - 33_Cluster组件_Tomcat的集群通信原理.md
  
   - 特别放送_如何持续保持对学习的兴趣_.md
  
   - 34_JVMGC原理及调优的基本思路.md
  
   - 35_如何监控Tomcat的性能_.md
  
   - 36_TomcatI_O和线程池的并发调优.md
  
   - 37_Tomcat内存溢出的原因分析及调优.md
  
   - 38_Tomcat拒绝连接原因分析及网络优化.md
  
   - 39_Tomcat进程占用CPU过高怎么办_.md
  
   - 40_谈谈Jetty性能调优的思路.md
  
   - 41_热点问题答疑（4）_Tomcat和Jetty有哪些不同_.md
  
   - 结束语_静下心来，品味经典.md
  
   - 结课测试_这些Tomcat&Jetty的知识你都掌握了吗_.md
  