site_name: 10x程序员工作法

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_程序员解决的问题，大多不是程序问题.md
  
   - 01_10x程序员是如何思考的_.md
  
   - 02_以终为始_如何让你的努力不白费_.md
  
   - 04_接到需求任务，你要先做哪件事_.md
  
   - 05_持续集成_集成本身就是写代码的一个环节.md
  
   - 06_精益创业_产品经理不靠谱，你该怎么办_.md
  
   - 07_解决了很多技术问题，为什么你依然在“坑”里_.md
  
   - 08_为什么说做事之前要先进行推演_.md
  
   - 09_你的工作可以用数字衡量吗_.md
  
   - 10_迭代0:启动开发之前，你应该准备什么_.md
  
   - 答疑解惑_如何管理你的上级_.md
  
   - 划重点_关于“以终为始”，你要记住的9句话.md
  
   - 11_向埃隆·马斯克学习任务分解.md
  
   - 12_测试也是程序员的事吗_.md
  
   - 13_先写测试，就是测试驱动开发吗_.md
  
   - 14_大师级程序员的工作秘笈.md
  
   - 15_一起练习_手把手带你分解任务.md
  
   - 16_为什么你的测试不够好_.md
  
   - 17_程序员也可以“砍”需求吗_.md
  
   - 18_需求管理_太多人给你安排任务，怎么办_.md
  
   - 19_如何用最小的代价做产品_.md
  
   - 答疑解惑_如何分解一个你不了解的技术任务_.md
  
   - 划重点_关于“任务分解”，你要重点掌握哪些事_.md
  
   - 20_为什么世界和你的理解不一样_.md
  
   - 21_你的代码为谁而写_.md
  
   - 22_轻量级沟通_你总是在开会吗_.md
  
   - 23_可视化_一种更为直观的沟通方式.md
  
   - 24_快速反馈_为什么你们公司总是做不好持续集成_.md
  
   - 25_开发中的问题一再出现，应该怎么办_.md
  
   - 26_作为程序员，你也应该聆听用户声音.md
  
   - 用户故事_站在前人的肩膀上，领取属于你的高效工作秘籍.md
  
   - 27_尽早暴露问题_为什么被指责的总是你_.md
  
   - 28_结构化_写文档也是一种学习方式.md
  
   - 答疑解惑_持续集成，一条贯穿诸多实践的主线.md
  
   - 划重点_一次关于“沟通反馈”主题内容的复盘.md
  
   - 加餐_你真的了解重构吗_.md
  
   - 29_“懒惰”应该是所有程序员的骄傲.md
  
   - 30_一个好的项目自动化应该是什么样子的_.md
  
   - 31_程序员怎么学习运维知识_.md
  
   - 32_持续交付_有持续集成就够了吗_.md
  
   - 33_如何做好验收测试_.md
  
   - 34_你的代码是怎么变混乱的_.md
  
   - 35_总是在说MVC分层架构，但你真的理解分层吗_.md
  
   - 36_为什么总有人觉得5万块钱可以做一个淘宝_.md
  
   - 37_先做好DDD再谈微服务吧，那只是一种部署形式.md
  
   - 答疑解惑_持续集成、持续交付，然后呢_.md
  
   - 划重点_“自动化”主题的重点内容回顾汇总.md
  
   - 38_新入职一家公司，怎么快速进入工作状态_.md
  
   - 39_面对遗留系统，你应该这样做.md
  
   - 40_我们应该如何保持竞争力_.md
  
   - 答疑解惑_如何在实际工作中推行新观念_.md
  
   - 划重点_“综合运用”主题内容的全盘回顾.md
  
   - 总复习_重新审视“最佳实践”.md
  
   - 总复习_重新来“看书”.md
  
   - 03_DoD的价值_你完成了工作，为什么他们还不满意_.md
  
   - 结束语_少做事，才能更有效地工作.md
  
   - 结课测试_这些10x程序员工作法的知识你都掌握了吗_.md
  
   - 第二季回归_我带着软件设计课回来了！.md
  
   - 第三季回归_我们一起来写好代码！.md
  
   - 第四季回归_通向高质量代码之路.md
  
   - 特别加餐_ChatGPT来了，你的编程效率提高了吗_.md
  
   - 私享直播｜1小时参透程序员的AI三重境界.md
  
   - 私享直播｜程序员的上限、下限和第二曲线.md
  
   - 第五季回归｜让我们一起共赴AI时代！.md
  