site_name: 即时消息技术剖析与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_搞懂“实时交互”的IM技术，将会有什么新机遇_.md
  
   - 01_架构与特性_一个完整的IM系统是怎样的_.md
  
   - 02_消息收发架构_为你的App，加上实时通信功能.md
  
   - 03_轮询与长连接_如何解决消息的实时到达问题_.md
  
   - 04_ACK机制_如何保证消息的可靠投递_.md
  
   - 05_消息序号生成器_如何保证你的消息不会乱序_.md
  
   - 06_HttpDNS和TLS_你的消息聊天真的安全吗_.md
  
   - 07_分布式锁和原子性_你看到的未读消息提醒是真的吗_.md
  
   - 08_智能心跳机制_解决网络的不确定性.md
  
   - 09_分布式一致性_让你的消息支持多终端漫游.md
  
   - 10_自动智能扩缩容_直播互动场景中峰值流量的应对.md
  
   - 11_期中实战_动手写一个简易版的IM系统.md
  
   - 12_服务高可用_保证核心链路稳定性的流控和熔断机制.md
  
   - 13_HTTPTunnel_复杂网络下消息通道高可用设计的思考.md
  
   - 14_分片上传_如何让你的图片、音视频消息发送得更快_.md
  
   - 15_CDN加速_如何让你的图片、视频、语音消息浏览播放不卡_.md
  
   - 16_APNs_聊一聊第三方系统级消息通道的事.md
  
   - 17_Cache_多级缓存架构在消息系统中的应用.md
  
   - 18_Docker容器化_说一说IM系统中模块水平扩展的实现.md
  
   - 19_端到端Trace_消息收发链路的监控体系搭建.md
  
   - 20_存储和并发_万人群聊系统设计中的几个难点.md
  
   - 21_期末实战_为你的简约版IM系统，加上功能.md
  
   - 22_答疑解惑_不同即时消息场景下架构实现上的异同.md
  
   - 结束语_真正的高贵，不是优于别人，而是优于过去的自己.md
  
   - 结课测试_“即时消息技术剖析与实战”100分试卷等你来挑战！.md
  