site_name: 手把手带你写一门编程语言

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜让我们来写一门计算机语言吧.md
  
   - 课前热身｜开始学习之前我们要准备什么_.md
  
   - 01｜实现一门超简单的语言最快需要多久_.md
  
   - 02｜词法分析_识别Token也可以很简单吗_.md
  
   - 03｜支持表达式_解析表达式和解析语句有什么不同_.md
  
   - 04｜如何让我们的语言支持变量和类型_.md
  
   - 05｜函数实现_是时候让我们的语言支持函数和返回值了.md
  
   - 06｜怎么支持条件语句和循环语句_.md
  
   - 07｜怎么设计属于我们自己的虚拟机和字节码_.md
  
   - 08｜基于TypeScript的虚拟机（一）_实现一个简单的栈机.md
  
   - 09｜基于TypeScript的虚拟机（二）_丰富特性，支持跳转语句.md
  
   - 10｜基于C语言的虚拟机（一）_实现一个简单的栈机.md
  
   - 11｜基于C语言的虚拟机（二）_性能增长10倍的秘密.md
  
   - 12｜物理机上程序运行的硬件环境是怎么样的_.md
  
   - 13｜物理机上程序运行的软件环境是怎么样的_.md
  
   - 14｜汇编代码学习（一）_熟悉CPU架构和指令集.md
  
   - 15｜汇编语言学习（二）_熟悉X86汇编代码.md
  
   - 16｜生成本地代码第1关_先把基础搭好.md
  
   - 17｜生成本地代码第2关_变量存储、函数调用和栈帧维护.md
  
   - 18｜生成本地代码第3关_实现完整的功能.md
  
   - 19｜怎么实现一个更好的寄存器分配算法_原理篇.md
  
   - 20｜怎么实现一个更好的寄存器分配算法_实现篇.md
  
   - 21｜加深对栈的理解_实现尾递归和尾调用优化.md
  
   - 期中测试｜快来检验你在起步篇的学习成果吧.md
  
   - “他山之石”｜Sugar_这门课你可以试试这么学.md
  
   - “屠龙之秘”｜实现计算机语言这样的技术能用在哪里_（一）.md
  
   - 22｜增强编译器前端功能第1步_再识数据流分析技术.md
  
   - 23｜增强编译器前端功能第2步_增强类型体系.md
  
   - 24｜增强编译器前端功能第3步_全面的集合运算.md
  
   - 25｜增强编译器前端功能第4步_综合运用多种语义分析技术.md
  
   - 26｜增强更丰富的类型第1步_如何支持浮点数_.md
  
   - 27｜增加更丰富的类型第2步_如何支持字符串_.md
  
   - 28｜增加更丰富的类型第3步_支持数组.md
  
   - 29｜面向对象编程第1步_先把基础搭好.md
  
   - 30｜面向对象编程第2步_剖析一些技术细节.md
  
   - 31｜面向对象编程第3步_支持继承和多态.md
  
   - 32｜函数式编程第1关_实现高阶函数.md
  
   - 33｜函数式编程第2关_实现闭包特性.md
  
   - 34｜内存管理第1关_Arena技术和元数据.md
  
   - 35｜内存管理第2关_实现垃圾回收.md
  
   - 36｜节点之海_怎么生成基于图的IR_.md
  
   - 37_从AST到IR_体会数据流和控制流思维.md
  
   - 38｜中端优化第1关_实现多种本地优化.md
  
   - 39｜中端优化第2关_全局优化要怎么搞_.md
  
   - 40｜中端优化第3关_一起来挑战过程间优化.md
  
   - 41｜后端优化_生成LIR和指令选择.md
  
   - 42｜到这里，我们的收获和未尽的工作有哪些_.md
  
   - 期末考试｜实现编程语言这些核心知识点，你掌握得咋样了_.md
  
   - 结束语｜等待你大展身手的那些领域.md
  