site_name: 现代C&#43;&#43;编程实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 新春寄语_35年码龄程序员_人生漫长，走点弯路在所难免.md
  
   - 新春福利_C&#43;&#43;好书荐读.md
  
   - 加餐_部分课后思考题答案合集.md
  
   - 特别放送｜好消息_我的C&#43;&#43;新书即将出版.md
  
   - 开篇词_C&#43;&#43;这么难，为什么我们还要用C&#43;&#43;_.md
  
   - 课前必读_有关术语发音及环境要求.md
  
   - 01_堆、栈、RAII_C&#43;&#43;里该如何管理资源_.md
  
   - 02_自己动手，实现C&#43;&#43;的智能指针.md
  
   - 03_右值和移动究竟解决了什么问题_.md
  
   - 04_容器汇编I_比较简单的若干容器.md
  
   - 05_容器汇编II_需要函数对象的容器.md
  
   - 06_异常_用还是不用，这是个问题.md
  
   - 07_迭代器和好用的新for循环.md
  
   - 08_易用性改进I_自动类型推断和初始化.md
  
   - 09_易用性改进II_字面量、静态断言和成员函数说明符.md
  
   - 10_到底应不应该返回对象_.md
  
   - 11_Unicode_进入多文字支持的世界.md
  
   - 12_编译期多态_泛型编程和模板入门.md
  
   - 13_编译期能做些什么_一个完整的计算世界.md
  
   - 14_SFINAE_不是错误的替换失败是怎么回事_.md
  
   - 15_constexpr_一个常态的世界.md
  
   - 16_函数对象和lambda_进入函数式编程.md
  
   - 17_函数式编程_一种越来越流行的编程范式.md
  
   - 18_应用可变模板和tuple的编译期技巧.md
  
   - 19_thread和future_领略异步中的未来.md
  
   - 20_内存模型和atomic_理解并发的复杂性.md
  
   - 21_工具漫谈_编译、格式化、代码检查、排错各显身手.md
  
   - 22_处理数据类型变化和错误_optional、variant、expected和Herbception.md
  
   - 23_数字计算_介绍线性代数和数值计算库.md
  
   - 24_Boost_你需要的“瑞士军刀”.md
  
   - 25_两个单元测试库_C&#43;&#43;里如何进行单元测试_.md
  
   - 26_Easylogging&#43;&#43;和spdlog_两个好用的日志库.md
  
   - 27_C&#43;&#43;RESTSDK_使用现代C&#43;&#43;开发网络应用.md
  
   - 28_Concepts_如何对模板进行约束_.md
  
   - 29_Ranges_无迭代器的迭代和更方便的组合.md
  
   - 30_Coroutines_协作式的交叉调度执行.md
  
   - 结束语_终点已达，行程还要继续.md
  
   - 结课问卷获奖用户名单.md
  
   - 期末测试_对于现代C&#43;&#43;，你掌握了多少呢_.md
  
   - 第二季回归｜拿下Vim，让编程效率神器为我所用.md
  
   - 旅程再启｜那些关于C&#43;&#43;的新认知.md
  
   - 31｜new和delete背后_分配函数和释放函数.md
  
   - 32｜容器里的内存管理_分配器.md
  
   - 33｜性能测试的正确姿势_性能、时间和优化.md
  
   - 34｜快速分配和释放内存_内存池.md
  
   - 35_发现和识别内存问题_内存调试实践.md
  
   - 36｜访问对象的代理对象_视图类型.md
  
   - 37｜参数传递的正确方法和模板的二进制膨胀.md
  
   - 38_折叠表达式_高效的编译期展开.md
  
   - 39_如何在编译期玩转字符串_.md
  
   - 40_如何在编译期遍历数据_.md
  
   - 41｜对象传参和返回的最佳实践.md
  