site_name: 性能工程高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_代码不要眼前的苟且，而要效率的提升和性能的优化.md
  
   - 01_程序员为什么要关心代码性能_.md
  
   - 02_程序员也要关心整个系统和公司成本吗_.md
  
   - 03_导读_专栏是怎么设计的_需要哪些知识_.md
  
   - 04_性能工程三定律_IT业和性能优化工作的“法律法规”.md
  
   - 05_概率统计和排队论_做性能工作必须懂的数理基础.md
  
   - 06_性能数据的分析_如何从大量数据中看出想要的信号_.md
  
   - 07_性能数据的展示_一图胜千言，说出你的数据故事.md
  
   - 08_经验总结_必须熟记的一组常用性能数字.md
  
   - 09_性能测试的种类_如何快准狠地抓住一个测试的本质_.md
  
   - 10_性能测试的规划和步骤_为什么性能测试不容易一蹴而就呢_.md
  
   - 11_性能测试的工具_七大测试场景如何选择高质量的测试工具_.md
  
   - 12_九条性能测试的经验和教训_如何保证测试结果可靠且可重复_.md
  
   - 13_性能测试的工程集成_如何与产品开发和运维业务有机集成_.md
  
   - 14_性能分析概述_性能问题归根结底是什么原因_.md
  
   - 15_CPU篇_如何让CPU的运行不受阻碍_.md
  
   - 16_内存篇_如何减少延迟提升内存分配效率_.md
  
   - 17_存储篇_如何根据性能优缺点选择最合适的存储系统_.md
  
   - 18_网络篇_如何步步拆解处理复杂的网络性能问题_.md
  
   - 19_性能优化六大原则_三要三不要，快速有效地进行优化.md
  
   - 20_性能优化十大策略_如何系统地有层次地优化性能问题_.md
  
   - 21_CPU案例_如何提高LLC（最后一级缓存）的命中率_.md
  
   - 22_系统案例_如何提高iTLB（指令地址映射）的命中率_.md
  
   - 23_存储案例_如何降低SSD峰值延迟_.md
  
   - 24_跨层案例_如何优化程序、OS和存储系统的交互_.md
  
   - 25_如何在生产环境中进行真实的容量测试_.md
  
   - 26_怎么规划和控制数据库的复制延迟大小_.md
  
   - 27_多任务环境中的Java性能问题，怎样才能不让程序互相干扰_.md
  
   - 28_网络数据传输慢，问题到底出在哪了_.md
  
   - 29_如何彻底发挥SSD的潜力_.md
  
   - 30_服务器的管理和部署_工业界近几年有哪些发展趋势_.md
  
   - 31_规划部署数据中心要考虑哪些重要因素_.md
  
   - 32_服务的容量规划_怎样才能做到有备无患_.md
  
   - 33_服务效率提升_如何降低公司运营成本_.md
  
   - 34_服务需求控制管理_每种需求都是必需的吗_.md
  
   - 35_职业发展_从“锦上添花”到“不可或缺”.md
  
   - 36_如何成为优秀的性能和容量工程师_.md
  
   - 结束语_不愁明月尽，自有夜珠来.md
  
   - 结课问卷获奖用户名单.md
  
   - 结课测试_这些性能工程知识，你真的掌握了吗_.md
  