site_name: 陈天·Rust编程第一课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜让Rust成为你的下一门主力语言.md
  
   - 01｜内存_值放堆上还是放栈上，这是一个问题.md
  
   - 02｜串讲_编程开发中，那些你需要掌握的基本概念.md
  
   - 加餐｜这个专栏你可以怎么学，以及Rust是否值得学_.md
  
   - 03｜初窥门径_从你的第一个Rust程序开始！.md
  
   - 04｜gethandsdirty_来写个实用的CLI小工具.md
  
   - 05｜gethandsdirty_做一个图片服务器有多难_.md
  
   - 06｜gethandsdirty_SQL查询工具怎么一鱼多吃_.md
  
   - 07｜所有权_值的生杀大权到底在谁手上_.md
  
   - 08｜所有权_值的借用是如何工作的_.md
  
   - 09｜所有权_一个值可以有多个所有者么_.md
  
   - 10｜生命周期_你创建的值究竟能活多久_.md
  
   - 11｜内存管理_从创建到消亡，值都经历了什么_.md
  
   - 加餐｜愚昧之巅_你的Rust学习常见问题汇总.md
  
   - 12｜类型系统_Rust的类型系统有什么特点_.md
  
   - 13｜类型系统_如何使用trait来定义接口_.md
  
   - 14｜类型系统_有哪些必须掌握的trait_.md
  
   - 15｜数据结构_这些浓眉大眼的结构竟然都是智能指针_.md
  
   - 16｜数据结构_Vec&amp;lt;T&amp;gt;、&amp;amp;[T]、Box&amp;lt;[T]&amp;gt;，你真的了解集合容器么_.md
  
   - 17｜数据结构_软件系统核心部件哈希表，内存如何布局_.md
  
   - 18｜错误处理_为什么Rust的错误处理与众不同_.md
  
   - 19｜闭包_FnOnce、FnMut和Fn，为什么有这么多类型_.md
  
   - 20｜4Steps_如何更好地阅读Rust源码_.md
  
   - 21｜阶段实操（1）_构建一个简单的KVserver-基本流程.md
  
   - 22｜阶段实操（2）_构建一个简单的KVserver-基本流程.md
  
   - 加餐｜期中测试_来写一个简单的grep命令行.md
  
   - 加餐｜期中测试_参考实现讲解.md
  
   - 23｜类型系统_如何在实战中使用泛型编程_.md
  
   - 24｜类型系统_如何在实战中使用traitobject_.md
  
   - 25｜类型系统_如何围绕trait来设计和架构系统_.md
  
   - 加餐｜Rust2021版次问世了！.md
  
   - 26｜阶段实操（3）_构建一个简单的KVserver-高级trait技巧.md
  
   - 27｜生态系统_有哪些常有的Rust库可以为我所用_.md
  
   - 28｜网络开发（上）_如何使用Rust处理网络请求_.md
  
   - 29｜网络开发（下）_如何使用Rust处理网络请求_.md
  
   - 30｜UnsafeRust_如何用C&#43;&#43;的方式打开Rust_.md
  
   - 31｜FFI_Rust如何和你的语言架起沟通桥梁_.md
  
   - 32｜实操项目_使用PyO3开发Python3模块.md
  
   - 33｜并发处理（上）_从atomics到Channel，Rust都提供了什么工具_.md
  
   - 34｜并发处理（下）_从atomics到Channel，Rust都提供了什么工具_.md
  
   - 35｜实操项目_如何实现一个基本的MPSCchannel_.md
  
   - 用户故事｜绝望之谷_改变从学习开始.md
  
   - 36｜阶段实操（4）_构建一个简单的KVserver-网络处理.md
  
   - 37｜阶段实操（5）_构建一个简单的KVserver-网络安全.md
  
   - 38｜异步处理_Future是什么_它和async_await是什么关系_.md
  
   - 39｜异步处理_async_await内部是怎么实现的_.md
  
   - 40｜异步处理_如何处理异步IO_.md
  
   - 41｜阶段实操（6）_构建一个简单的KVserver-异步处理.md
  
   - 42｜阶段实操（7）_构建一个简单的KVserver-如何做大的重构_.md
  
   - 43｜生产环境_真实世界下的一个Rust项目包含哪些要素_.md
  
   - 44｜数据处理_应用程序和数据如何打交道_.md
  
   - 45｜阶段实操（8）_构建一个简单的KVserver-配置_测试_监控_CI_CD.md
  
   - 46｜软件架构_如何用Rust架构复杂系统_.md
  
   - 大咖助场｜开悟之坡（上）_Rust的现状、机遇与挑战.md
  
   - 大咖助场｜开悟之坡（下）_Rust的现状、机遇与挑战.md
  
   - 用户故事｜语言不仅是工具，还是思维方式.md
  
   - 加餐｜代码即数据_为什么我们需要宏编程能力_.md
  
   - 加餐｜宏编程（上）_用最“笨”的方式撰写宏.md
  
   - 加餐｜宏编程（下）_用syn_quote优雅地构建宏.md
  
   - 结束语｜永续之原_Rust学习，如何持续精进_.md
  
   - 期末测试｜来赴一场满分之约！.md
  
   - 特别策划｜学习锦囊（一）_听听课代表们怎么说.md
  
   - 特别策划｜学习锦囊（二）_听听课代表们怎么说.md
  
   - 特别策划｜学习锦囊（三）_听听课代表们怎么说.md
  
   - 特别策划｜生成式AI_哪些开发环节可能被颠覆_.md
  