site_name: 安全攻防技能30讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_别说你没被安全困扰过.md
  
   - 01_安全的本质_数据被窃取后，你能意识到问题来源吗_.md
  
   - 02_安全原则_我们应该如何上手解决安全问题_.md
  
   - 03_密码学基础_如何让你的密码变得“不可见”_.md
  
   - 04_身份认证_除了账号密码，我们还能怎么做身份认证_.md
  
   - 05_访问控制_如何选取一个合适的数据保护方案_.md
  
   - 06_XSS_当你“被发送”了一条微博时，到底发生了什么_.md
  
   - 07_SQL注入_明明设置了强密码，为什么还会被别人登录_.md
  
   - 08_CSRF_SSRF_为什么避免了XSS，还是“被发送”了一条微博_.md
  
   - 09_反序列化漏洞_使用了编译型语言，为什么还是会被注入_.md
  
   - 10_信息泄露_为什么黑客会知道你的代码逻辑_.md
  
   - 11_插件漏洞_我的代码看起来很安全，为什么还会出现漏洞_.md
  
   - 12_权限提升和持久化_为什么漏洞修复了，黑客还是能够自由进出_.md
  
   - 13_Linux系统安全_多人共用服务器，如何防止别人干“坏事”_.md
  
   - 14_网络安全_和别人共用Wi-Fi时，你的信息会被窃取吗_.md
  
   - 15_Docker安全_在虚拟的环境中，就不用考虑安全了吗_.md
  
   - 16_数据库安全_数据库中的数据是如何被黑客拖取的_.md
  
   - 17_分布式安全_上百个分布式节点，不会出现“内奸”吗_.md
  
   - 18_安全标准和框架_怎样依“葫芦”画出好“瓢”_.md
  
   - 19_防火墙_如何和黑客“划清界限”_.md
  
   - 20_WAF_如何为漏洞百出的Web应用保驾护航_.md
  
   - 21_IDS_当黑客绕过了防火墙，你该如何发现_.md
  
   - 22_RASP_写规则写得烦了_尝试一下更底层的IDS.md
  
   - 23_SIEM_一个人管理好几个安全工具，如何高效运营_.md
  
   - 24_SDL_怎样才能写出更“安全”的代码_.md
  
   - 25_业务安全体系_对比基础安全，业务安全有哪些不同_.md
  
   - 26_产品安全方案_如何降低业务对黑灰产的诱惑_.md
  
   - 27_风控系统_如何从海量业务数据中，挖掘黑灰产_.md
  
   - 28_机器学习_如何教会机器识别黑灰产_.md
  
   - 29_设备指纹_面对各种虚拟设备，如何进行对抗_.md
  
   - 30_安全运营_“黑灰产”打了又来，如何正确处置_.md
  
   - 模块串讲（一）_Web安全_如何评估用户数据和资产数据面临的威胁_.md
  
   - 模块串讲（二）_Linux系统和应用安全_如何大范围提高平台安全性_.md
  
   - 模块串讲（三）_安全防御工具_如何选择和规划公司的安全防御体系_.md
  
   - 加餐1_数据安全_如何防止内部员工泄露商业机密_.md
  
   - 加餐2_前端安全_如何打造一个可信的前端环境_.md
  
   - 加餐3_职业发展_应聘安全工程师，我需要注意什么_.md
  
   - 加餐4_个人成长_学习安全，哪些资源我必须要知道_.md
  
   - 加餐5_安全新技术_IoT、IPv6、区块链中的安全新问题.md
  
   - 结束语_在与黑客的战役中，我们都是盟友！.md
  
   - 结课测试｜这些安全知识，你都掌握了吗_.md
  