site_name: 技术领导力实战笔记

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_卓越的团队，必然有一个卓越的领导者.md
  
   - 第1讲_你的能力模型决定你的职位.md
  
   - 第2讲_七位CTO纵论技术领导者核心能力.md
  
   - 第3讲_CEO实话实说_我需要这样的CTO.md
  
   - 第4讲_技术领导者不等于技术管理者.md
  
   - 大咖对话_从几个工程师到2000&#43;个工程师的技术团队成长秘诀.md
  
   - 第5讲_CTO的三重境界.md
  
   - 第6讲_像CEO一样思考.md
  
   - 第7讲_要制定技术战略，先看清局面.md
  
   - 第8讲_技术领导力就是“成事”的能力.md
  
   - 大咖对话_未来技术负责人与首席增长官将如何协作_.md
  
   - 第9讲_CTO是商业思维和技术思维交汇的那个点.md
  
   - 第10讲_创业公司CTO的认知升级.md
  
   - 第11讲_最合适的技术才是最有价值的技术.md
  
   - 第12讲_谈谈CTO在商业战略中的定位.md
  
   - 大咖问答_打造自己的个人品牌，你也可以.md
  
   - 第13讲_把脉高效执行的关键要素.md
  
   - 第14讲_从零开始搭建轻量级研发团队.md
  
   - 第15讲_定制高效研发流程.md
  
   - 第16讲_培养中层团队的管理认知.md
  
   - 大咖问答_发现下一个小米，不是只能靠运气.md
  
   - 第17讲_团队成长要靠技巧和体系.md
  
   - 第18讲_做到这四点，团队必定飞速成长.md
  
   - 第19讲_将企业打造成一所终身大学.md
  
   - 第20讲_论团队管理与共同升级.md
  
   - 大咖对话_技术人真正需要的是升维思考.md
  
   - 第21讲_绩效管理的目标不仅仅是绩效考核.md
  
   - 第22讲_验证研发团队价值的绩效考核机制.md
  
   - 第23讲_产品技术团队OKR使用法则.md
  
   - 第24讲_996、987，程序员加班文化你怎么看_.md
  
   - 大咖对话_技术管理者应该向优秀的体育教练学习.md
  
   - 第25讲_建立有效的员工淘汰机制.md
  
   - 第26讲_让细节的“病毒”感染你的团队.md
  
   - 第27讲_如何在不同组织文化下推行技术管理.md
  
   - 第28讲_业务高速增长期的团队管理_“知轻重、重绸缪、调缓急”.md
  
   - 大咖对话_让团队成员持续的enjoy.md
  
   - 第29讲_被80%的人误解的工程师文化.md
  
   - 第30讲_关于工程师文化的六个问题.md
  
   - 第31讲_五位技术领导者的文化构建实战.md
  
   - 第32讲_文化是管理的那只无形之手.md
  
   - 大咖对话_创业就是把自己过去的经验快速的产品化.md
  
   - 第33讲_选对的人，做正确的事情.md
  
   - 第34讲_打好技术团队搭建的基础.md
  
   - 第35讲_做个合格的技术岗位面试官.md
  
   - 第36讲_“高潜力人才”的内部培养.md
  
   - 大咖对话_如何高效管理8000&#43;规模的技术团队.md
  
   - 第37讲_技术创业该如何选择赛道.md
  
   - 第38讲_CTO要掌握的产品哲学_理性与人性的权衡.md
  
   - 第39讲_从客户价值谈技术创新.md
  
   - 第40讲_技术人投身创业公司之前，应当考虑些什么_.md
  
   - 大咖对话_技术人创业前衡量自我的3P3C模型.md
  
   - 第41讲_技术人创业前要问自己的六个问题.md
  
   - 第42讲_团队激励之分配好你的奖金.md
  
   - 第43讲_通过积分考核提升技术团队的绩效.md
  
   - 第44讲_空降技术高管的“择业七计”.md
  
   - 大咖对话_如何打造自我驱动型的技术团队_.md
  
   - 第45讲_选好人生下一站——CTO空降上篇.md
  
   - 第46讲_走出“至暗时刻”——CTO空降下篇.md
  
   - 第47讲_空降领导者平稳落地要做的四道题（上）.md
  
   - 第48讲_空降领导者平稳落地要做的四道题（下）.md
  
   - 大咖对话_管理者是首席铲屎官_.md
  
   - 第49讲_打造高效的研发组织架构_高效研发流程那些事（一）.md
  
   - 第50讲_你的研发流程符合你的组织架构吗_谈高效研发流程那些事（二）.md
  
   - 第51讲_聊聊研发流程管理中的那些坑_高效研发流程那些事（三）.md
  
   - 第52讲_数据如何驱动研发高效运转_谈高效研发流程那些事（四）.md
  
   - 大咖对话_对人才的长期投资是人才体系打造的根本.md
  
   - 第53讲_如何打造高效且敏捷的组织文化_谈高效研发流程那些亊（五）.md
  
   - 第54讲_打造高速运转的迭代机器_现代研发流程体系打造（一）.md
  
   - 第55讲_用机器打造迭代机器_现代研发流程体系打造（二）.md
  
   - 第56讲_有了敏捷开发，那交付期限去哪儿了_.md
  
   - 大咖对话_项目成功的秘诀——技术产品双头负责制.md
  
   - 第57讲_敏捷中的期限之殇，软件业该怎么做_.md
  
   - 第58讲_如何打造个人技术品牌_.md
  
   - 第59讲_技术演讲，有章可循.md
  
   - 第60讲_正确对待技术演讲中的失误.md
  
   - 大咖对话_不可替代的Java_生态与程序员是两道护城河.md
  
   - 第61讲_刘俊强_技术最高决策者应该关注技术细节吗_.md
  
   - 第62讲_张溪梦_技术领袖需要具备的商业价值思维.md
  
   - 第63讲_未来组织形态带来的领导力挑战.md
  
   - 第64讲_如何判断业务价值的高低.md
  
   - 大咖对话_池建强_做产品不要执着于打造爆款.md
  
   - 第65讲_如何打造高效的分布式团队_.md
  
   - 第66讲_如何打造有活力、持续创新的研发团队_.md
  
   - 第67讲_如何打造独属自己的工程师文化_.md
  
   - 第68讲_如何打造一个自组织团队_.md
  
   - 大咖对话_童剑_用合伙人管理结构打造完美团队.md
  
   - 第69讲_茹炳晟_QE团队向工程效能团队转型的实践之路.md
  
   - 第70讲_技术、产品、管理的不同视角.md
  
   - 第71讲_什么样的人适合考虑管理角色.md
  
   - 第72讲_创业公司如何招到合适的人才.md
  
   - 大咖对话_以产生价值判断工程师贡献——读者留言精选.md
  
   - 第73讲_用数据来分析管理员工.md
  
   - 第74讲_为什么给了高工资，依然留不住核心员工_.md
  
   - 第75讲_刘俊强_一本正经教你如何毁掉一场技术演讲.md
  
   - 第76讲_内部技术会议的价值.md
  
   - 大咖对话_韩军_CTO转型CEO如何转变思路.md
  
   - 第79讲_程军_从0到1打造高效技术团队的方法论.md
  
   - 第80讲_技术Leader的持续成长.md
  
   - 大咖对话_焦烈焱_从四个维度更好的激发团队创造力.md
  
   - 第81讲_游舒帆_一流团队必备的商业思维能力.md
  
   - 第82讲_游舒帆_数据力，透过数据掌握公司经营大小事.md
  
   - 第83讲_游舒帆_运营力，让用户出现你期待的行为.md
  
   - 大咖对话_谭待_架构的本质是折中.md
  
   - 第84讲_游舒帆_策略力，让目标与行动具备高度一致性.md
  
   - 第85讲_游舒帆_敏捷力，拥抱不确定性，与VUCA共舞.md
  
   - 第86讲_刘俊强_管理者必备的高效会议指南（上）.md
  
   - 第87讲_刘俊强_管理者必备的高效会议指南（下）.md
  
   - 大咖对话_陈斌_如何打造高创造力、高动力的技术团队.md
  
   - 第88讲_刘俊强_做好一对一沟通的关键要素（上）.md
  
   - 第89讲_刘俊强_做好一对一沟通的关键要素（下）.md
  
   - 第90讲_程军_打造高效技术团队之招人.md
  
   - 第91讲_程军_打造高效技术团队之做事.md
  
   - 大咖对话_万玉权_高效团队的关键，以目标为导向，用数据来说话.md
  
   - 第92讲_成敏_技术负责人如何做优先级决策.md
  
   - 第93讲_兰军_团队研发效率低下的要因分析.md
  
   - 第94讲_兰军_提升产品团队研发效率的实践（上）.md
  
   - 第95讲_兰军_提升产品团队研发效率的实践（下）.md
  
   - 大咖对话_万玉权_如何招到并培养核心人才.md
  
   - 第96讲_阿禅_工程师转型产品经理可能踩到的“坑”.md
  
   - 第97讲_阿禅_工程师转型产品经理的必备思维.md
  
   - 第98讲_徐裕键_业务高速增长过程中的团队迭代.md
  
   - 第99讲_徐裕键_业务高速增长过程中的技术演进.md
  
   - 大咖对话_杨育斌_技术领导者要打造技术团队的最大化价值.md
  
   - 第100讲_徐裕键_团队文化建设，保持创业公司的战斗力.md
  
   - 第101讲_刘俊强_领导力提升指南之培养积极的态度.md
  
   - 第102讲_姚从磊_巧用AARRR模型，吸引优秀技术人才（一）.md
  
   - 第103讲_姚从磊_巧用AARRR模型，吸引优秀技术人才（二）.md
  
   - 大咖对话_谢孟军_技术人如何建立自己的个人品牌.md
  
   - 第104讲_姚从磊_巧用AARRR模型，吸引优秀技术人才（三）.md
  
   - 第105讲_姚从磊_巧用AARRR模型，吸引优秀技术人才（四）.md
  
   - 第106讲_程军_技术人的「知行合一」（一）.md
  
   - 第107讲_刘俊强_消除压力的七种方法.md
  
   - 大咖对话_余沛_进阶CTO必备的素质与能力.md
  
   - 第108讲_谢呈_技术高手转身创业的坑和坡.md
  
   - 第109讲_谢呈_关于垂直互联网创业的一些经验之谈.md
  
   - 第110讲_成敏_创业公司为什么会技术文化产品缺失.md
  
   - 第111讲_蔡锐涛_从0到1再到100，创业不同阶段的技术管理思考.md
  
   - 大咖对话_余沛_打造以最佳交付实践为目标的技术导向.md
  
   - 第112讲_刘俊强_必知绩效管理知识之绩效管理循环.md
  
   - 第113讲_程军_技术人的「知行合一」（二）.md
  
   - 第114讲_成敏_谈谈不同阶段技术公司的特点.md
  
   - 第115讲_成敏_打造优秀团队与文化的三个推手.md
  
   - 大咖对话_季昕华_以不变的目的应对多变的技术浪潮.md
  
   - 第116讲_刘俊强_必知绩效管理知识之绩效目标的制定.md
  
   - 第117讲_程军_技术人的「知行合一」（三）.md
  
   - 第118讲_吴铭_成本评估是技术leader的关键素质.md
  
   - 第119讲_汤力嘉_CTO如何进行产品决策（一）.md
  
   - 大咖对话_胡哲人_技术人创业要跨过的思维坎.md
  
   - 第120讲_刘俊强_必知绩效管理知识之绩效数据收集（上）.md
  
   - 第121讲_刘俊强_必知绩效管理知识之绩效数据收集（下）.md
  
   - 第122讲_黄伟坚_创业中那些永远回避不了的问题.md
  
   - 第123讲_黄伟坚_用系统性思维看待创业.md
  
   - 大咖对话_袁店明_打造高效研发团队的五个要点.md
  
   - 第124讲_刘俊强_必知绩效管理知识之评定绩效.md
  
   - 第125讲_洪强宁_从程序员到架构师，从架构师到CTO（一）.md
  
   - 第126讲_洪强宁_从程序员到架构师，从架构师到CTO（二）.md
  
   - 第127讲_刘俊强_必知绩效管理知识之绩效沟通（一）.md
  
   - 大咖对话_袁店明_如何将打造自组织团队落诸实践.md
  
   - 第128讲_王坚_年轻人永远是创新的主体.md
  
   - 第129讲_刘俊强_必知绩效管理知识之绩效沟通（二）.md
  
   - 第130讲_刘俊强_必知绩效管理知识之绩效沟通（三）.md
  
   - 第131讲_汤力嘉_CTO如何在产品方面进行决策（二）.md
  
   - 大咖对话_王坚_我从不吃后悔药.md
  
   - 第132讲_徐函秋_转型技术管理者初期的三大挑战（一）.md
  
   - 第133讲_徐函秋_转型技术管理者初期的三大挑战（二）.md
  
   - 第134讲_刘建国_我各方面做得都很好，就是做不好向上沟通.md
  
   - 第135讲_钮博彦_软件研发度量体系建设（一）.md
  
   - 大咖对话_高斌_过分渲染会过度拉高大众对人工智能的期望.md
  
   - 第136讲_钮博彦_软件研发度量体系建设（二）.md
  
   - 第137讲_成敏_创业者不要成为自己公司产品技术文化的破坏者.md
  
   - 第138讲_于艺_以生存为核心，B端产品的定位心法.md
  
   - 第139讲_成敏_创业者应该具备的认知与思维方式.md
  
   - 大咖对话_张建锋_创业可以快而大，也可以小而美.md
  
   - 第140讲_袁店明_创业产品必须迈过的鸿沟.md
  
   - 第141讲_徐毅_五星级软件工程师的高效秘诀（一）.md
  
   - 第142讲_徐毅_五星级软件工程师的高效秘诀（二）.md
  
   - 第143讲_徐毅_技术Leader应该具备的能力或素质.md
  
   - 大咖对话_徐毅_打造高效研发团队的五个维度及相关实践.md
  
   - 第144讲_于艺_如何提升自己的能力与动力.md
  
   - 第145讲_李列为_技术人员的商业思维.md
  
   - 第146讲_刘天胜_打造高效团队，关键在于平衡人、事和时间（一）.md
  
   - 第147讲_刘天胜_打造高效团队，关键在于平衡人、事和时间（二）.md
  
   - 大咖对话_徐毅_如何提升员工的活力与动力_.md
  
   - 第148讲_肖德时_创业团队技术领导者必备的十个领导力技能（上）.md
  
   - 第149讲_肖德时_创业团队技术领导者必备的十个领导力技能（下）.md
  
   - 第150讲_暨家愉_技术人如何快乐的自我成长（上）.md
  
   - 第151讲_暨家愉_技术人如何快乐的自我成长（下）.md
  
   - 大咖对话_王龙_利用C端连接B端实现产业互联网是下半场的重中之重.md
  
   - 第152讲_施翔_如何打造7_24高效交付通道（上）.md
  
   - 第153讲_施翔_如何打造7_24高效交付通道（下）.md
  
   - 第154讲_谢东升_说说技术管理者从外企到民企的挑战.md
  
   - 第155讲_王可光_如何搭建初创团队之人才关.md
  
   - 大咖对话_王平_从人、事、价值观、文化等维度看技术团队转型.md
  
   - 第156讲_成敏_技术人转型管理的两大秘诀.md
  
   - 第157讲_成敏_技术人才的管理公式.md
  
   - 第158讲_胡峰_人到中年_失业与恐惧.md
  
   - 第159讲_黄云_技术管理者如何科学的做好向上管理.md
  
   - 大咖对话_王平_如何快速搭建核心技术团队.md
  
   - 第160讲_胡键_创业公司需要高凝聚力高绩效的技术团队.md
  
   - 第161讲_卢亿雷_企业发展的不同阶段，该如何打造高效的研发流程体系.md
  
   - 第162讲_王海亮_提升技术团队效率的5个提示（上）.md
  
   - 第163讲_王海亮_提升技术团队效率的5个提示（下）.md
  
   - 大咖对话_彭跃辉_保持高效迭代的团队是如何炼成的.md
  
   - 第164讲_陈崇磐_心理成熟度-创业公司识人利器.md
  
   - 第165讲_陈崇磐_管事与管人-如何避开创业公司组队陷阱.md
  
   - 第166讲_俞圆圆_合格CTO应该做好的5件事（上）.md
  
   - 第167讲_俞圆圆_合格CTO应该做好的5件事（下）.md
  
   - 大咖对话_彭跃辉_解决用户痛点就是立足于市场的秘诀.md
  
   - 新春特辑1_卓越CTO必备的能力与素质.md
  
   - 新春特辑2_如何成长为优秀的技术管理者_.md
  
   - 新春特辑3_如何打造高质效的技术团队_.md
  
   - 新春特辑4_如何打造高效的研发流程与文化_.md
  
   - 新春特辑5_如何做好人才的选育用留_.md
  
   - 第168讲_余加林_从技术人到创业合伙人必备的三个维度的改变.md
  
   - 第169讲_高琦_如何给研发打绩效不头疼而又公正_（上）.md
  
   - 第170讲_高琦_如何给研发打绩效不头疼而又公正_（下）.md
  
   - 第171讲_邱良军_如何有效地找到你心仪的人才.md
  
   - 大咖对话_王鹏云_管理方式的差异是为了更好地实现企业商业价值.md
  
   - 第172讲_于人_研发团队人均产能3年提升3.6倍的秘诀（上）.md
  
   - 第173讲_于人_研发团队人均产能3年提升3.6倍的秘诀（下）.md
  
   - 第174讲_邱良军_打造高效技术团队，你准备好了吗！.md
  
   - 第175讲_邱良军_打造高效技术团队的人才招聘攻略.md
  
   - 大咖对话_王鹏云_技术人创业该如何选择合伙人_.md
  
   - 第176讲_胡键_创业公司如何打造高凝聚力高绩效的技术团队_组织篇.md
  
   - 第177讲_胡键_创业公司如何打造高凝聚力高绩效的技术团队_工具篇.md
  
   - 第178讲_马连浩_用人的关键在于用人所长，而非改人之短.md
  
   - 第179讲_张矗_技术管理者必经的几个思维转变.md
  
   - 大咖对话_李昊_创业公司如何做好技术团队绩效考核_.md
  
   - 第180讲_钟忻_成为“温格”—聊聊如何当好CTO.md
  
   - 第181讲_姚威_技术团队管理中关于公平的五个核心准则.md
  
   - 第182讲_谢文杰_区块链的下一个十年.md
  
   - 第183讲_薛文植_技术管理的本质—要做尊重人性的管理.md
  
   - 大咖对话_陈天石_AI芯片需要技术和资本的双重密集支撑.md
  
   - 第184讲_狼叔_2019年前端和Node的未来—大前端篇（上）.md
  
   - 第185讲_狼叔_2019年前端和Node的未来—大前端篇（下）.md
  
   - 第186讲_赵晓光_如何培养团队竞争力（上）.md
  
   - 第187讲_赵晓光_如何培养团队竞争力（下）.md
  
   - 大咖对话_李智慧_技术人如何应对“互联网寒冬”.md
  
   - 第188讲_张嵩_从心理学角度看待小中型团队的管理.md
  
   - 第189讲_狼叔_2019年前端和Node的未来—Node.js篇（上）.md
  
   - 第190讲_狼叔_2019年前端和Node的未来—Node.js篇（下）.md
  
   - 第191讲_肖冰_如何建立高信任度的团队.md
  
   - 大咖对话_刘俊强_谈谈我对2019年云计算趋势的看法.md
  
   - 第192讲_崔俊涛_如何做好技术团队的激励（上）.md
  
   - 第193讲_崔俊涛_如何做好技术团队的激励（下）.md
  
   - 第194讲_刘俊强_2019年云计算趋势对技术人员的影响.md
  
   - 第195讲_吴晖_企业B2B服务打磨的秘诀—ESI.md
  
   - 大咖对话_刘俊强_云计算时代技术管理者的应对之道.md
  
   - 第196讲_邱良军_关于做好技术团队管理的几点思考.md
  
   - 第197讲_邱良军_做好研发管理的3个关键.md
  
   - 第198讲_徐林_通过快速反馈建立充满信任的技术团队.md
  
   - 第199讲_宝玉_怎样平衡软件质量与时间成本范围的关系_.md
  
   - 大咖对话_陶真_技术人要爱上问问题，而不是自己的解决方案.md
  
   - 第200讲_邱良军_沟通，沟通，还是沟通（上）.md
  
   - 第201讲_邱良军_沟通，沟通，还是沟通（下）.md
  
   - 第202讲_陈嘉佳_奈飞文化宣言（上）.md
  
   - 第203讲_陈嘉佳_奈飞文化宣言（下）.md
  
   - 大咖对话_玉攻_四个维度看小程序与App的区别.md
  
   - 第204讲_邱良军_从小处着眼，修炼文化价值观.md
  
   - 第205讲_邵浩_人工智能新技术如何快速发现及落地（上）.md
  
   - 第206讲_邵浩_人工智能新技术如何快速发现及落地（下）.md
  
   - 第207讲_许良_科创板来了，我该怎么办_.md
  
   - 第208讲_陈阳_科创板投资，未来哪些行业受益最大_.md
  
   - 大咖对话_顾旻曼_投资时我们更多地是在找优秀的团队.md
  
   - 结束篇_即使远隔千山万水，也要乘风与你同往.md
  
   - 温故而知新_一键直达，六大文章主题索引.md
  