site_name: 玩转Vue3全家桶

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_如何借助Vue3建构你的前端知识体系_.md
  
   - 01_宏观视角_从前端框架发展史聊聊为什么要学Vue3_.md
  
   - 02_上手_一个清单应用帮你入门Vue.js.md
  
   - 03_新特性_初探Vue3新特性.md
  
   - 04_升级_Vue2项目如何升级到Vue3_.md
  
   - 05_项目启动_搭建Vue3工程化项目第一步.md
  
   - 06_新的代码组织方式_CompositionAPI&scriptsetup到底好在哪里.md
  
   - 07_巧妙的响应式_深入理解Vue3的响应式机制.md
  
   - 08_组件化_如何像搭积木一样开发网页_.md
  
   - 09_动画_Vue中如何实现动画效果_.md
  
   - 10_数据流_如何使用Vuex设计你的数据流.md
  
   - 11_路由_新一代vue-router带来什么变化.md
  
   - 12_调试_提高开发效率必备的VueDevtools.md
  
   - 13_JSX_如何利用JSX应对更灵活的开发场景_.md
  
   - 14_TypeScript_Vue3中如何使用TypeScript_.md
  
   - 15_实战痛点1_复杂Vue项目的规范和基础库封装.md
  
   - 16_实战痛点2_项目开发中的权限系统.md
  
   - 17_实战痛点3_Vue3中如何集成第三方框架.md
  
   - 18_实战痛点4_Vue3项目中的性能优化.md
  
   - 加餐01｜什么是好的项目_.md
  
   - 19_实战痛点5_如何打包发布你的Vue3应用_.md
  
   - 加餐02｜深入TypeScript.md
  
   - 20｜组件库_如何设计你自己的通用组件库_.md
  
   - 21_单元测试_如何使用TDD开发一个组件_.md
  
   - 22｜表单_如何设计一个表单组件_.md
  
   - 23_弹窗_如何设计一个弹窗组件_.md
  
   - 24｜树_如何设计一个树形组件_.md
  
   - 25｜表格_如何设计一个表格组件_.md
  
   - 26｜文档_如何给你的组件库设计一个可交互式文档_.md
  
   - 27｜自定义渲染器_如何实现Vue的跨端渲染_.md
  
   - 28｜响应式_万能的面试题，怎么手写响应式系统.md
  
   - 29｜运行时_Vue在浏览器里是怎么跑起来的_.md
  
   - 30｜虚拟DOM（上）_如何通过虚拟DOM更新页面_.md
  
   - 31｜虚拟DOM（下）_想看懂虚拟DOM算法，先刷个算法题.md
  
   - 32｜编译原理（上）_手写一个迷你Vue3Compiler的入门原理.md
  
   - 33_编译原理（中）_VueCompiler模块全解析.md
  
   - 34_编译原理（下）_编译原理给我们带来了什么_.md
  
   - 35｜Vite原理_写一个迷你的Vite.md
  
   - 36｜数据流原理_Vuex&amp;amp;Pinia源码剖析.md
  
   - 37｜前端路由原理_vue-router源码剖析.md
  
   - 38｜服务端渲染原理_Vue3中的SSR是如何实现的_.md
  
   - 用户故事｜有了手感，才能真正把知识学透.md
  
   - 结束语｜Vue3生态源码到底给我们带来了什么_.md
  
   - 期末测试｜来赴一场满分之约！.md
  