site_name: 透视HTTP协议

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜ToBeaHTTPHero.md
  
   - 01_时势与英雄_HTTP的前世今生.md
  
   - 02_HTTP是什么_HTTP又不是什么_.md
  
   - 03_HTTP世界全览（上）_与HTTP相关的各种概念.md
  
   - 04_HTTP世界全览（下）_与HTTP相关的各种协议.md
  
   - 05_常说的“四层”和“七层”到底是什么_“五层”“六层”哪去了_.md
  
   - 06_域名里有哪些门道_.md
  
   - 07_自己动手，搭建HTTP实验环境.md
  
   - 08_键入网址再按下回车，后面究竟发生了什么_.md
  
   - 09_HTTP报文是什么样子的_.md
  
   - 10_应该如何理解请求方法_.md
  
   - 11_你能写出正确的网址吗_.md
  
   - 12_响应状态码该怎么用_.md
  
   - 13_HTTP有哪些特点_.md
  
   - 14_HTTP有哪些优点_又有哪些缺点_.md
  
   - 15_海纳百川_HTTP的实体数据.md
  
   - 16_把大象装进冰箱_HTTP传输大文件的方法.md
  
   - 17_排队也要讲效率_HTTP的连接管理.md
  
   - 18_四通八达_HTTP的重定向和跳转.md
  
   - 19_让我知道你是谁_HTTP的Cookie机制.md
  
   - 20_生鲜速递_HTTP的缓存控制.md
  
   - 21_良心中间商_HTTP的代理服务.md
  
   - 22_冷链周转_HTTP的缓存代理.md
  
   - 23_HTTPS是什么_SSL_TLS又是什么_.md
  
   - 24_固若金汤的根本（上）_对称加密与非对称加密.md
  
   - 25_固若金汤的根本（下）_数字签名与证书.md
  
   - 26_信任始于握手_TLS1.2连接过程解析.md
  
   - 27_更好更快的握手_TLS1.3特性解析.md
  
   - 28_连接太慢该怎么办_HTTPS的优化.md
  
   - 29_我应该迁移到HTTPS吗_.md
  
   - 30_时代之风（上）_HTTP_2特性概览.md
  
   - 31_时代之风（下）_HTTP_2内核剖析.md
  
   - 32_未来之路_HTTP_3展望.md
  
   - 33_我应该迁移到HTTP_2吗_.md
  
   - 34_Nginx_高性能的Web服务器.md
  
   - 35_OpenResty_更灵活的Web服务器.md
  
   - 36_WAF_保护我们的网络服务.md
  
   - 37_CDN_加速我们的网络服务.md
  
   - 38_WebSocket_沙盒里的TCP.md
  
   - 39_HTTP性能优化面面观（上）.md
  
   - 40_HTTP性能优化面面观（下）.md
  
   - 41_Linux_Mac实验环境搭建与URI查询参数.md
  
   - 42_DHE_ECDHE算法的原理.md
  
   - 43_如何进行Docker实验环境搭建_.md
  
   - 44_先睹为快_HTTP_3实验版本长什么样子_.md
  
   - 罗剑锋老师出新课了_.md
  
   - 结束语_做兴趣使然的Hero.md
  
   - 结课测试_这些HTTP协议知识，你真的掌握了吗_.md
  