site_name: 邱岳的产品手记

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_产品经理的世界没有对错.md
  
   - 01_验证码是个好设计吗_.md
  
   - 02_产品经理工具指南.md
  
   - 03_产品案例分析·Trigraphy的设计哲学.md
  
   - 04_如何当好AI时代的产品经理_（学习篇）.md
  
   - 05_如何当好AI时代的产品经理_（实践篇）.md
  
   - 06_产品案例分析·TheGuardian的文本之美.md
  
   - 07_关于需求变更（上）_需求背后的需求.md
  
   - 08_关于需求变更（下）:化变更于无形.md
  
   - 09_产品案例分析_Hopper的“人工智能”.md
  
   - 10_产品被抄袭了，怎么办_.md
  
   - 11_如何借鉴灵感_.md
  
   - 12_产品案例分析_LabRdr的设计实验.md
  
   - 13_无用却必要_产品规划（上）.md
  
   - 14_留白与节奏_产品规划（下）.md
  
   - 15_产品案例分析_Mimo与LearnPython的导学之趣.md
  
   - 16_在内部产品中找到产品经理的价值.md
  
   - 17_产品经理如何获得非权力性的影响力_.md
  
   - 18_产品案例分析_WWFTogether的情怀设计.md
  
   - 19_产品经理如何与开发打交道（上）_打破思维的边界.md
  
   - 20_产品经理如何与开发打交道（下）_合作与共赢.md
  
   - 21_产品案例分析_Fabulous的精致养成.md
  
   - 22_产品经理的图文基本功（上）_产品文档.md
  
   - 23_产品经理的图文基本功（下）_产品图例.md
  
   - 24_产品案例分析_PathSource的混乱与直观.md
  
   - 25_产品世界的暗黑模式_操纵的诱惑.md
  
   - 26_写好产品文档的诀窍.md
  
   - 27_产品案例分析_Quartz&amp;Hooked的对话式交互.md
  
   - 28_产品分析的套路（上）_谁是利益相关者_.md
  
   - 29_产品分析的套路（中）_解决什么问题_.md
  
   - 30_产品案例分析_Primer的扑克牌交互.md
  
   - 31_产品分析的套路（下）_如何出解决方案_.md
  
   - 32_从受众规模、需求频率和强度出发_排定需求优先级的方法（上）.md
  
   - 33_产品案例分析_Arts&amp;Culture的架构之美.md
  
   - 34_价值曲线分析_排定需求优先级的方法（下）.md
  
   - 35_答疑时间_关于产品经理的12个问题.md
  
   - 36_产品案例分析_解读知识星球.md
  
   - 37_如何做好需求评审（上）_需求评审不只是一次会议.md
  
   - 38_如何做好需求评审（下）_在评审中控住全场.md
  
   - 39_产品案例分析_SeatGeek的订票设计.md
  
   - 40_新年给产品经理的几碗鸡汤.md
  
   - 41_产品经理的项目管理心得.md
  
   - 42_产品案例分析_Unread的阅读体验.md
  
   - 43_“玩”的力量_从游戏设计中学习产品设计（上）.md
  
   - 44_“玩”的启示_从游戏设计中学习产品设计（下）.md
  
   - 45_产品案例分析_Chartistic的“复杂”图表.md
  
   - 尾声_你的快乐是哪一种.md
  
   - 【第二季回归】二爷归来，再次扬帆起航.md
  
   - 结课测试_关于产品的这些知识，你都掌握了吗_.md
  