site_name: 计算机基础实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜练好基本功，优秀工程师成长第一步.md
  
   - 01｜CISC&amp;RISC_从何而来，何至于此.md
  
   - 02｜RISC特性与发展_RISC-V凭什么成为“半导体行业的Linux”_.md
  
   - 先睹为快_迷你CPU项目效果演示.md
  
   - 03｜硬件语言筑基（一）_从硬件语言开启手写CPU之旅.md
  
   - 04｜硬件语言筑基（二）:代码是怎么生成具体电路的_.md
  
   - 05｜指令架构_RISC-V在CPU设计上到底有哪些优势_.md
  
   - 06｜手写CPU（一）_迷你CPU架构设计与取指令实现.md
  
   - 07｜手写CPU（二）_如何实现指令译码模块_.md
  
   - 08｜手写CPU（三）_如何实现指令执行模块_.md
  
   - 09｜手写CPU（四）_如何实现CPU流水线的访存阶段_.md
  
   - 10｜手写CPU（五）_CPU流水线的写回模块如何实现_.md
  
   - 11｜手写CPU（六）_如何让我们的CPU跑起来_.md
  
   - 用户故事｜我是怎样学习Verilog的_.md
  
   - 12｜QEMU_支持RISC-V的QEMU如何构建_.md
  
   - 13｜小试牛刀_跑通RISC-V平台的HelloWorld程序.md
  
   - 14｜走进C语言_高级语言怎样抽象执行逻辑_.md
  
   - 15｜C与汇编_揭秘C语言编译器的“搬砖”日常.md
  
   - 16｜RISC-V指令精讲（一）_算术指令实现与调试.md
  
   - 17｜RISC-V指令精讲（二）_算术指令实现与调试.md
  
   - 18｜RISC-V指令精讲（三）_跳转指令实现与调试.md
  
   - 19｜RISC-V指令精讲（四）_跳转指令实现与调试.md
  
   - 20｜RISC-V指令精讲（五）_原子指令实现与调试.md
  
   - 21｜RISC-V指令精讲（六）_加载指令实现与调试.md
  
   - 22｜RISC-V指令精讲（七）_访存指令实现与调试.md
  
   - 23｜内存地址空间_程序中地址的三种产生方式.md
  
   - 24｜虚实结合_虚拟内存和物理内存.md
  
   - 25｜堆&amp;amp;栈_堆与栈的区别和应用.md
  
   - 26｜延迟分配_提高内存利用率的三种机制.md
  
   - 27｜应用内存管理_Linux的应用与内存管理.md
  
   - 28｜进程调度_应用为什么能并行执行_.md
  
   - 29｜应用间通信（一）_详解Linux进程IPC.md
  
   - 30｜应用间通信（二）_详解Linux进程IPC.md
  
   - 国庆策划01｜知识挑战赛_检验一下学习成果吧！.md
  
   - 国庆策划02｜来自课代表的学习锦囊.md
  
   - 国庆策划03｜揭秘代码优化操作和栈保护机制.md
  
   - 31｜外设通信_IOCache与IO调度.md
  
   - 32｜IO管理_Linux如何管理多个外设_.md
  
   - 33｜lotop与lostat命令_聊聊命令背后的故事与工作原理.md
  
   - 34｜文件仓库_初识文件与文件系统.md
  
   - 35｜Linux文件系统（一）_Linux如何存放文件_.md
  
   - 36｜Linux文件系统（二）_Linux如何存放文件_.md
  
   - 37｜浏览器原理（一）_浏览器为什么要用多进程模型_.md
  
   - 38｜浏览器原理（二）_浏览器进程通信与网络渲染详解.md
  
   - 39｜源码解读_V8执行JS代码的全过程.md
  
   - 40｜内功心法（一）_内核和后端通用的设计思想有哪些_.md
  
   - 41｜内功心法（二）_内核和后端通用的设计思想有哪些_.md
  
   - 42｜性能调优_性能调优工具eBPF和调优方法.md
  
   - 结束语｜心若有所向往，何惧道阻且长.md
  
   - 期末测试｜来赴一场100分之约！.md
  
   - 温故知新｜思考题参考答案（一）.md
  
   - 温故知新｜思考题参考答案（二）.md
  
   - 加餐01｜云计算基础_自己动手搭建一款IAAS虚拟化平台.md
  
   - 加餐02_学习攻略（一）_大数据&amp;amp;云计算，究竟怎么学_.md
  
   - 加餐03｜学习攻略（二）_大数据&amp;amp;云计算，究竟怎么学_.md
  
   - 加餐04｜谈谈容器云与和CaaS平台.md
  
   - 加餐05｜分布式微服务与智能SaaS.md
  