site_name: SpringCloud微服务项目实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_跟着学，你也能成为微服务高手.md
  
   - 01_是什么推动了单体应用到微服务架构的演进_.md
  
   - 02_微服务全家桶_走进SpringCloud的世界.md
  
   - 03_初窥门径_我们要搭建一个怎样的微服务实战项目_.md
  
   - 04_十八般兵器_如何搭建项目所需的开发环境_.md
  
   - 05_牛刀小试_如何搭建优惠券模板服务_.md
  
   - 06_牛刀小试_如何搭建优惠券计算服务和用户服务_.md
  
   - 07_Nacos体系架构_什么是服务治理_.md
  
   - 08_服务治理_Nacos集群环境搭建.md
  
   - 09_集成Nacos_如何将服务提供者注册到Nacos服务器_.md
  
   - 10_集成Nacos_如何通过服务发现机制向服务提供者发起调用_.md
  
   - 11_Loadbalancer实战_通过自定义负载均衡策略实现金丝雀测试.md
  
   - 12_OpenFeign_服务间调用组件OpenFeign是怎么“隔空取物”的_.md
  
   - 13_OpenFeign实战_如何实现服务间调用功能_.md
  
   - 14_OpenFeign实战_OpenFeign组件有哪些高级玩法_.md
  
   - 15_配置中心在微服务中发挥着怎样的作用_.md
  
   - 16_如何集成NacosConfig实现配置项动态刷新_.md
  
   - 17_Sentinel体系结构_什么是服务容错（降级熔断、流量整形）_.md
  
   - 18_Sentinel实战_如何实施流量整形与限流策略_.md
  
   - 19_Sentinel实战_如何为项目添加异常降级方案_.md
  
   - 20_Sentinel实战_如何接入Nacos实现规则持久化_.md
  
   - 加餐_说透微服务_什么是主链路规划_.md
  
   - 21_Sleuth体系架构_为什么微服务架构需要链路追踪_.md
  
   - 22_调用链追踪_集成Sleuth和Zipkin，实现链路打标.md
  
   - 23_调用链追踪_如何通过ELK实现日志检索_.md
  
   - 24_为什么微服务架构少不了微服务网关_.md
  
   - 25_微服务网关_Gateway中的路由和谓词有何应用_.md
  
   - 26_微服务网关_如何设置请求转发、跨域和限流规则_.md
  
   - 27_微服务网关_如何借助Nacos实现动态路由规则_.md
  
   - 28_消息驱动_谁说消息队列只能削峰填谷_.md
  
   - 29_消息驱动_如何集成Stream实现消息驱动_.md
  
   - 30_消息驱动_如何高效处理Stream中的异常_.md
  
   - 31_消息驱动_如何通过RabbitMQ插件实现延迟消息_.md
  
   - 32_AlibabaSeata框架_什么是分布式事务_.md
  
   - 33_分布式事务_搭建Seata服务器.md
  
   - 34_分布式事务_使用Nacos&#43;Seata实现AT模式.md
  
   - 35_分布式事务_使用Nacos&#43;Seata实现TCC补偿模式.md
  
   - 结束语_站在聚光灯下.md
  