site_name: 容器实战高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_一个态度两个步骤，成为容器实战高手.md
  
   - 01_认识容器_容器的基本操作和实现原理.md
  
   - 02_理解进程（1）_为什么我在容器中不能kill1号进程_.md
  
   - 03｜理解进程（2）_为什么我的容器里有这么多僵尸进程_.md
  
   - 04_理解进程（3）_为什么我在容器中的进程被强制杀死了_.md
  
   - 05｜容器CPU（1）_怎么限制容器的CPU使用_.md
  
   - 06_容器CPU（2）_如何正确地拿到容器CPU的开销_.md
  
   - 07_LoadAverage_加了CPUCgroup限制，为什么我的容器还是很慢_.md
  
   - 08_容器内存_我的容器为什么被杀了_.md
  
   - 09_PageCache_为什么我的容器内存使用量总是在临界点_.md
  
   - 10_Swap_容器可以使用Swap空间吗_.md
  
   - 11_容器文件系统_我在容器中读写文件怎么变慢了_.md
  
   - 12_容器文件Quota_容器为什么把宿主机的磁盘写满了_.md
  
   - 13_容器磁盘限速_我的容器里磁盘读写为什么不稳定_.md
  
   - 14_容器中的内存与I_O_容器写文件的延时为什么波动很大_.md
  
   - 15_容器网络_我修改了_proc_sys_net下的参数，为什么在容器中不起效_.md
  
   - 16_容器网络配置（1）_容器网络不通了要怎么调试_.md
  
   - 17｜容器网络配置（2）_容器网络延时要比宿主机上的高吗_.md
  
   - 18_容器网络配置（3）_容器中的网络乱序包怎么这么高_.md
  
   - 19_容器安全（1）_我的容器真的需要privileged权限吗_.md
  
   - 20_容器安全（2）_在容器中，我不以root用户来运行程序可以吗_.md
  
   - 结束语_跳出舒适区，突破思考的惰性.md
  
   - 结课测试｜这些容器技术的问题，你都掌握了么_.md
  
   - 用户故事_莫名_相信坚持的力量，终会厚积薄发.md
  
   - 加餐福利_课后思考题答案合集.md
  
   - 加餐01_案例分析_怎么解决海量IPVS规则带来的网络延时抖动问题_.md
  
   - 加餐02_理解perf_怎么用perf聚焦热点函数_.md
  
   - 加餐03_理解ftrace（1）_怎么应用ftrace查看长延时内核函数_.md
  
   - 加餐04_理解ftrace（2）_怎么理解ftrace背后的技术tracepoint和kprobe_.md
  
   - 加餐05_eBPF_怎么更加深入地查看内核中的函数_.md
  
   - 加餐06_BCC_入门eBPF的前端工具.md
  