site_name: AI技术内参

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_你的360度人工智能信息助理.md
  
   - 001_聊聊2017年KDD大会的时间检验奖.md
  
   - 002_精读2017年KDD最佳研究论文.md
  
   - 003_精读2017年KDD最佳应用数据科学论文.md
  
   - 004_精读2017年EMNLP最佳长论文之一.md
  
   - 005_精读2017年EMNLP最佳长论文之二.md
  
   - 006_精读2017年EMNLP最佳短论文.md
  
   - 007_精读2017年ICCV最佳研究论文.md
  
   - 008_精读2017年ICCV最佳学生论文.md
  
   - 009_如何将“深度强化学习”应用到视觉问答系统_.md
  
   - 010_精读2017年NIPS最佳研究论文之一_如何解决非凸优化问题_.md
  
   - 011_精读2017年NIPS最佳研究论文之二_KSD测试如何检验两个分布的异同_.md
  
   - 012_精读2017年NIPS最佳研究论文之三_如何解决非完美信息博弈问题_.md
  
   - 013_WSDM2018论文精读_看谷歌团队如何做位置偏差估计.md
  
   - 014_WSDM2018论文精读_看京东团队如何挖掘商品的替代信息和互补信息.md
  
   - 015_WSDM2018论文精读_深度学习模型中如何使用上下文信息_.md
  
   - 016_TheWeb2018论文精读_如何对商品的图片美感进行建模_.md
  
   - 017_TheWeb2018论文精读_如何改进经典的推荐算法BPR_.md
  
   - 018_TheWeb2018论文精读_如何从文本中提取高元关系_.md
  
   - 019_SIGIR2018论文精读_偏差和“流行度”之间的关系.md
  
   - 020_SIGIR2018论文精读_如何利用对抗学习来增强排序模型的普适性_.md
  
   - 021_SIGIR2018论文精读_如何对搜索页面上的点击行为进行序列建模_.md
  
   - 022_CVPR2018论文精读_如何研究计算机视觉任务之间的关系_.md
  
   - 023_CVPR2018论文精读_如何从整体上对人体进行三维建模_.md
  
   - 024_CVPR2018论文精读_如何解决排序学习计算复杂度高这个问题_.md
  
   - 025_ICML2018论文精读_模型经得起对抗样本的攻击_这或许只是个错觉.md
  
   - 026_ICML2018论文精读_聊一聊机器学习算法的“公平性”问题.md
  
   - 027_ICML2018论文精读_优化目标函数的时候，有可能放大了“不公平”_.md
  
   - 028_ACL2018论文精读_问答系统场景下，如何提出好问题_.md
  
   - 029_ACL2018论文精读_什么是对话中的前提触发_如何检测_.md
  
   - 030_ACL2018论文精读_什么是“端到端”的语义哈希_.md
  
   - 复盘7_一起来读人工智能国际顶级会议论文.md
  
   - 031_经典搜索核心算法_TF-IDF及其变种.md
  
   - 032_经典搜索核心算法_BM25及其变种（内附全年目录）.md
  
   - 033_经典搜索核心算法_语言模型及其变种.md
  
   - 034_机器学习排序算法_单点法排序学习.md
  
   - 035_机器学习排序算法_配对法排序学习.md
  
   - 036_机器学习排序算法_列表法排序学习.md
  
   - 037_“查询关键字理解”三部曲之分类.md
  
   - 038_“查询关键字理解”三部曲之解析.md
  
   - 039_“查询关键字理解”三部曲之扩展.md
  
   - 040_搜索系统评测，有哪些基础指标_.md
  
   - 041_搜索系统评测，有哪些高级指标_.md
  
   - 042_如何评测搜索系统的在线表现_.md
  
   - 043_文档理解第一步_文档分类.md
  
   - 044_文档理解的关键步骤_文档聚类.md
  
   - 045_文档理解的重要特例_多模文档建模.md
  
   - 046_大型搜索框架宏观视角_发展、特点及趋势.md
  
   - 047_多轮打分系统概述.md
  
   - 048_搜索索引及其相关技术概述.md
  
   - 049_PageRank算法的核心思想是什么_.md
  
   - 050_经典图算法之HITS.md
  
   - 051_社区检测算法之“模块最大化”.md
  
   - 052_机器学习排序算法经典模型_RankSVM.md
  
   - 053_机器学习排序算法经典模型_GBDT.md
  
   - 054_机器学习排序算法经典模型_LambdaMART.md
  
   - 055_基于深度学习的搜索算法_深度结构化语义模型.md
  
   - 056_基于深度学习的搜索算法_卷积结构下的隐含语义模型.md
  
   - 057_基于深度学习的搜索算法_局部和分布表征下的搜索模型.md
  
   - 复盘1_搜索核心技术模块.md
  
   - 058_简单推荐模型之一_基于流行度的推荐模型.md
  
   - 059_简单推荐模型之二_基于相似信息的推荐模型.md
  
   - 060_简单推荐模型之三_基于内容信息的推荐模型.md
  
   - 061_基于隐变量的模型之一_矩阵分解.md
  
   - 062_基于隐变量的模型之二_基于回归的矩阵分解.md
  
   - 063_基于隐变量的模型之三_分解机.md
  
   - 064_高级推荐模型之一_张量分解模型.md
  
   - 065_高级推荐模型之二_协同矩阵分解.md
  
   - 066_高级推荐模型之三_优化复杂目标函数.md
  
   - 067_推荐的Exploit和Explore算法之一_EE算法综述.md
  
   - 068_推荐的Exploit和Explore算法之二_UCB算法.md
  
   - 069_推荐的Exploit和Explore算法之三_汤普森采样算法.md
  
   - 070_推荐系统评测之一_传统线下评测.md
  
   - 071_推荐系统评测之二_线上评测.md
  
   - 072_推荐系统评测之三_无偏差估计.md
  
   - 073_现代推荐架构剖析之一_基于线下离线计算的推荐架构.md
  
   - 074_现代推荐架构剖析之二_基于多层搜索架构的推荐系统.md
  
   - 075_现代推荐架构剖析之三_复杂现代推荐架构漫谈.md
  
   - 076_基于深度学习的推荐模型之一_受限波兹曼机.md
  
   - 077_基于深度学习的推荐模型之二_基于RNN的推荐系统.md
  
   - 078_基于深度学习的推荐模型之三_利用深度学习来扩展推荐系统.md
  
   - 复盘2_推荐系统核心技术模块.md
  
   - 079_广告系统概述.md
  
   - 080_广告系统架构.md
  
   - 081_广告回馈预估综述.md
  
   - 082_Google的点击率系统模型.md
  
   - 083_Facebook的广告点击率预估模型.md
  
   - 084_雅虎的广告点击率预估模型.md
  
   - 085_LinkedIn的广告点击率预估模型.md
  
   - 086_Twitter的广告点击率预估模型.md
  
   - 087_阿里巴巴的广告点击率预估模型.md
  
   - 088_什么是“基于第二价位的广告竞拍”_.md
  
   - 089_广告的竞价策略是怎样的_.md
  
   - 090_如何优化广告的竞价策略_.md
  
   - 091_如何控制广告预算_.md
  
   - 092_如何设置广告竞价的底价_.md
  
   - 093_聊一聊“程序化直接购买”和“广告期货”.md
  
   - 094_归因模型_如何来衡量广告的有效性.md
  
   - 095_广告投放如何选择受众_如何扩展受众群_.md
  
   - 096_如何利用机器学习技术来检测广告欺诈_.md
  
   - 复盘4_广告系统核心技术模块.md
  
   - 097_LDA模型的前世今生.md
  
   - 098_LDA变种模型知多少.md
  
   - 099_针对大规模数据，如何优化LDA算法_.md
  
   - 100_基础文本分析模型之一_隐语义分析.md
  
   - 101_基础文本分析模型之二_概率隐语义分析.md
  
   - 102_基础文本分析模型之三_EM算法.md
  
   - 103_为什么需要Word2Vec算法_.md
  
   - 104_Word2Vec算法有哪些扩展模型_.md
  
   - 105_Word2Vec算法有哪些应用_.md
  
   - 106_序列建模的深度学习利器_RNN基础架构.md
  
   - 107_基于门机制的RNN架构_LSTM与GRU.md
  
   - 108_RNN在自然语言处理中有哪些应用场景_.md
  
   - 109_对话系统之经典的对话模型.md
  
   - 110_任务型对话系统有哪些技术要点_.md
  
   - 111_聊天机器人有哪些核心技术要点_.md
  
   - 112_什么是文档情感分类_.md
  
   - 113_如何来提取情感“实体”和“方面”呢_.md
  
   - 114_文本情感分析中如何做意见总结和搜索_.md
  
   - 复盘3_自然语言处理及文本处理核心技术模块.md
  
   - 115_什么是计算机视觉_.md
  
   - 116_掌握计算机视觉任务的基础模型和操作.md
  
   - 117_计算机视觉中的特征提取难在哪里_.md
  
   - 118_基于深度学习的计算机视觉技术（一）_深度神经网络入门.md
  
   - 119_基于深度学习的计算机视觉技术（二）_基本的深度学习模型.md
  
   - 120_基于深度学习的计算机视觉技术（三）_深度学习模型的优化.md
  
   - 121_计算机视觉领域的深度学习模型（一）_AlexNet.md
  
   - 122_计算机视觉领域的深度学习模型（二）_VGG&amp;amp;GoogleNet.md
  
   - 123_计算机视觉领域的深度学习模型（三）_ResNet.md
  
   - 124_计算机视觉高级话题（一）_图像物体识别和分割.md
  
   - 125_计算机视觉高级话题（二）_视觉问答.md
  
   - 126_计算机视觉高级话题（三）_产生式模型.md
  
   - 复盘5_计算机视觉核心技术模块.md
  
   - 127_数据科学家基础能力之概率统计.md
  
   - 128_数据科学家基础能力之机器学习.md
  
   - 129_数据科学家基础能力之系统.md
  
   - 130_数据科学家高阶能力之分析产品.md
  
   - 131_数据科学家高阶能力之评估产品.md
  
   - 132_数据科学家高阶能力之如何系统提升产品性能.md
  
   - 133_职场话题_当数据科学家遇见产品团队.md
  
   - 134_职场话题_数据科学家应聘要具备哪些能力_.md
  
   - 135_职场话题_聊聊数据科学家的职场规划.md
  
   - 136_如何组建一个数据科学团队_.md
  
   - 137_数据科学团队养成_电话面试指南.md
  
   - 138_数据科学团队养成_Onsite面试面面观.md
  
   - 139_成为“香饽饽”的数据科学家，如何衡量他们的工作呢_.md
  
   - 140_人工智能领域知识体系更新周期只有5～6年，数据科学家如何培养_.md
  
   - 141_数据科学家团队组织架构_水平还是垂直，这是个问题.md
  
   - 142_数据科学家必备套路之一_搜索套路.md
  
   - 143_数据科学家必备套路之二_推荐套路.md
  
   - 144_数据科学家必备套路之三_广告套路.md
  
   - 145_如何做好人工智能项目的管理_.md
  
   - 146_数据科学团队必备的工程流程三部曲.md
  
   - 147_数据科学团队怎么选择产品和项目_.md
  
   - 148_曾经辉煌的雅虎研究院.md
  
   - 149_微软研究院_工业界研究机构的楷模.md
  
   - 150_聊一聊谷歌特立独行的混合型研究.md
  
   - 复盘6_数据科学家与数据科学团队是怎么养成的_.md
  
   - 151_精读AlphaGoZero论文.md
  
   - 152_2017人工智能技术发展盘点.md
  
   - 153_如何快速学习国际顶级学术会议的内容_.md
  
   - 154_在人工智能领域，如何快速找到学习的切入点_.md
  
   - 155_人工智能技术选择，该从哪里获得灵感_.md
  
   - 156_近在咫尺，走进人工智能研究.md
  
   - 内参特刊_和你聊聊每个人都关心的人工智能热点话题.md
  
   - 结束语_雄关漫道真如铁，而今迈步从头越.md
  