site_name: 技术领导力实战笔记2022

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜他山之石_带你直面技术管理者的真实困局.md
  
   - 01｜研发团队绩效考核_Leader如何做到赏罚分明_.md
  
   - 02｜如何打造一个“无需激励”自运转的技术团队_.md
  
   - 03｜技术型创业公司如何把握发展与管理的节奏感_.md
  
   - 04｜能力构建（上）_如何从做技术转变到做技术决策_.md
  
   - 05｜能力构建（下）_从管事到管人，需要迈过的坎.md
  
   - 06｜技术领导者如何“修炼”管理的艺术_.md
  
   - 07｜从员工批量离职中，认识管理的价值.md
  
   - 08｜技术分担产品之忧（上）_挑选有业务专家潜力的人.md
  
   - 09｜技术分担产品之忧（下）_产研如何融合_.md
  
   - 10｜技术管理者如何获得下属的认同_.md
  
   - 11｜用规则来搭建团队_写周报不一定是坏事.md
  
   - 12｜从任务分配角度来看管理.md
  
   - 13｜招兵买马_如何判断候选人与岗位的匹配程度_.md
  
   - 14｜团队优化_如何妥善且优雅地做好解聘工作_.md
  
   - 15｜空降负责人如何与团队建立信任_.md
  
   - Q&amp;amp;A｜关于技术管理，你有哪些话想说_.md
  
   - 16｜有战斗力的团队，是打造出来的，也是争取来的.md
  
   - 17｜技术升级落地需要天时、地利、人和.md
  
   - 18｜技术管理者如何发掘写代码之外的能力_.md
  
   - 19｜坚持技术or转做管理，我们该如何选择_.md
  
   - 20｜成为技术管理者之后，我们应该做出哪些转变_.md
  
   - 21｜高效管理，让工作事半功倍.md
  
   - 22｜提升影响力_信念、热情与行动缺一不可.md
  
   - 23｜大型研发架构团队的AOM实践.md
  
   - 24｜CaseStudy_让线上故障沉淀为团队的经验.md
  
   - 25｜用心做好“鼓励式”管理.md
  
   - 26｜从大厂到创业公司，管理上需要怎样转变_.md
  
   - 27｜管理者不是当权者，而是服务者.md
  
   - 28｜管理者既要安定内部，又要团结外部.md
  
   - 29｜巧用性格上的差异来组建团队.md
  
   - 30｜从技术专家到总经理，在不确定中探索和成长.md
  
   - 结束语｜知易行难，在管理的实践中检验真理.md
  