site_name: ReactNative新架构实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜为什么要选择ReactNative做你的跨端方案_.md
  
   - 加餐｜集中答疑_详解Android环境搭建.md
  
   - 加餐｜集中答疑_详解iOS环境搭建.md
  
   - 01｜学习ReactNative，你需要掌握哪些知识_.md
  
   - 02｜Component_搭建静态页面的正确思路是什么_.md
  
   - 03｜Style_关于样式你需要知道的三件事.md
  
   - 04｜State_如何让页面“动”起来_.md
  
   - 05｜Image_选择适合你的图片加载方式.md
  
   - 06｜Pressable_如何实现一个体验好的点按组件_.md
  
   - 07｜TextInput_如何实现一个体验好的输入框_.md
  
   - 08｜List_如何实现高性能的无限列表_.md
  
   - 09｜FastRefresh_提高UI调试效率神器.md
  
   - 10｜Debug_解决BUG思路有哪些_.md
  
   - 11｜组件实战_如何实现瀑布流_.md
  
   - 12｜页面实战_如何搭建一个电商首页_.md
  
   - 直播加餐｜七年，我的跨端实践和探索.md
  
   - 13｜生态_ReactNativeAwesome.md
  
   - 14｜Reanimated_如何让动画变得更流畅_.md
  
   - 15｜Gesture（上）_如何实现一个拖拽动效_.md
  
   - 16｜Gesture（中）_如何解决单视图多手势的冲突问题_.md
  
   - 17｜Gesture（下）_如何解决多视图多手势的冲突问题_.md
  
   - 18｜Navigation_页面之间怎么跳转_.md
  
   - 19｜Redux_大型应用应该如何管理状态_.md
  
   - 20｜Sentry_线上错误与性能监控怎么处理_.md
  
   - 21｜混合应用_如何从零开始集成ReactNative_.md
  
   - 22｜自定义组件_如何满足业务的个性化需求_.md
  
   - 23｜热更新_如何搭建一个热更新平台_.md
  
   - 24｜拆包_Metro拆包的工作原理是什么_.md
  
   - 25｜性能优化_如何设计一个合适的性能优化方案_.md
  
   - 26｜客户端优化_如何把性能提升到极致_.md
  
   - 阶段测试｜ReactNative的这些核心知识，你都掌握了吗_.md
  
   - 总结与展望｜新架构探索之旅，马上开始.md
  
   - 27｜跨端的机遇_小程序、Flutter和ReactNative原理对比.md
  
   - 28｜追本溯源_从第一版ReactNative开始学会读懂源码.md
  
   - 29｜弄清现状_新架构预览版究竟长什么样_.md
  
   - 30｜JavaScript引擎_双向通讯底层原理是什么_.md
  
   - 31｜多线程_RN底层是如何保障交互体验的_.md
  
   - 32｜Fabric_新渲染器的演进之路.md
  
   - 33｜AI前沿_ChatGPT资料精选集.md
  
   - 34｜升级收益_这两年ReactNative都做了哪些升级_.md
  
   - 35｜自动化_升级0.72新架构的步骤和关键.md
  
   - 36｜升新不升旧_自定义组件如何升级到新架构_.md
  