site_name: 技术与商业案例解读

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_突破技术思维，站在商业的角度看问题.md
  
   - 001_西雅图IT公司之RealNetworks_一个帝国的兴衰（上）.md
  
   - 002_西雅图IT公司之RealNetworks_一个帝国的兴衰（下）.md
  
   - 003_以RealNetworks为例，谈谈初创公司如何应对巨头碾压.md
  
   - 004_可视化分析鼻祖Tableau.md
  
   - 005_从Tableau上市，看学术界和工业界人士创业.md
  
   - 006_在线旅游帝国Expedia崛起的背后.md
  
   - 007_房产经纪的颠覆者Redfin_在“传统”与“现代”间徘徊.md
  
   - 008_房产经纪的“协作者”Zillow_一个地产数据平台.md
  
   - 009_颠覆还是协作，房地产市场上Redfin和Zillow的抉择.md
  
   - 010_应用交付网络大厂F5_“一招鲜”之殇.md
  
   - 011_在线差旅报销鼻祖Concur_在转型中获得发展.md
  
   - 012_漫谈企业转型_在市场变迁中寻找生机.md
  
   - 013_克雷公司沉浮录_行走在超级计算机市场.md
  
   - 014_“单一化”的隐忧_从克雷公司看“一条腿走路”.md
  
   - 015_Halo的开发者Bungie_与微软的聚散.md
  
   - 016_“卖身”须谨慎_创业公司面临的抉择.md
  
   - 017_亚马逊领导力准则之要有硬骨头.md
  
   - 018_亚马逊领导力准则之决策正确.md
  
   - 019_亚马逊领导力准则之客户至尚.md
  
   - 020_亚马逊领导力准则之勤俭节约.md
  
   - 021_亚马逊领导力准则之主人翁精神.md
  
   - 022_亚马逊领导力准则之选贤育能.md
  
   - 023_亚马逊领导力准则之最高标准.md
  
   - 024_亚马逊领导力准则之创新简化.md
  
   - 025_亚马逊领导力准则之崇尚行动.md
  
   - 026_亚马逊领导力准则之远见卓识.md
  
   - 027_亚马逊领导力准则之好奇求知与赢得信任.md
  
   - 028_亚马逊领导力准则之刨根问底与达成业绩.md
  
   - 029_智能音箱的战斗_亚马逊的硬件路.md
  
   - 030_智能音箱的战斗_Echo攻城略地.md
  
   - 031_智能音箱的战斗_语音助手Alexa.md
  
   - 032_智能音箱的战斗_谷歌的杀入.md
  
   - 033_智能音箱的战斗_亚马逊的战略布局.md
  
   - 034_智能音箱的战斗_巨头纷纷入场.md
  
   - 035_智能音箱的战斗_白马非马.md
  
   - 036_如何透过一个领域去联合分析多家企业_.md
  
   - 037_管中窥豹之从面试看企业文化_微软.md
  
   - 038_管中窥豹之从面试看企业文化_亚马逊.md
  
   - 039_管中窥豹之从面试看企业文化_谷歌.md
  
   - 040_管中窥豹之从面试看企业文化_甲骨文.md
  
   - 041_管中窥豹之从面试看企业文化_Facebook.md
  
   - 042_透过企业用人之道看企业发展.md
  
   - 043_办公软件的战斗_开篇.md
  
   - 044_VisiCalc_第一个电子表格软件的诞生.md
  
   - 045_WordStar_第一个字处理软件的故事.md
  
   - 046_微软_办公软件战场的螳螂.md
  
   - 047_WordPerfect_字处理软件的新秀.md
  
   - 048_Lotus1-2-3_莲花公司的电子表格帝国.md
  
   - 049_红狮会战_微软的反击.md
  
   - 050_大杀器LotusNotes和被收购的莲花公司.md
  
   - 051_无敌寂寞的微软之为创新而创新.md
  
   - 052_办公软件的新时代_微软和谷歌的战斗.md
  
   - 053_异军突起的Slack.md
  
   - 054_办公软件战斗的启示_内忧总是强于外患.md
  
   - 055_办公软件战斗的启示_敌人的出现常常出其不意.md
  
   - 056_半条命的Dota帝国Valve_半条命.md
  
   - 057_半条命的Dota帝国Valve_Steam平台.md
  
   - 058_半条命的Dota帝国Valve_Dota2.md
  
   - 059_半条命的Dota帝国Valve_无领导管理.md
  
   - 060_半条命的Dota帝国Valve_虚拟现实.md
  
   - 061_GabeNewell_Valve帝国制度的利弊.md
  
   - 062_文档数据库的缔造者MongoDB（上）.md
  
   - 063_文档数据库的缔造者MongoDB（下）.md
  
   - 064_以MongoDB为例，看基础架构类产品创业.md
  
   - 065_直面MongoDB，谈微软的NoSQL战略.md
  
   - 066_Hadoop三国之魏国Cloudera.md
  
   - 067_Hadoop三国之吴国MapR.md
  
   - 068_Hadoop三国之蜀国Hortonworks.md
  
   - 069_Hadoop及其发行商的未来.md
  
   - 070_谷歌的大数据路_从“三驾马车”到一无所有.md
  
   - 071_谷歌的大数据路_一场影响深远的论战.md
  
   - 072_谷歌的大数据路_谷歌的“黑科技”.md
  
   - 073_如何读懂类似谷歌“三驾马车”这样的技术论文_.md
  
   - 074_雅虎_大数据领域的“活雷锋”.md
  
   - 075_IBM的大数据路之起早贪黑赶了晚集.md
  
   - 076_社交公司们的大数据贡献.md
  
   - 077_微软的大数据发展史_微软硅谷研究院.md
  
   - 078_微软的大数据发展史_必应的Cosmos.md
  
   - 079_微软的大数据发展史_Azure的大数据发展.md
  
   - 080_亚马逊的大数据故事_从先驱者到插管吸血开源.md
  
   - 081_亚马逊的大数据故事_创新和拿来并存的云服务.md
  
   - 082_阿里巴巴的大数据故事_数据分析平台发展史.md
  
   - 083_阿里巴巴的大数据故事_流计算引擎发展史.md
  
   - 084_大公司的大数据战略得失_自建轮子成本高.md
  
   - 085_大公司的大数据战略得失_抱团取暖难敌插管吸血者.md
  
   - 086_Palantir_神秘的大数据独角兽.md
  
   - 087_Splunk_机器大数据的分析帝国.md
  
   - 088_Confluent_在Kafka上飞驰的数据交换者.md
  
   - 089_Powerset_HBase的老东家.md
  
   - 090_Cassandra和DataStax的故事.md
  
   - 091_Databricks之Spark的数据金砖王国.md
  
   - 092_DataArtisans_浴火重生的新一代大数据计算引擎Flink.md
  
   - 093_Dremio:在Drill和Arrow上的大数据公司.md
  
   - 094_Imply_基于Druid的大数据分析公司.md
  
   - 095_Kyligence_阿帕奇麒麟背后的大数据公司.md
  
   - 096_Snowflake:云端的弹性数据仓库.md
  
   - 097_TiDB_一个国产新数据库的创业故事.md
  
   - 098_大数据创业公司的前景_红海创业多艰辛.md
  
   - 099_如何通过企业技术积累去分析一家企业_.md
  
   - 100_仁科_被迫再创业的DavidDuffield.md
  
   - 101_仁科_飞跃发展的企业级软件帝国.md
  
   - 102_仁科_收购和被收购.md
  
   - 103_仁科的成与败.md
  
   - 104_WorkDay_杜菲尔德复仇记.md
  
   - 105_DavidDuffield的眼界和成败.md
  
   - 106_分析企业的两要素_远见和执行力.md
  
   - 107_Zenefits_一个卖保险的创业公司.md
  
   - 108_Glassdoor_让公司信息对个人透明.md
  
   - 109_从巴顿的创业史看巴顿.md
  
   - 110_免费还是收费_WinRAR的生意经.md
  
   - 111_周鸿祎和BAT的沉浮录（上）.md
  
   - 112_周鸿祎和BAT的沉浮录（中）.md
  
   - 113_周鸿祎和BAT的沉浮录（下）.md
  
   - 114_周鸿祎和BAT的沉浮录（后记）.md
  
   - 115_互联网第一股雅虎的兴衰_霸主的诞生.md
  
   - 116_互联网第一股雅虎的兴衰_运气不敌技术.md
  
   - 117_互联网第一股雅虎的兴衰_没有救世主.md
  
   - 118_成也杨致远，败也杨致远.md
  
   - 119_企业因人成事，领导人很重要.md
  
   - 120_彼得·蒂尔的投资人生.md
  
   - 121_商业之外的彼得·蒂尔.md
  
   - 122_创业的智慧_从彼得·蒂尔的创投哲学说起.md
  
   - 123_谷歌的创新精神_好的、坏的和丑陋的（上）.md
  
   - 124_谷歌的创新精神_好的、坏的和丑陋的（下）.md
  
   - 125_Facebook的黑客精神.md
  
   - 126_Twitter_蓝色小鸟还能飞多久（上）.md
  
   - 127_Twitter_蓝色小鸟还能飞多久（下）.md
  
   - 128_赚钱是根本，换CEO也没救.md
  
   - 129_Square_手机POS机和比特币交易.md
  
   - 130_创意很重要，但不是一切.md
  
   - 131_杰克·多西_分身有术之兼任两家上市公司CEO.md
  
   - 132_Groupon_团购鼻祖的兴衰.md
  
   - 133_卖掉自己是不是更好.md
  
   - 134_企业在线存储Box.md
  
   - 135_个人在线存储Dropbox.md
  
   - 136_做产品先做消费者市场，还是先做企业市场.md
  
   - 137_今天我们都来Pin图片之Pinterest的图片社交路.md
  
   - 138_企业不上市为哪般.md
  
   - 139_微软的综合工程师改革.md
  
   - 140_SaaS先驱Salesforce.md
  
   - 141_太超前好不好.md
  
   - 142_Sun_太阳的升起.md
  
   - 143_Sun_太阳的陨落.md
  
   - 144_看错敌人多可怕.md
  
   - 145_SAP的HANA战略（上）.md
  
   - 146_SAP的HANA战略（下）.md
  
   - 147_成功的忽悠&#43;成功的执行=成功的产品.md
  
   - 148_SQLServer发展史.md
  
   - 149_眼光决定一切.md
  
   - 150_Ashton-Tate_桌面数据库王者的兴衰.md
  
   - 151_无敌不可以肆意妄为.md
  
   - 152_Reddit_天涯论坛美国版.md
  
   - 153_HackerNews_创业社交两不误.md
  
   - 154_YCombinator_孵化器还是培训班_.md
  
   - 155_创业公司进孵化器真的值得吗_.md
  
   - 156_PaulGraham_硅谷创业教父.md
  
   - 157_Zynga_发家从农场开始.md
  
   - 158_论Zynga的倒台.md
  
   - 159_企业分析要求综合素质.md
  
   - 结束语_积跬步，而终至千里.md
  
   - 一键直达_系列解读文章回顾.md
  
   - 新书首发丨《大数据浪潮之巅》.md
  
   - 结课测试_这些技术与商业的知识你都掌握了吗_.md
  