site_name: MySQL运维实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜理论&#43;实践，带你解决90%以上的MySQL运维问题.md
  
   - 01｜快速上手数据库安装部署.md
  
   - 02｜MySQL账号和权限管理.md
  
   - 03｜数据库连接问题诊断分析.md
  
   - 04｜MySQL中不同类型的参数与参数配置.md
  
   - 05｜你用对数据类型了吗_.md
  
   - 06｜SQLMode对程序有怎样的影响_.md
  
   - 07｜乱码是怎么产生的，以及如何避免_.md
  
   - 08｜程序访问数据库内存溢出怎么解决_.md
  
   - 09｜MySQL如何快速导入导出数据_（上）.md
  
   - 10｜MySQL如何快速导入导出数据_（下）.md
  
   - 11｜表太大了，修改表结构太慢怎么解决_（上）.md
  
   - 12｜表太大了，修改表结构太慢怎么解决_（下）.md
  
   - 13｜定位MySQL问题的思路_数据库为什么慢了_.md
  
   - 14｜Linux问题诊断入门_操作系统是否存在瓶颈_.md
  
   - 15｜非典型数据库故障解析_数据库故障一定是数据库的锅吗_.md
  
   - 16｜如何在不影响业务的情况下平滑升级MySQL_.md
  
   - 17｜SQL优化第一步_理解访问路径.md
  
   - 18｜读懂MySQL中的执行计划（上）.md
  
   - 18｜读懂MySQL中的执行计划（下）.md
  
   - 19｜优化器成本模型_优化器为什么选择这个执行计划_.md
  
   - 20｜单表查询_如何评估单表访问成本_.md
  
   - 21｜表连接如何执行_.md
  
   - 22｜MySQL子查询优化策略.md
  
   - 23｜10&#43;SQL执行性能不佳的真实案例（上）.md
  
   - 24｜10&#43;SQL执行性能不佳的真实案例（下）.md
  
   - 25｜数据库无法启动，如何读取InnoDB文件中的数据_（上）.md
  
   - 26｜数据库无法启动，如何读取InnoDB文件中的数据_（下）.md
  
   - 27｜InnoDBBufferPool如何提高数据库性能_(上）.md
  
   - 28｜InnoDBBufferPool如何提高数据库性能_(下）.md
  
   - 29｜数据都在内存里修改，服务器或数据库宕机会丢数据吗_.md
  
   - 30｜事务怎么回滚_（上）.md
  
   - 31｜事务怎么回滚_（下）.md
  
   - 32｜隔离级别对应用程序有什么影响_.md
  
   - 33｜InnoDB锁定和死锁问题_为什么我的SQL锁超时了_.md
  
   - 34｜MySQL数据库高可用架构部署和维护.md
  
   - 35｜MySQL半同步能提高主备数据的一致性吗_.md
  
   - 36｜备库有延迟怎么办_.md
  
   - 37｜备库服务器异常重启，备库损坏了该如何修复_.md
  
   - 38｜为什么有了备库还要做备份_兼谈Xtrabackup的使用.md
  
   - 39｜数据误操作了如何快速恢复_.md
  
   - 40｜MySQL8.0Clone插件的应用和内部原理.md
  
   - 41｜MySQL8.0组复制技术的应用（上）.md
  
   - 42｜MySQL8.0组复制技术的应用（下）.md
  
   - 43｜ProxySQL_数据库高可用了，应用高可用怎么做_.md
  
   - 44｜如何搭建一个MySQL监控平台_.md
  
   - 45｜MySQL源码分析和GDB调试器的应用.md
  
   - 结束语｜如何系统地掌握一门数据库技术_.md
  
   - 结课测试｜来赴一场满分之约吧.md
  
   - 基础篇｜课后题答疑.md
  
   - SQL优化篇｜课后题答疑.md
  
   - InnoDB存储引擎篇｜课后题答疑.md
  
   - 高可用篇｜课后题答疑.md
  