site_name: Java业务开发常见错误100例

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_业务代码真的会有这么多坑_.md
  
   - 01_使用了并发工具类库，线程安全就高枕无忧了吗_.md
  
   - 02_代码加锁_不要让“锁”事成为烦心事.md
  
   - 03_线程池_业务代码最常用也最容易犯错的组件.md
  
   - 04_连接池_别让连接池帮了倒忙.md
  
   - 05_HTTP调用_你考虑到超时、重试、并发了吗_.md
  
   - 06_20%的业务代码的Spring声明式事务，可能都没处理正确.md
  
   - 答疑篇_代码篇思考题集锦（一）.md
  
   - 07_数据库索引_索引并不是万能药.md
  
   - 08_判等问题_程序里如何确定你就是你_.md
  
   - 09_数值计算_注意精度、舍入和溢出问题.md
  
   - 10_集合类_坑满地的List列表操作.md
  
   - 11_空值处理_分不清楚的null和恼人的空指针.md
  
   - 12_异常处理_别让自己在出问题的时候变为瞎子.md
  
   - 答疑篇_代码篇思考题集锦（二）.md
  
   - 13_日志_日志记录真没你想象的那么简单.md
  
   - 14_文件IO_实现高效正确的文件读写并非易事.md
  
   - 15_序列化_一来一回你还是原来的你吗_.md
  
   - 16_用好Java8的日期时间类，少踩一些“老三样”的坑.md
  
   - 17_别以为“自动挡”就不可能出现OOM.md
  
   - 18_当反射、注解和泛型遇到OOP时，会有哪些坑_.md
  
   - 19_Spring框架_IoC和AOP是扩展的核心.md
  
   - 20_Spring框架_框架帮我们做了很多工作也带来了复杂度.md
  
   - 答疑篇_代码篇思考题集锦（三）.md
  
   - 21_代码重复_搞定代码重复的三个绝招.md
  
   - 22_接口设计_系统间对话的语言，一定要统一.md
  
   - 23_缓存设计_缓存可以锦上添花也可以落井下石.md
  
   - 24_业务代码写完，就意味着生产就绪了_.md
  
   - 25_异步处理好用，但非常容易用错.md
  
   - 26_数据存储_NoSQL与RDBMS如何取长补短、相辅相成_.md
  
   - 答疑篇_设计篇思考题答案合集.md
  
   - 27_数据源头_任何客户端的东西都不可信任.md
  
   - 28_安全兜底_涉及钱时，必须考虑防刷、限量和防重.md
  
   - 29_数据和代码_数据就是数据，代码就是代码.md
  
   - 30_如何正确保存和传输敏感数据_.md
  
   - 答疑篇_安全篇思考题答案合集.md
  
   - 31_加餐1_带你吃透课程中Java8的那些重要知识点（一）.md
  
   - 32_加餐2_带你吃透课程中Java8的那些重要知识点（二）.md
  
   - 33_加餐3_定位应用问题，排错套路很重要.md
  
   - 34_加餐4_分析定位Java问题，一定要用好这些工具（一）.md
  
   - 35_加餐5_分析定位Java问题，一定要用好这些工具（二）.md
  
   - 36_加餐6_这15年来，我是如何在工作中学习技术和英语的_.md
  
   - 答疑篇_加餐篇思考题答案合集.md
  
   - 37_加餐7_程序员成长28计.md
  
   - 38_加餐8_Java程序从虚拟机迁移到Kubernetes的一些坑.md
  
   - 结束语_写代码时，如何才能尽量避免踩坑_.md
  
   - 结课测试_关于Java业务开发的100个常见错误，你都明白其中缘由了吗_.md
  
   - 结课问卷获奖用户名单.md
  