site_name: Python核心技术与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_从工程的角度深入理解Python.md
  
   - 01_如何逐步突破，成为Python高手_.md
  
   - 02_JupyterNotebook为什么是现代Python的必学技术_.md
  
   - 03_列表和元组，到底用哪一个_.md
  
   - 04_字典、集合，你真的了解吗_.md
  
   - 05_深入浅出字符串.md
  
   - 06_Python“黑箱”_输入与输出.md
  
   - 07_修炼基本功_条件与循环.md
  
   - 08_异常处理_如何提高程序的稳定性_.md
  
   - 09_不可或缺的自定义函数.md
  
   - 10_简约不简单的匿名函数.md
  
   - 11_面向对象（上）_从生活中的类比说起.md
  
   - 12_面向对象（下）_如何实现一个搜索引擎_.md
  
   - 13_搭建积木_Python模块化.md
  
   - 14_答疑（一）_列表和元组的内部实现是怎样的_.md
  
   - 15_Python对象的比较、拷贝.md
  
   - 16_值传递，引用传递or其他，Python里参数是如何传递的_.md
  
   - 17_强大的装饰器.md
  
   - 18_metaclass，是潘多拉魔盒还是阿拉丁神灯_.md
  
   - 19_深入理解迭代器和生成器.md
  
   - 20_揭秘Python协程.md
  
   - 21_Python并发编程之Futures.md
  
   - 22_并发编程之Asyncio.md
  
   - 23_你真的懂PythonGIL（全局解释器锁）吗_.md
  
   - 24_带你解析Python垃圾回收机制.md
  
   - 25_答疑（二）_GIL与多线程是什么关系呢_.md
  
   - 26_活都来不及干了，还有空注意代码风格_！.md
  
   - 27_学会合理分解代码，提高代码可读性.md
  
   - 28_如何合理利用assert_.md
  
   - 29_巧用上下文管理器和With语句精简代码.md
  
   - 30_真的有必要写单元测试吗_.md
  
   - 31_pdb&amp;amp;cProfile_调试和性能分析的法宝.md
  
   - 32_答疑（三）_如何选择合适的异常处理方式_.md
  
   - 33_带你初探量化世界.md
  
   - 34_RESTful&amp;amp;Socket_搭建交易执行层核心.md
  
   - 35_RESTful&amp;amp;Socket_行情数据对接和抓取.md
  
   - 36_Pandas&amp;amp;Numpy_策略与回测系统.md
  
   - 37_Kafka&amp;amp;ZMQ_自动化交易流水线.md
  
   - 38_MySQL_日志和数据存储系统.md
  
   - 39_Django_搭建监控平台.md
  
   - 40_总结_Python中的数据结构与算法全景.md
  
   - 41_硅谷一线互联网公司的工作体验.md
  
   - 42_细数技术研发的注意事项.md
  
   - 加餐_带你上手SWIG_一份清晰好用的SWIG编程实践指南.md
  
   - 43_Q&amp;amp;A_聊一聊职业发展和选择.md
  
   - 结束语_技术之外的几点成长建议.md
  
   - 结课测试_关于Python的这些知识，你都掌握了吗_.md
  