site_name: 操作系统实战45讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_为什么要学写一个操作系统_.md
  
   - 03_黑盒之中有什么_内核结构与设计.md
  
   - 04_震撼的Linux全景图_业界成熟的内核架构长什么样_.md
  
   - 08_锁_并发操作中，解决数据同步的四种方法.md
  
   - 09_瞧一瞧Linux_Linux的自旋锁和信号量如何实现_.md
  
   - 10_设置工作模式与环境（上）_建立计算机.md
  
   - 11_设置工作模式与环境（中）_建造二级引导器.md
  
   - 12_设置工作模式与环境（下）_探查和收集信息.md
  
   - 13_第一个C函数_如何实现板级初始化_.md
  
   - 14_Linux初始化（上）_GRUB与vmlinuz的结构.md
  
   - 15_Linux初始化（下）_从_start到第一个进程.md
  
   - 24_活动的描述_到底什么是进程_.md
  
   - 25_多个活动要安排（上）_多进程如何调度_.md
  
   - 26_多个活动要安排（下）_如何实现进程的等待与唤醒机制_.md
  
   - 27_瞧一瞧Linux_Linux如何实现进程与进程调度_.md
  
   - 28_部门分类_如何表示设备类型与设备驱动_.md
  
   - 29_部门建立_如何在内核中注册设备_.md
  
   - 30_部门响应_设备如何处理内核I_O包_.md
  
   - 31_瞧一瞧Linux_如何获取所有设备信息_.md
  
   - 32_仓库结构_如何组织文件_.md
  
   - 33_仓库划分_文件系统的格式化操作.md
  
   - 34_仓库管理_如何实现文件的六大基本操作_.md
  
   - 35_瞧一瞧Linux_虚拟文件系统如何管理文件_.md
  
   - 36_从URL到网卡_如何全局观察网络数据流动_.md
  
   - 37_从内核到应用_网络数据在内核中如何流转.md
  
   - 38_从单排到团战_详解操作系统的宏观网络架构.md
  
   - 41_服务接口_如何搭建沟通桥梁_.md
  
   - 42_瞧一瞧Linux_如何实现系统API_.md
  
   - 43_虚拟机内核_KVM是什么_.md
  
   - 44_容器_如何理解容器的实现机制_.md
  
   - 45_ARM新宠_苹果的M1芯片因何而快_.md
  
   - 46_AArch64体系_ARM最新编程架构模型剖析.md
  
   - 结束语_生活可以一地鸡毛，但操作系统却是心中的光.md
  
   - 结课测试｜这些操作系统的问题，你都掌握了么_.md
  
   - 大咖助场｜以无法为有法，以无限为有限.md
  
   - LMOS来信_第二季课程带你“手撕”计算机基础.md
  
   - 编辑手记_升级认知，迭代自己的操作系统.md
  
   - 01_程序的运行过程_从代码到机器运行.md
  
   - 02_几行汇编几行C_实现一个最简单的内核.md
  
   - 05_CPU工作模式_执行程序的三种模式.md
  
   - 06_虚幻与真实_程序中的地址如何转换_.md
  
   - 07_Cache与内存_程序放在哪儿_.md
  
   - 16_划分土地（上）_如何划分与组织内存_.md
  
   - 17_划分土地（中）_如何实现内存页面初始化_.md
  
   - 18_划分土地（下）_如何实现内存页的分配与释放_.md
  
   - 19_土地不能浪费_如何管理内存对象_.md
  
   - 20_土地需求扩大与保障_如何表示虚拟内存_.md
  
   - 21_土地需求扩大与保障_如何分配和释放虚拟内存_.md
  
   - 22_瞧一瞧Linux_伙伴系统如何分配内存_.md
  
   - 23_瞧一瞧Linux_SLAB如何分配内存_.md
  
   - 39_瞧一瞧Linux_详解socket实现与网络编程接口.md
  
   - 40_瞧一瞧Linux_详解socket的接口实现.md
  
   - 用户故事_成为面向“知识库”的工程师.md
  
   - 用户故事_操作系统发烧友_看不懂_因为你没动手.md
  
   - 用户故事_技术人如何做选择，路才越走越宽_.md
  
   - 用户故事_用好动态调试，助力课程学习.md
  
   - 用户故事_yiyang_我的上机实验“爬坑指南”.md
  
   - 用户故事｜艾同学_路虽远，行则将至.md
  
   - 用户故事｜驰往_借镜观形，学以致用.md
  
   - 参考答案_对答案，是再次学习的一个机会.md
  