site_name: 赵成的运维体系管理课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_带给你不一样的运维思考.md
  
   - 01_为什么Netflix没有运维岗位_.md
  
   - 02_微服务架构时代，运维体系建设为什么要以“应用”为核心_.md
  
   - 03_标准化体系建设（上）_如何建立应用标准化体系和模型_.md
  
   - 04_标准化体系建设（下）_如何建立基础架构标准化及服务化体系_.md
  
   - 05_如何从生命周期的视角看待应用运维体系建设_.md
  
   - 06_聊聊CMDB的前世今生.md
  
   - 07_有了CMDB，为什么还需要应用配置管理_.md
  
   - 08_如何在CMDB中落地应用的概念_.md
  
   - 09_如何打造运维组织架构_.md
  
   - 10_谷歌SRE运维模式解读.md
  
   - 11_从谷歌CRE谈起，运维如何培养服务意识_.md
  
   - 12_持续交付知易行难，想做成这事你要理解这几个关键点.md
  
   - 13_持续交付的第一关键点_配置管理.md
  
   - 14_如何做好持续交付中的多环境配置管理_.md
  
   - 15_开发和测试争抢环境_是时候进行多环境建设了.md
  
   - 16_线上环境建设，要扛得住真刀真枪的考验.md
  
   - 17_人多力量大vs.两个披萨原则，聊聊持续交付中的流水线模式.md
  
   - 18_持续交付流水线软件构建难吗_有哪些关键问题_.md
  
   - 19_持续交付中流水线构建完成后就大功告成了吗_别忘了质量保障.md
  
   - 20_做持续交付概念重要还是场景重要_看“笨办法”如何找到最佳方案.md
  
   - 21_极端业务场景下，我们应该如何做好稳定性保障_.md
  
   - 22_稳定性实践_容量规划之业务场景分析.md
  
   - 23_稳定性实践_容量规划之压测系统建设.md
  
   - 24_稳定性实践_限流降级.md
  
   - 25_稳定性实践_开关和预案.md
  
   - 26_稳定性实践_全链路跟踪系统，技术运营能力的体现.md
  
   - 27_故障管理_谈谈我对故障的理解.md
  
   - 28_故障管理_故障定级和定责.md
  
   - 29_故障管理_鼓励做事，而不是处罚错误.md
  
   - 30_故障管理_故障应急和故障复盘.md
  
   - 31_唇亡齿寒，运维与安全.md
  
   - 32_为什么蘑菇街会选择上云_是被动选择还是主动出击_.md
  
   - 33_为什么混合云是未来云计算的主流形态_.md
  
   - 34_SpringCloud_面向应用层的云架构解决方案.md
  
   - 35_以绝对优势立足_从CDN和云存储来聊聊云生态的崛起.md
  
   - 36_量体裁衣方得最优解_聊聊页面静态化架构和二级CDN建设.md
  
   - 37_云计算时代，我们所说的弹性伸缩，弹的到底是什么_.md
  
   - 38_我是如何走上运维岗位的_.md
  
   - 39_云计算和AI时代，运维应该如何做好转型_.md
  
   - 40_运维需要懂产品和运营吗_.md
  
   - 41_冷静下来想想，员工离职这事真能“防得住”吗_.md
  
   - 42_树立个人品牌意识_从背景调查谈谈职业口碑的重要性.md
  
   - 划重点_赵成的运维体系管理课精华（一）.md
  
   - 划重点_赵成的运维体系管理课精华（二）.md
  
   - 划重点_赵成的运维体系管理课精华（三）.md
  
   - 新书_《进化_运维技术变革与实践探索》.md
  
   - 特别放送｜我的2019_收获，静静等待.md
  
   - 结束语_学习的过程，多些耐心和脚踏实地.md
  