site_name: 面试现场

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_面试，这样做会功到自然成.md
  
   - 01_公司到底想要什么样的人_.md
  
   - 02_想要成功面试，先要弄懂面试过程.md
  
   - 03_面试官的面试逻辑是什么_.md
  
   - 04_现在的你，到底该不该换工作.md
  
   - 05_喜欢或擅长的工作，你该选哪一个_.md
  
   - 06_职业规划一_你真的想好要怎么发展了吗_.md
  
   - 07_职业规划二_程序员后来都去干啥了_.md
  
   - 08_如何让你的简历更受青睐.md
  
   - 09_经历没有亮点可讲_你需要做份“详历”.md
  
   - 10_面试紧张怎么办_.md
  
   - 11_面试答疑（一）_说说你面试中的一些困惑.md
  
   - 12_如何做好开场_给自我介绍加“特效”.md
  
   - 13_你真能讲明白技术吗_.md
  
   - 14_怎样展示你在项目中的重要性_.md
  
   - 15_如何认识自己的优缺点_.md
  
   - 16_透过兴趣爱好，面试官可以看出什么_.md
  
   - 17_如何让你的回答更到位_.md
  
   - 18_被面试官问住了怎么办_.md
  
   - 19_应该如何向面试官提问_.md
  
   - 20_怎么谈薪水比较好_.md
  
   - 21_面试答疑（二）_面试问答环节的一些思考.md
  
   - 22_怎样体现你的学习能力强_.md
  
   - 23_怎么体现你能把工作越做越好_.md
  
   - 24_怎样体现你的协作能力强_.md
  
   - 25_不是领导，怎么体现你的领导力_.md
  
   - 26_你解决问题的能力有多强_.md
  
   - 27_盘点面试官和应聘者的认知差异.md
  
   - 28_通过面试，你能了解这个团队多少_.md
  
   - 29_合同都签了，老板却不放你走，怎么办_.md
  
   - 30_面试答疑（三）_如何更好地体现你的能力_.md
  
   - 01_考官面对面_程序员择业时常碰到的几个疑惑.md
  
   - 02_考官面对面_如何有效地准备一场面试_.md
  
   - 03_考官面对面_面试注意事项及面试官常见的思维模式.md
  
   - 04_考官面对面_面试与应聘，如何站在对方的角度考虑问题_.md
  
   - 05_考官面对面_我是如何面试程序员的_.md
  
   - 06_考官面对面_我们是如何面试架构师的_.md
  
   - 07_考官面对面_面试经验谈之校招与社招.md
  
   - 结束语_以终为始，闭环迭代，持续提高.md
  
   - 结课测试｜这些面试技巧你都掌握了吗_.md
  