site_name: 物联网开发实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 引子｜RISC-V_物联网领域值得关注的芯片趋势是什么_.md
  
   - 实战一｜嵌入式开发_如何使用C语言开发智能电灯_.md
  
   - 实战二｜MQTT开发_如何实现联网控制_.md
  
   - 假期快乐｜这是一份暂时停更的声明.md
  
   - 开篇词_物联网这个趋势，你不应该错过.md
  
   - 01_入门介绍_如何定义物联网_.md
  
   - 02_通信技术_设备接入网络的方式有哪些_.md
  
   - 03_网络协议_设备使用什么语言与互联网对话_.md
  
   - 04_数据分析_数据的价值有哪些_.md
  
   - 05_系统实例_怎样设计一个简易物联网系统_.md
  
   - 06_物模型_如何定义智能电灯_.md
  
   - 07_零配置组网_设备如何发现彼此_.md
  
   - 08_MQTT_在实践中掌握一个通信协议.md
  
   - 09_边缘中心_物联网网关有多重要_.md
  
   - 10_数据处理框架_批处理还是流处理_.md
  
   - 11_数据存储_物联网中的数据库有哪些_.md
  
   - 12_IoTHub_面对海量设备如何打造高性能设备接入层_.md
  
   - 13_隐私_在实践中如何保护用户隐私_.md
  
   - 14_安全_物联网平台如何应对安全风险_.md
  
   - 15_平台_智能家居开源平台的生态是怎样的_.md
  
   - 16_实战准备_如何搭建硬件开发环境_.md
  
   - 17_远程控制_怎样打造联网的智能电灯_.md
  
   - 18_场景联动_智能电灯如何感知光线_（上）.md
  
   - 19_场景联动_智能电灯如何感知光线_（下）.md
  
   - 20_智能语音_好玩的语音控制是怎么实现的_.md
  
   - 21_多传感器集成_浇花怎么实现自动化_.md
  
   - 22_掌控数据_家里的数据可以怎么利用_.md
  
   - 结束语_永远做一个具有极客精神的人.md
  
   - 结课测试_这些物联网的问题，你都掌握了吗_.md
  
   - 加餐一_这5本关于物联网的好书，值得一读.md
  
   - 加餐二_行业应用_物联网的发展将如何重塑我们的生活_.md
  
   - 加餐三_行业应用_物联网的发展将如何升级第一、第二产业_.md
  
   - 加餐四_5G技术将如何推动物联网的发展_.md
  
   - 加餐五_投身物联网行业，如何做好职业规划_.md
  
   - 用户故事_让野蛮生长成为职业发展的助推剂.md
  
   - 用户故事_转战物联网，我相信天道酬勤.md
  