site_name: DevOps实战笔记

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_从默默无闻到风靡全球，DevOps究竟有什么魔力_.md
  
   - 01_DevOps的“定义”_DevOps究竟要解决什么问题_.md
  
   - 02_DevOps的价值_数字化转型时代，DevOps是必选项_.md
  
   - 03_DevOps的实施_到底是工具先行还是文化先行_.md
  
   - 04_DevOps的衡量_你是否找到了DevOps的实施路线图_.md
  
   - 05_价值流分析_关于DevOps转型，我们应该从何处入手_.md
  
   - 06_转型之路_企业实施DevOps的常见路径和问题.md
  
   - 07_业务敏捷_帮助DevOps快速落地的源动力.md
  
   - 08_精益看板（上）_精益驱动的敏捷开发方法.md
  
   - 09_精益看板（下）_精益驱动的敏捷开发方法.md
  
   - 10_配置管理_最容易被忽视的DevOps工程实践基础.md
  
   - 11_分支策略_让研发高效协作的关键要素.md
  
   - 12_持续集成_你说的CI和我说的CI是一回事吗_.md
  
   - 13_自动化测试_DevOps的阿克琉斯之踵.md
  
   - 14_内建质量_丰田和亚马逊给我们的启示.md
  
   - 15_技术债务_那些不可忽视的潜在问题.md
  
   - 16_环境管理_一切皆代码是一种什么样的体验_.md
  
   - 17_部署管理_低风险的部署发布策略.md
  
   - 18_混沌工程_软件领域的反脆弱.md
  
   - 19_正向度量_如何建立完整的DevOps度量体系_.md
  
   - 20_持续改进_PDCA体系和持续改进的意义.md
  
   - 21_开源还是自研_企业DevOps平台建设的三个阶段.md
  
   - 22_产品设计之道_DevOps产品设计的五个层次.md
  
   - 23_持续交付平台_现代流水线必备的十大特征（上）.md
  
   - 24_持续交付平台_现代流水线必备的十大特征（下）.md
  
   - 25_让数据说话_如何建设企业级数据度量平台_.md
  
   - 26_平台产品研发_三个月完成千人规模的产品要怎么做_.md
  
   - 27_巨人的肩膀_那些你不能忽视的开源工具.md
  
   - 28_迈向云端_云原生应用时代的平台思考.md
  
   - 29_向前一步_万人规模企业的DevOps实战转型案例（上）.md
  
   - 30_向前一步_万人规模企业的DevOps实战转型案例（下）.md
  
   - 特别放送（一）_成为DevOps工程师的必备技能（上）.md
  
   - 特别放送（二）_成为DevOps工程师的必备技能（下）.md
  
   - 特别放送（三）_学习DevOps不得不了解的经典资料.md
  
   - 特别放送（四）_Jenkins产品经理是如何设计产品的_.md
  
   - 特别放送（五）_关于DevOps组织和文化的那些趣事儿.md
  
   - 期中总结_3个典型问题答疑及如何高效学习.md
  
   - 期末总结_在云时代，如何选择一款合适的流水线工具_.md
  
   - 结束语_持续改进，成就非凡！.md
  
   - 结课问卷获奖用户名单.md
  
   - 期末测试_这些DevOps核心知识，你都掌握了吗_.md
  