site_name: SRE实践_服务可靠性案例课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜互联网公司故障频发，我们应该如何保障服务持续可靠_.md
  
   - 导学｜如何构建坚不可摧的服务可靠性体系_.md
  
   - 01｜监控_如何从业务视角出发添加监控_.md
  
   - 02｜容量_从业务视角看容量到底是什么_.md
  
   - 03｜变更_为什么说变更是可靠性的第一杀手_.md
  
   - 04｜预案_预案的三板斧指的是什么_.md
  
   - 05｜备份和恢复_可靠性的最后一道防线.md
  
   - 06｜可靠性文化和规范_人是万物的尺度.md
  
   - 微软蓝屏事件_如何应对变更带来的问题_.md
  
   - 网易云音乐故障猜想_如何避免迁移带来的问题_.md
  
   - 07｜监控场景_为什么所有故障都有监控的因素_.md
  
   - 08｜容量场景（一）_12306为什么现在能扛住春节抢票了_.md
  
   - 09｜容量场景（二）_一次让网盘雪崩的热点事件.md
  
   - 10｜容量场景（三）_一条让新浪工程师们通宵加班的微博.md
  
   - 11｜变更场景（一）_一条让Facebook蒸发百亿的指令.md
  
   - 12｜变更场景（二）_一次简单升级竟然损失几千万.md
  
   - 13｜变更场景（三）_连续绊倒两个云厂商的故障.md
  
   - 14｜预案场景（一）_B站最为深刻的一次自我剖析.md
  
   - 15｜预案场景（二）_一次机房故障为何让多位高管被辞退_.md
  
   - 16｜备份和恢复_一次误操作中断7小时.md
  
   - 17｜可靠性意识_可靠性Oncall十大原则.md
  
   - 18｜概述_AIOps涉及哪些领域和方向_.md
  
   - 19｜AIOps故障发现_我们如何看到肉眼看不到的故障_.md
  
   - 20｜AIOps问题定位_如何在报警风暴中找到暴风眼_.md
  
   - 21｜AIOps容量预测_如何准确地预估流量_.md
  
   - 22｜AIOps变更管理_如何进行更全面地检查与更精准地阻断_.md
  
   - 23｜AIOps智能决策_给故障处理安装一个大脑.md
  
   - 24｜AIOps数据可靠性_如何预测磁盘故障.md
  
   - 25｜可靠性基础科学_可靠性背后的运筹学和概率学.md
  
   - 结束语｜这里不是终点，而是一个起点.md
  
   - 结课测试｜来赴一场满分之约.md
  