site_name: Python实战·从0到1搭建直播视频平台

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜打通前后端技术，玩转视频平台.md
  
   - 01｜初识Python（上）_入门Python你应该怎么做_.md
  
   - 02｜初识Python（下）_入门Python你应该怎么做_.md
  
   - 03｜初识Web_学习Web最好的方式是什么_.md
  
   - 04｜Vue概览_Vue哪些内容是你必须要掌握的_.md
  
   - 18｜初识Flask_搭建第一个Flask项目.md
  
   - 19｜路由定义和视图常用逻辑_路由定义和视图的核心是什么_.md
  
   - 20｜匹配路由&amp;amp;异常捕获_如何用转化器实现匹配规则_.md
  
   - 21｜数据库ORM对象关系映射（一）_数据库连接与必备操作.md
  
   - 22｜数据库应用（二）_数据库ORM对象关系映射.md
  
   - 23｜数据库应用（三）_项目数据库配置实战.md
  
   - 24｜数据库应用（四）_如何在项目中灵活应用数据库操作.md
  
   - 25｜Blueprint与Redprint_如何让程序进行模块化处理_.md
  
   - 26｜RESTfulAPI与Flask-Restful_如何实现后端接口的开发与封装_.md
  
   - 27｜初识认证机制_认证机制能解决哪些问题_.md
  
   - 28｜认证机制_Flask认证机制设计与实现.md
  
   - 29｜后端功能接口实战（一）_后端接口该如何开发_.md
  
   - 30｜后端功能接口实战（二）_后端接口该如何开发_.md
  
   - 31｜项目实战与部署_如何实现接口部署与访问_.md
  
   - 32｜全面解析HTTP_从HTTP_0.9到HTTP_3的演变.md
  
   - 33｜直播流程_如何设计搭建直播的核心流程_.md
  
   - 34｜Nginx安装与直播配置_Nginx如何实现直播配置_.md
  
   - 35｜RTMP协议与NRM搭建_如何使用NRM支持HLS协议直播_.md
  
   - 36｜推拉流、串流码与控制器_实现录制与停止直播流.md
  
   - 37｜直播完整实现_使用Nginx-rtmp-module配置RTMP直播服务.md
  
   - 38｜回顾总结_前后端知识体系全景回顾.md
  
   - 05｜需求分析_如何确定在线视频平台的核心功能模块_.md
  
   - 06｜框架搭建_如何用vue-cli搭建一个前端框架_.md
  
   - 07｜路由设计_如何借助VueRouter设计出更合理的路由_.md
  
   - 08｜个人中心与权限_如何玩转各类系统的权限管理_.md
  
   - 09｜ElementU&amp;amp;CSS_如何设计页面逻辑与功能点_.md
  
   - 10｜详情页实现_如何实现需求定制化_.md
  
   - 11｜DPlayer播放器综合应用_怎样实现自己的第一个视频播放器_.md
  
   - 12｜视频发布功能实现_怎样满足用户发布视频的需求_.md
  
   - 13｜数据中心应用_平台数据大脑应具备哪些核心指标_.md
  
   - 14｜ECharts实战_可视化如何更好地服务于创作者_.md
  
   - 15｜直播中心搭建（一）_如何通过Video.js配置直播中心_.md
  
   - 16｜直播中心搭建（二）_如何通过VideoJs配置直播中心_.md
  
   - 17｜项目打包与优化_前端必备的Webpack打包配置详解.md
  
   - 答疑篇｜前导篇&amp;amp;前端实战篇思考题答案.md
  
   - 结束语｜在技术的浪潮中，成为奔腾不息的后浪.md
  
   - 结课测试｜来赴一场满分之约！.md
  