site_name: 重学前端

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_从今天起，重新理解前端.md
  
   - 明确你的前端学习路线与方法.md
  
   - 列一份前端知识架构图.md
  
   - JavaScript类型_关于类型，有哪些你不知道的细节_.md
  
   - JavaScript对象_面向对象还是基于对象_.md
  
   - JavaScript对象_我们真的需要模拟类吗_.md
  
   - JavaScript对象_你知道全部的对象分类吗_.md
  
   - JavaScript执行（一）_Promise里的代码为什么比setTimeout先执行_.md
  
   - JavaScript执行（二）_闭包和执行上下文到底是怎么回事_.md
  
   - JavaScript执行（三）_你知道现在有多少种函数吗_.md
  
   - JavaScript执行（四）_try里面放return，finally还会执行吗_.md
  
   - JavaScript词法_为什么12.toString会报错_.md
  
   - （小实验）理解编译原理_一个四则运算的解释器.md
  
   - JavaScript语法（预备篇）_到底要不要写分号呢_.md
  
   - JavaScript语法（一）_在script标签写export为什么会抛错_.md
  
   - JavaScript语法（二）_你知道哪些JavaScript语句_.md
  
   - JavaScript语法（三）_什么是表达式语句_.md
  
   - JavaScript语法（四）_新加入的__运算符，哪里有些不一样呢_.md
  
   - HTML语义_div和span不是够用了吗_.md
  
   - HTML语义_如何运用语义类标签来呈现Wiki网页_.md
  
   - CSS语法_除了属性和选择器，你还需要知道这些带@的规则.md
  
   - HTML元信息类标签_你知道head里一共能写哪几种标签吗_.md
  
   - CSS选择器_如何选中svg里的a元素_.md
  
   - CSS选择器_伪元素是怎么回事儿_.md
  
   - HTML链接_除了a标签，还有哪些标签叫链接_.md
  
   - CSS排版_从毕昇开始，我们就开始用正常流了.md
  
   - HTML替换型元素_为什么link一个CSS要用href，而引入js要用src呢_.md
  
   - HTML小实验_用代码分析HTML标准.md
  
   - CSSFlex排版_为什么垂直居中这么难_.md
  
   - CSS动画与交互_为什么动画要用贝塞尔曲线这么奇怪的东西_.md
  
   - HTML语言_DTD到底是什么_.md
  
   - CSS渲染_CSS是如何绘制颜色的_.md
  
   - CSS小实验_动手做，用代码挖掘CSS属性.md
  
   - HTML·ARIA_可访问性是只给盲人用的特性么_.md
  
   - 浏览器_一个浏览器是如何工作的_（阶段一）.md
  
   - 浏览器_一个浏览器是如何工作的_（阶段二）.md
  
   - 浏览器_一个浏览器是如何工作的（阶段三）.md
  
   - 浏览器_一个浏览器是如何工作的_（阶段四）.md
  
   - 浏览器_一个浏览器是如何工作的_（阶段五）.md
  
   - 浏览器DOM_你知道HTML的节点有哪几种吗_.md
  
   - 浏览器CSSOM_如何获取一个元素的准确位置.md
  
   - 浏览器事件_为什么会有捕获过程和冒泡过程_.md
  
   - 浏览器API（小实验）_动手整理全部API.md
  
   - 性能_前端的性能到底对业务数据有多大的影响_.md
  
   - 工具链_什么样的工具链才能提升团队效率_.md
  
   - 持续集成_几十个前端一起工作，如何保证工作质量_.md
  
   - 搭建系统_大量的低价值需求应该如何应对_.md
  
   - 前端架构_前端架构有哪些核心问题_.md
  
   - 新年彩蛋_2019，有哪些前端技术值得关注_.md
  
   - 用户故事_那些你与“重学前端”的不解之缘.md
  
   - 期中答疑_name(){}与name:function(){}，两种写法有什么区别吗_.md
  
   - 答疑加餐_学了这么多前端的“小众”知识，到底对我有什么帮助_.md
  
   - 加餐_前端与图形学.md
  
   - 加餐_前端交互基础设施的建设.md
  
   - 期末答疑（一）_前端代码单元测试怎么做_.md
  
   - 期末答疑（二）_前端架构中，每个逻辑页面如何可以做到独立发布呢_.md
  
   - 尾声_长风破浪会有时，直挂云帆济沧海.md
  