site_name: 深入剖析Kubernetes

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_打通“容器技术”的任督二脉.md
  
   - 01_预习篇·小鲸鱼大事记（一）_初出茅庐.md
  
   - 02_预习篇·小鲸鱼大事记（二）_崭露头角.md
  
   - 03_预习篇·小鲸鱼大事记（三）_群雄并起.md
  
   - 04_预习篇·小鲸鱼大事记（四）_尘埃落定.md
  
   - 05_白话容器基础（一）_从进程说开去.md
  
   - 06_白话容器基础（二）_隔离与限制.md
  
   - 07_白话容器基础（三）_深入理解容器镜像.md
  
   - 08_白话容器基础（四）_重新认识Docker容器.md
  
   - 09_从容器到容器云_谈谈Kubernetes的本质.md
  
   - 10_Kubernetes一键部署利器_kubeadm.md
  
   - 11_从0到1_搭建一个完整的Kubernetes集群.md
  
   - 12_牛刀小试_我的第一个容器化应用.md
  
   - 13_为什么我们需要Pod_.md
  
   - 14_深入解析Pod对象（一）_基本概念.md
  
   - 15_深入解析Pod对象（二）_使用进阶.md
  
   - 16_编排其实很简单_谈谈“控制器”模型.md
  
   - 17_经典PaaS的记忆_作业副本与水平扩展.md
  
   - 18_深入理解StatefulSet（一）_拓扑状态.md
  
   - 19_深入理解StatefulSet（二）_存储状态.md
  
   - 20_深入理解StatefulSet（三）_有状态应用实践.md
  
   - 21_容器化守护进程的意义_DaemonSet.md
  
   - 22_撬动离线业务_Job与CronJob.md
  
   - 23_声明式API与Kubernetes编程范式.md
  
   - 24_深入解析声明式API（一）_API对象的奥秘.md
  
   - 25_深入解析声明式API（二）_编写自定义控制器.md
  
   - 26_基于角色的权限控制_RBAC.md
  
   - 27_聪明的微创新_Operator工作原理解读.md
  
   - 28_PV、PVC、StorageClass，这些到底在说啥_.md
  
   - 29_PV、PVC体系是不是多此一举_从本地持久化卷谈起.md
  
   - 30_编写自己的存储插件_FlexVolume与CSI.md
  
   - 31_容器存储实践_CSI插件编写指南.md
  
   - 32_浅谈容器网络.md
  
   - 33_深入解析容器跨主机网络.md
  
   - 34_Kubernetes网络模型与CNI网络插件.md
  
   - 35_解读Kubernetes三层网络方案.md
  
   - 36_为什么说Kubernetes只有softmulti-tenancy_.md
  
   - 37_找到容器不容易_Service、DNS与服务发现.md
  
   - 38_从外界连通Service与Service调试“三板斧”.md
  
   - 39_谈谈Service与Ingress.md
  
   - 40_Kubernetes的资源模型与资源管理.md
  
   - 41_十字路口上的Kubernetes默认调度器.md
  
   - 42_Kubernetes默认调度器调度策略解析.md
  
   - 43_Kubernetes默认调度器的优先级与抢占机制.md
  
   - 44_KubernetesGPU管理与DevicePlugin机制.md
  
   - 45_幕后英雄_SIG-Node与CRI.md
  
   - 46_解读CRI与容器运行时.md
  
   - 47_绝不仅仅是安全_KataContainers与gVisor.md
  
   - 48_Prometheus、MetricsServer与Kubernetes监控体系.md
  
   - 49_CustomMetrics:让AutoScaling不再“食之无味”.md
  
   - 50_让日志无处可逃_容器日志收集与管理.md
  
   - 51_谈谈Kubernetes开源社区和未来走向.md
  
   - 52_答疑_在问题中解决问题，在思考中产生思考.md
  
   - 特别放送_2019年，容器技术生态会发生些什么_.md
  
   - 特别放送_基于Kubernetes的云原生应用管理，到底应该怎么做_.md
  
   - 结束语_Kubernetes_赢开发者赢天下.md
  
   - 结课测试｜这些Kubernetes的相关知识，你都掌握了吗_.md
  