site_name: DDD实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_学好了DDD，你能做什么_.md
  
   - 01_领域驱动设计_微服务设计为什么要选择DDD_.md
  
   - 02_领域、子域、核心域、通用域和支撑域_傻傻分不清_.md
  
   - 03_限界上下文_定义领域边界的利器.md
  
   - 04_实体和值对象_从领域模型的基础单元看系统设计.md
  
   - 05_聚合和聚合根_怎样设计聚合_.md
  
   - 06_领域事件_解耦微服务的关键.md
  
   - 07_DDD分层架构_有效降低层与层之间的依赖.md
  
   - 08_微服务架构模型_几种常见模型的对比和分析.md
  
   - 09_中台_数字转型后到底应该共享什么_.md
  
   - 10_DDD、中台和微服务_它们是如何协作的_.md
  
   - 答疑_有关3个典型问题的讲解.md
  
   - 11_DDD实践_如何用DDD重构中台业务模型_.md
  
   - 12_领域建模_如何用事件风暴构建领域模型_.md
  
   - 13_代码模型（上）_如何使用DDD设计微服务代码模型_.md
  
   - 14_代码模型（下）_如何保证领域模型与代码模型的一致性_.md
  
   - 15_边界_微服务的各种边界在架构演进中的作用_.md
  
   - 16_视图_如何实现服务和数据在微服务各层的协作_.md
  
   - 17_从后端到前端_微服务后，前端如何设计_.md
  
   - 18_知识点串讲_基于DDD的微服务设计实例.md
  
   - 19_总结（一）_微服务设计和拆分要坚持哪些原则_.md
  
   - 20_总结（二）_分布式架构关键设计10问.md
  
   - 结束语_所谓高手，就是跨过坑和大海！.md
  
   - 基于DDD的微服务设计实例代码详解.md
  
   - 抽奖｜《DDD实战课》沉淀成书了，感谢有你！.md
  
   - 期末测试_有关DDD的内容，你掌握了多少呢_.md
  