site_name: 技术面试官识人手册

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_世事洞明皆学问，人情练达即文章_小面试，大道理.md
  
   - 01_评估体系_公司和团队到底需要怎样的技术人才_.md
  
   - 02_制定计划_好的计划是成功的一半.md
  
   - 03_问题设计（上）_三大原则理清面试考察方向.md
  
   - 04_问题设计（下）_五个技巧助攻技术问题设计.md
  
   - 答疑课堂01_面试计划篇热点问题解答.md
  
   - 05_流程把控_控好流程，让面试进程高效有温度.md
  
   - 06_算法和数据结构考察_怎样有层次地驾驭算法考察_.md
  
   - 07_系统设计能力考察_系统设计内功到底怎么考_.md
  
   - 08_其它技能考察_见微知著，不可忽略的其它考察点.md
  
   - 答疑课堂02_面试实践篇热点问题解答.md
  
   - 09_决策会准备_怎样全面收集事实，有效提炼数据_.md
  
   - 10_决策会开展（上）_怎样引导争辩，达成共识_.md
  
   - 11_决策会开展（下）_怎样确保评估全面且有深度_.md
  
   - 答疑课堂03_面试决策篇热点问题解答.md
  
   - 12_线上面试_隔屏对话，交流依然畅通.md
  
   - 13_简历识人_洞悉简历背后信息，动态调节面试策略.md
  
   - 结束语_操千曲而后晓声，观千剑而后识器.md
  
   - 结课测试｜这些面试问题，你都掌握了么_.md
  