site_name: 从0开始做增长

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_人人都是增长官.md
  
   - 01预习_增长小白如何“弯道超车”_.md
  
   - 02预习_如何理解“增长”_.md
  
   - 03预习_不同职能如何做好增长_.md
  
   - 04预习_做增长如何处理职能间的矛盾_.md
  
   - 05_正确目标找不对，天天加班也枉然.md
  
   - 06_活学活用北极星指标.md
  
   - 07_OKR如何助力增长_.md
  
   - 08_不懂用户调研_那就对了！.md
  
   - 09_调研目标_在差异性洞察中找到爆破点.md
  
   - 10_数据分析_在“花式对比”中发现玄机.md
  
   - 11_用户分类_围绕北极星指标细分人群.md
  
   - 12_用户访谈_像侦探一样寻找破案线索（上）.md
  
   - 13_用户访谈_像侦探一样寻找破案线索（下）.md
  
   - 14_提炼用户差异，发现增长契机.md
  
   - 15_挖掘产品优势，打破增长瓶颈.md
  
   - 16_定位营销差异，抢占用户心智.md
  
   - 17_一级方向_找到增长爆破点.md
  
   - 18_B端产品如何调研_.md
  
   - 19_全局规划增长机会.md
  
   - 20_统筹全局的用户增长地图.md
  
   - 21_案例解析_定义关键增长指标.md
  
   - 22_正负双向洞察，找准切入点.md
  
   - 23_二级机会_制定增长策略.md
  
   - 24_为一家濒临破产的公司制定增长策略（上）.md
  
   - 25_为一家濒临破产的公司制定增长策略（中）.md
  
   - 26_为一家濒临破产的公司制定增长策略（下）.md
  
   - 27_为什么指标数据怎么优化都不提升_.md
  
   - 28_案例解析_打造增长闭环（上）.md
  
   - 29_案例解析_打造增长闭环（下）.md
  
   - 30_案例解析_唤醒沉睡用户（上）.md
  
   - 31_案例解析_唤醒沉睡用户（下）.md
  
   - 32_没有分解，就无缘增长.md
  
   - 33_四个要点颠覆传统需求文档.md
  
   - 34_三级落地_无限场景应用.md
  
   - 35_手把手教你设计一次成功的实验（上）.md
  
   - 36_手把手教你设计一次成功的实验（下）.md
  
   - 37_积少可成多，别针换别墅.md
  
   - 38_四级延续_增长组件库案例.md
  
   - 39_以用户为中心增长.md
  
   - 预习答疑_你需要一张思维导图吗_.md
  
   - 增长导航图_增长专栏的知识架构是怎样的_.md
  
   - 尾声_结束意味着新的开始.md
  
   - 结课测试_这些“增长”知识，你真的掌握了吗_.md
  