site_name: 系统性能调优必知必会

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_万变不离其宗，性能优化也有章可循.md
  
   - 01_CPU缓存_怎样写代码能够让CPU执行得更快_.md
  
   - 02_内存池_如何提升内存分配的效率_.md
  
   - 03_索引_如何用哈希表管理亿级对象_.md
  
   - 04_零拷贝_如何高效地传输文件_.md
  
   - 05_协程_如何快速地实现高并发服务_.md
  
   - 06_锁_如何根据业务场景选择合适的锁_.md
  
   - 07_性能好，效率高的一对多通讯该如何实现_.md
  
   - 08_事件驱动_C10M是如何实现的_.md
  
   - 09_如何提升TCP三次握手的性能_.md
  
   - 10_如何提升TCP四次挥手的性能_.md
  
   - 11_如何修改TCP缓冲区才能兼顾并发数量与传输速度_.md
  
   - 12_如何调整TCP拥塞控制的性能_.md
  
   - 13_实战_单机如何实现管理百万主机的心跳服务_.md
  
   - 14_优化TLS_SSL性能该从何下手_.md
  
   - 15_如何提升HTTP_1.1性能_.md
  
   - 16_HTTP_2是怎样提升性能的_.md
  
   - 17_Protobuf是如何进一步提高编码效率的_.md
  
   - 18_如何通过gRPC实现高效远程过程调用_.md
  
   - 期中考试｜行至半程，你的收获如何呢_.md
  
   - 加餐1｜特别福利_陶辉视频课精选.md
  
   - 加餐2｜答疑精选_这些问题你都清楚吗_.md
  
   - 19_如何通过监控找到性能瓶颈_.md
  
   - 20_CAP理论_怎样舍弃一致性去换取性能_.md
  
   - 21_AKF立方体_怎样通过可扩展性来提高性能_.md
  
   - 22_NWR算法_如何修改读写模型以提升性能_.md
  
   - 23_负载均衡_选择Nginx还是OpenResty_.md
  
   - 24_一致性哈希_如何高效地均衡负载_.md
  
   - 25_过期缓存_如何防止缓存被流量打穿_.md
  
   - 26_应用层多播_如何快速地分发内容_.md
  
   - 27_消息队列_如何基于异步消息提升性能_.md
  
   - 28_MapReduce_如何通过集群实现离线计算_.md
  
   - 29_流式计算_如何通过集群实现实时计算_.md
  
   - 30_如何权衡关系数据库与NoSQL数据库_.md
  
   - 加餐3_大厂面试到底在考些什么_.md
  
   - 大咖助场1_李玥_高并发场景下如何优化微服务的性能_.md
  
   - 大咖助场2｜庄振运_与程序员相关的SSD性能知识.md
  
   - 加餐4｜百万并发下Nginx的优化之道.md
  
   - 大咖助场3｜傅健_那些年，影响我们达到性能巅峰的常见绊脚石（上）.md
  
   - 大咖助场4｜傅健_那些年，影响我们达到性能巅峰的常见绊脚石（下）.md
  
   - 加餐5_如何理解分布式系统_.md
  
   - 加餐6｜分布式系统的本质是什么_.md
  
   - 加餐7｜深入剖析HTTP_3协议.md
  
   - 结束语_从业IT20年后，我将最看重什么_.md
  
   - 来领奖啦！你填写毕业问卷了吗_.md
  
   - 毕业问卷获奖用户名单.md
  
   - 期末测试｜对于性能优化，你掌握了多少呢_.md
  