site_name: 成为AI产品经理

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_你好，产品经理！你的未来价值壁垒在哪儿_.md
  
   - 01_行业视角_产品经理眼中的人工智能.md
  
   - 02_个人视角_成为AI产品经理，要先搞定这两个问题.md
  
   - 03_技术视角_AI产品经理需要懂的技术全景图.md
  
   - 04_过来人讲_成为AI产品经理的两条路径.md
  
   - 05_通过一个AI产品的落地，掌握产品经理工作全流程.md
  
   - 06｜AI模型的构建过程是怎样的_（上）.md
  
   - 07｜AI模型的构建过程是怎样的_（下）.md
  
   - 08_算法全景图_AI产品经理必须要懂的算法有哪些_.md
  
   - 09_K近邻算法_机器学习入门必学算法.md
  
   - 10_线性回归_教你预测，投放多少广告带来的收益最大.md
  
   - 11_逻辑回归_如何预测用户是否会购买商品_.md
  
   - 12_朴素贝叶斯_让AI告诉你，航班延误险该不该买_.md
  
   - 13_决策树与随机森林_如何预测用户会不会违约_.md
  
   - 14_支持向量机_怎么预测股票市场的涨与跌_.md
  
   - 15_K-means聚类算法_如何挖掘高价值用户_.md
  
   - 期中答疑_AI产品经理热门问题答疑合集.md
  
   - 期中周测试题，你做对了吗_.md
  
   - 16_深度学习_当今最火的机器学习技术，你一定要知道.md
  
   - 17_模型评估_从一个失控的项目看优秀的产品经理如何评估AI模型_.md
  
   - 18_核心技能_产品经理评估模型需要关注哪些指标_.md
  
   - 19_模型性能评估（一）_从信用评分产品看什么是混淆矩阵_.md
  
   - 20_模型性能评估（二）_从信用评分产品看什么是KS、AUC_.md
  
   - 21_模型性能评估（三）_从股价预测产品看回归算法常用的评估指标.md
  
   - 22_模型稳定性评估_如何用PSI来评估信用评分产品的稳定性_.md
  
   - 春节加餐1_用户增长模型_怎么利用AI技术判断新渠道性价比_.md
  
   - 春节加餐2_一次答疑，带你回顾模型评估的所有基础概念.md
  
   - 23_模型监控_产品经理如何建设算法模型监控指标体系_.md
  
   - 24_推荐类产品（一）_推荐系统产品经理的工作职责与必备技能.md
  
   - 25_推荐类产品（二）_从0打造电商个性化推荐系统产品.md
  
   - 26_预测类产品（一）_用户复购意向预测的底层逻辑是什么_.md
  
   - 27_预测类产品（二）_从0打造一款预测用户复购意向的产品.md
  
   - 28_预测类产品（三）_从0打造一款“大白信用评分产品”.md
  
   - 29_自然语言处理产品_从0打造一款智能客服产品.md
  
   - 30_AI产品经理，你该如何提升自己的价值_.md
  
   - 31_AI产品经理面试，这些问题你必须会答！.md
  
   - 结束语_唯一不变的，就是变化本身！.md
  
   - 期末考试_“AI产品经理”100分试卷等你来挑战！.md
  