site_name: Vue3企业级项目实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜为何掌握了技术API，依然在项目中处处掣肘_.md
  
   - 01｜编译和非编译模式_离开Vue工具，你还知道怎么用Vue3吗_.md
  
   - 02｜Webpack编译搭建_如何用Webpack初构建Vue3项目_.md
  
   - 03｜从Rollup到Vite_如何用Vite构建你的Vue3项目_.md
  
   - 04｜模版语法和JSX语法_你知道Vue可以用JSX写吗_.md
  
   - 05｜响应式开发操作_如何理解和使用Vue3的响应式数据_.md
  
   - 06｜跨组件数据通信_常见的组件间数据通信方式有哪些_.md
  
   - 07｜项目代码规范_如何成为一名合格的团队协作工程师_.md
  
   - 加餐｜基础篇思考题答疑.md
  
   - 08｜如何从零搭建自研的Vue组件库_.md
  
   - 09｜主题方案和基础组件_如何设计组件库的主题方案_.md
  
   - 10｜动态渲染组件_如何实现Vue的动态渲染组件_.md
  
   - 11｜布局组件_如何实现自研组件库的布局方案_.md
  
   - 12｜受控表单组件_如何开发受控的表单组件_.md
  
   - 13｜动态表单组件_怎么优雅地动态渲染表单_.md
  
   - 14｜代码单元测试_如何轻松地保证自己的代码质量_.md
  
   - 加餐｜进阶篇思考题答疑.md
  
   - 围炉夜话｜学了新技术，在公司用不上怎么办_.md
  
   - 围炉夜话｜Leader眼里最有潜力的仔长什么样_.md
  
   - 围炉夜话｜你的职业起点和职业终点是什么_.md
  
   - 15｜定制运营拖拽组件_如何实现运营搭建页面的拖拽功能_.md
  
   - 16｜单页面应用_如何理解和实现单页面应用开发_.md
  
   - 17｜Koa.js_如何结合Koa.js开发Node.jsWeb服务_.md
  
   - 18｜Node.js服务端渲染页面_客户端渲染和服务端渲染有何区别_.md
  
   - 19｜全栈项目搭建_如何搭建Vue.js的前后台全栈项目_.md
  
   - 20｜数据库方案设计_如何设计运营搭建平台的数据库_.md
  
   - 21｜用户注册和登录_如何结合Vue3和Koa.js实现注册登录_.md
  
   - 22｜物料组件的编译和管理_如何处理组件的多种模块格式_.md
  
   - 23｜运营物料的后台管理_如何全栈化实现列表分页的功能_.md
  
   - 加餐｜实战篇思考题答疑（上）.md
  
   - 24｜后台搭建数据源_如何设计运营搭建页面的数据结构_.md
  
   - 25｜后台搭建功能_如何设计和实现Vue.js运营后台的搭建功能_.md
  
   - 26｜页面编译和运行_如何设计Vue.js搭建页面的渲染策略_.md
  
   - 27｜后台发布流程_如何实现Vue.js搭建页面的发布流程_.md
  
   - 28｜前台页面版本化管理_如何实现搭建页面的迭代策略_.md
  
   - 29｜前台页面的渲染方式_如何设计前台页面的渲染策略_.md
  
   - 30｜前台页面的性能优化_如何实现前台页面的性能优化_.md
  
   - 31｜前台页面的日志监控_如何进行页面实时监控与问题定位_.md
  
   - 加餐｜实战篇思考题答疑（下）.md
  
   - 32｜单元测试_如何打造Vue.js和Node.js全栈项目的单元测试_.md
  
   - 33｜页面功能扩展_如何对Vue.js全栈项目做优雅扩展_.md
  
   - 34｜服务端功能扩展_如何对Vue.js全栈项目做服务端功能扩展_.md
  
   - 35｜多进程部署_如何最大限度利用服务器资源运行Node.js服务_.md
  
   - 36｜日志收集与问题排错_如何守护好Vue.js和Node.js的全栈项目_.md
  
   - 加餐｜增强篇思考题答疑.md
  
   - 结束语｜时刻做好“军备竞赛”，机会只留给有准备的人.md
  
   - 期末测试｜来赴一场满分之约！.md
  