site_name: 编译原理实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_在真实世界的编译器中游历.md
  
   - 学习指南_如何学习这门编译原理实战课_.md
  
   - 01_编译的全过程都悄悄做了哪些事情_.md
  
   - 02_词法分析_用两种方式构造有限自动机.md
  
   - 03_语法分析_两个基本功和两种算法思路.md
  
   - 04_语义分析_让程序符合语义规则.md
  
   - 05_运行时机制_程序如何运行，你有发言权.md
  
   - 06_中间代码_不是只有一副面孔.md
  
   - 07_代码优化_跟编译器做朋友，让你的代码飞起来.md
  
   - 08_代码生成_如何实现机器相关的优化_.md
  
   - 知识地图_一起来复习编译技术核心概念与算法.md
  
   - 09_Java编译器（一）_手写的编译器有什么优势_.md
  
   - 10_Java编译器（二）_语法分析之后，还要做些什么_.md
  
   - 11_Java编译器（三）_属性分析和数据流分析.md
  
   - 12_Java编译器（四）_去除语法糖和生成字节码.md
  
   - 13_JavaJIT编译器（一）_动手修改Graal编译器.md
  
   - 14_JavaJIT编译器（二）_SeaofNodes为何如此强大_.md
  
   - 15_JavaJIT编译器（三）_探究内联和逃逸分析的算法原理.md
  
   - 16_JavaJIT编译器（四）_Graal的后端是如何工作的_.md
  
   - 17_Python编译器（一）_如何用工具生成编译器_.md
  
   - 18_Python编译器（二）_从AST到字节码.md
  
   - 19_Python编译器（三）_运行时机制.md
  
   - 20_JavaScript编译器（一）_V8的解析和编译过程.md
  
   - 21_JavaScript编译器（二）_V8的解释器和优化编译器.md
  
   - 22_Julia编译器（一）_如何让动态语言性能很高_.md
  
   - 23_Julia编译器（二）_如何利用LLVM的优化和后端功能_.md
  
   - 24_Go语言编译器_把它当作教科书吧.md
  
   - 25_MySQL编译器（一）_解析一条SQL语句的执行过程.md
  
   - 26_MySQL编译器（二）_编译技术如何帮你提升数据库性能_.md
  
   - 热点问题答疑_如何吃透7种真实的编译器_.md
  
   - 划重点_7种编译器的核心概念与算法.md
  
   - 期中考试_这些编译原理知识，你都掌握了吗_.md
  
   - 用户故事_易昊_程序员不止有Bug和加班，还有诗和远方.md
  
   - 27_课前导读_学习现代语言设计的正确姿势.md
  
   - 28_前端总结_语言设计也有人机工程学.md
  
   - 29_中端总结_不遗余力地进行代码优化.md
  
   - 30_后端总结_充分发挥硬件的能力.md
  
   - 31_运行时（一）_从0到语言级的虚拟化.md
  
   - 32_运行时（二）_垃圾收集与语言的特性有关吗_.md
  
   - 33_并发中的编译技术（一）_如何从语言层面支持线程_.md
  
   - 34_并发中的编译技术（二）_如何从语言层面支持协程_.md
  
   - 35_并发中的编译技术（三）_Erlang语言厉害在哪里_.md
  
   - 36_高级特性（一）_揭秘元编程的实现机制.md
  
   - 37_高级特性（二）_揭秘泛型编程的实现机制.md
  
   - 38_综合实现（一）_如何实现面向对象编程_.md
  
   - 39_综合实现（二）_如何实现函数式编程_.md
  
   - 40_成果检验_方舟编译器的优势在哪里_.md
  
   - 期末答疑与总结_再次审视学习编译原理的作用.md
  
   - 结束语_实战是唯一标准！.md
  
   - 期末考试_“编译原理实战课”100分试卷等你来挑战！.md
  
   - 不定期加餐1_远程办公，需要你我具备什么样的素质_.md
  
   - 不定期加餐2_学习技术的过程，其实是训练心理素质的过程.md
  
   - 不定期加餐3_这几年，打动我的两本好书.md
  
   - 不定期加餐4_从身边的牛人身上，我学到的一些优秀品质.md
  
   - 不定期加餐5_借助实例，探究C&#43;&#43;编译器的内部机制.md
  