site_name: 快手·音视频技术入门课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜想快速入门音视频技术，你得这么学.md
  
   - 01｜如何从色彩格式、帧率等参数角度看视频图像_.md
  
   - 02｜音频从采集到输出涉及哪些关键参数_.md
  
   - 03｜如何做音视频的封装与转码_.md
  
   - 04｜直播行业的发展概况与技术迭代.md
  
   - 05｜如何使用FFmpeg与OBS进行直播推流_.md
  
   - 06｜如何使用ffprobe分析音视频参数与内容_.md
  
   - 07_如何高效查找并使用FFmpeg常用参数_.md
  
   - 08｜FFmpeg和它的朋友们是怎么处理MP4的_.md
  
   - 09｜如何使用FFmpeg与Handbrake做转码_.md
  
   - 10_FFmpeg基础模块（一）_容器相关的API操作.md
  
   - 11_FFmpeg基础模块（二）_AVIO、AVDictionary与AVOption.md
  
   - 12_FFmpeg基础模块（三）_AVCodec.md
  
   - 13_FFmpeg有哪些常见的应用场景_.md
  
   - 14｜如何在FFmpeg中定制一个自己专属的模块_.md
  
   - 15｜如何参与到FFmpeg社区交流中_.md
  
   - 结束语｜音视频技术更宠爱脚踏实地的人.md
  
   - 期末测试｜来赴一场满分之约！.md
  