site_name: 大规模数据处理实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_从这里开始，带你走上硅谷一线系统架构师之路.md
  
   - 01_为什么MapReduce会被硅谷一线公司淘汰_.md
  
   - 02_MapReduce后谁主沉浮_怎样设计下一代数据处理技术_.md
  
   - 03_大规模数据处理初体验_怎样实现大型电商热销榜_.md
  
   - 04_分布式系统（上）_学会用服务等级协议SLA来评估你的系统.md
  
   - 05_分布式系统（下）_架构师不得不知的三大指标.md
  
   - 06_如何区分批处理还是流处理_.md
  
   - 07_Workflow设计模式_让你在大规模数据世界中君临天下.md
  
   - 08_发布_订阅模式_流处理架构中的瑞士军刀.md
  
   - 09_CAP定理_三选二，架构师必须学会的取舍.md
  
   - 10_Lambda架构_Twitter亿级实时数据分析架构背后的倚天剑.md
  
   - 11_Kappa架构_利用Kafka锻造的屠龙刀.md
  
   - 12_我们为什么需要Spark_.md
  
   - 13_弹性分布式数据集_Spark大厦的地基（上）.md
  
   - 14_弹性分布式数据集_Spark大厦的地基（下）.md
  
   - 15_SparkSQL_Spark数据查询的利器.md
  
   - 16_SparkStreaming_Spark的实时流计算API.md
  
   - 17_StructuredStreaming_如何用DataFrameAPI进行实时数据分析_.md
  
   - 18_WordCount_从零开始运行你的第一个Spark应用.md
  
   - 19_综合案例实战_处理加州房屋信息，构建线性回归模型.md
  
   - 20_流处理案例实战_分析纽约市出租车载客信息.md
  
   - 21_深入对比Spark与Flink_帮你系统设计两开花.md
  
   - 22_ApacheBeam的前世今生.md
  
   - 23_站在Google的肩膀上学习Beam编程模型.md
  
   - 24_PCollection_为什么Beam要如此抽象封装数据_.md
  
   - 25_Transform_Beam数据转换操作的抽象方法.md
  
   - 26_Pipeline_Beam如何抽象多步骤的数据流水线_.md
  
   - 27_PipelineI_O:Beam数据中转的设计模式.md
  
   - 28_如何设计创建好一个BeamPipeline_.md
  
   - 29_如何测试BeamPipeline_.md
  
   - 30_ApacheBeam实战冲刺_Beam如何runeverywhere_.md
  
   - 31_WordCountBeamPipeline实战.md
  
   - 32_BeamWindow_打通流处理的任督二脉.md
  
   - 33_横看成岭侧成峰_再战StreamingWordCount.md
  
   - 34_Amazon热销榜BeamPipeline实战.md
  
   - 35_Facebook游戏实时流处理BeamPipeline实战（上）.md
  
   - 36_Facebook游戏实时流处理BeamPipeline实战（下）.md
  
   - 37_5G时代，如何处理超大规模物联网数据.md
  
   - 38_大规模数据处理在深度学习中如何应用_.md
  
   - 39_从SQL到StreamingSQL_突破静态数据查询的次元.md
  
   - 40_大规模数据处理未来之路.md
  
   - FAQ第一期_学习大规模数据处理需要什么基础_.md
  
   - 加油站_Practicemakesperfect！.md
  
   - FAQ第二期_Spark案例实战答疑.md
  
   - FAQ第三期_ApacheBeam基础答疑.md
  
   - 结束语_世间所有的相遇，都是久别重逢.md
  