site_name: 自动化测试高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_做性价比最高的自动化测试.md
  
   - 01｜ROI价值内核_自动化测试的价值可以量化么_.md
  
   - 02｜3KU法则_如何找出最优自动化实施截面_.md
  
   - 03｜工具选择_什么工具框架值得用_.md
  
   - 04｜脚本复用_什么样的代码才值得写_.md
  
   - 05｜AutoGenAuto_所有测试工作即代码.md
  
   - 06｜左移&amp;amp;右移_测试如何在Dev和Ops领域大展身手_.md
  
   - 07｜需求提炼（一）_单体应用要测什么_.md
  
   - 08｜需求提炼（二）_微服务集群要测什么_.md
  
   - 09｜3KU法则_为一个订餐系统设计全栈测试方案.md
  
   - 10｜单元测试（一）_原来测试可以这么高效.md
  
   - 11｜单元测试（二）_四象限法让你的单测火力全开.md
  
   - 12｜集成测试（一）_一条HappyPath扫天下.md
  
   - 13｜集成测试（二）_携手开发，集测省力又省心.md
  
   - 14｜集成测试（三）_护航微服务集群迭代升级.md
  
   - 15｜UI测试_如何让UI测试更轻快便捷_.md
  
   - 16｜概念重识_如何用3KU为端到端&amp;amp;验收测试赋能_.md
  
   - 17｜元数据模型（一）_小Job模型构建大蓝图.md
  
   - 18｜元数据模型（二）_小Job模型构建大蓝图.md
  
   - 19｜排兵布阵_自动化测试的编排、扩展与重构.md
  
   - 20｜链接工具_要驱动工具，不要被工具驱动.md
  
   - 21｜设计实战（一）_一个金融交易业务的自动化测试设计.md
  
   - 22｜设计实战（二）:一个全周期自动化测试Pipeline的设计.md
  
   - 23｜设计实战（三）:一个分布式多端视频会议自动化测试设计.md
  
   - 24｜启动运行_基于Job模型的框架实现和运行.md
  
   - 25｜找准方向_如何建立有效的测试度量体系_.md
  
   - 26｜见微知著_单元测试度量避坑.md
  
   - 27｜眼见为实_如何用数据描述你的自动化测试ROI_.md
  
   - 28｜解决问题_如何保证自动化测试的可信性_.md
  
   - 29｜落地实践_搭建可持续度量的技术平台.md
  
   - 有了ChatGPT，自动化测试工程师可以躺平了吗_.md
  
   - 结束语｜测试有终点，成长无边界.md
  
   - 期末测试｜来赴一场100分之约！.md
  
   - 用户故事｜我的自动化学习之路.md
  