site_name: 数据分析实战45讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 旅程再启｜培养你的数据分析思维.md
  
   - 加餐01｜BCG分类_采购人员如何与供应商谈降本_.md
  
   - 加餐02｜RFM分层_店铺收入大幅下跌的原因是什么_.md
  
   - 加餐03｜AARRR模型_如何找到运营中的薄弱环节并进行优化_.md
  
   - 开篇词_你为什么需要数据分析能力_.md
  
   - 01丨数据分析全景图及修炼指南.md
  
   - 02丨学习数据挖掘的最佳路径是什么_.md
  
   - 03丨Python基础语法_开始你的Python之旅.md
  
   - 04丨Python科学计算_用NumPy快速处理数据.md
  
   - 05丨Python科学计算_Pandas.md
  
   - 06_学数据分析要掌握哪些基本概念_.md
  
   - 07_用户画像_标签化就是数据的抽象能力.md
  
   - 08_数据采集_如何自动化采集数据_.md
  
   - 09丨数据采集_如何用八爪鱼采集微博上的“D&amp;amp;G”评论.md
  
   - 10丨Python爬虫_如何自动化下载王祖贤海报_.md
  
   - 11_数据科学家80%时间都花费在了这些清洗任务上_.md
  
   - 12_数据集成_这些大号一共20亿粉丝_.md
  
   - 13_数据变换_考试成绩要求正态分布合理么_.md
  
   - 14丨数据可视化_掌握数据领域的万金油技能.md
  
   - 15丨一次学会Python数据可视化的10种技能.md
  
   - 16丨数据分析基础篇答疑.md
  
   - 17丨决策树（上）_要不要去打篮球_决策树来告诉你.md
  
   - 18丨决策树（中）_CART，一棵是回归树，另一棵是分类树.md
  
   - 19丨决策树（下）_泰坦尼克乘客生存预测.md
  
   - 20丨朴素贝叶斯分类（上）_如何让机器判断男女_.md
  
   - 21丨朴素贝叶斯分类（下）_如何对文档进行分类_.md
  
   - 22丨SVM（上）_如何用一根棍子将蓝红两色球分开_.md
  
   - 23丨SVM（下）_如何进行乳腺癌检测_.md
  
   - 24丨KNN（上）_如何根据打斗和接吻次数来划分电影类型_.md
  
   - 25丨KNN（下）_如何对手写数字进行识别_.md
  
   - 26丨K-Means（上）_如何给20支亚洲球队做聚类_.md
  
   - 27丨K-Means（下）_如何使用K-Means对图像进行分割_.md
  
   - 28丨EM聚类（上）_如何将一份菜等分给两个人_.md
  
   - 29丨EM聚类（下）_用EM算法对王者荣耀英雄进行划分.md
  
   - 30丨关联规则挖掘（上）_如何用Apriori发现用户购物规则_.md
  
   - 31丨关联规则挖掘（下）_导演如何选择演员_.md
  
   - 32丨PageRank（上）_搞懂Google的PageRank算法.md
  
   - 33丨PageRank（下）_分析希拉里邮件中的人物关系.md
  
   - 34丨AdaBoost（上）_如何使用AdaBoost提升分类器性能_.md
  
   - 35丨AdaBoost（下）_如何使用AdaBoost对房价进行预测_.md
  
   - 36丨数据分析算法篇答疑.md
  
   - 37丨数据采集实战_如何自动化运营微博_.md
  
   - 38丨数据可视化实战_如何给毛不易的歌曲做词云展示_.md
  
   - 39丨数据挖掘实战（1）_信用卡违约率分析.md
  
   - 40丨数据挖掘实战（2）_信用卡诈骗分析.md
  
   - 41丨数据挖掘实战（3）_如何对比特币走势进行预测_.md
  
   - 42丨当我们谈深度学习的时候，我们都在谈什么_.md
  
   - 43丨深度学习（下）_如何用Keras搭建深度学习网络做手写数字识别_.md
  
   - 44丨如何培养你的数据分析思维_.md
  
   - 45丨求职简历中没有相关项目经验，怎么办_.md
  
   - 加餐丨在社交网络上刷粉刷量，技术上是如何实现的_.md
  
   - 结束语丨当大家都在讲知识和工具的时候，我更希望你重视思维和实战.md
  
   - 结课测试_数据分析的这些知识，你真的掌握了吗_.md
  