site_name: 白话法律42讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_这年头，你真应该懂点法律常识.md
  
   - 01“老周，我想知道”_常见法律认知盲区（一）.md
  
   - 02“老周，我想知道”_律师就在你身边（二）.md
  
   - 03“老周，我想知道”_律师就在你身边（三）.md
  
   - 04“老周，我想知道”_律师就在你身边（四）.md
  
   - 05_创业未捷老板跑，社保工资哪里讨_.md
  
   - 06_保密还是“卖身”，霸王条款怎么看_.md
  
   - 07_编造流言蹭热度_看守所里降温度！.md
  
   - 08_合同在手欠款难收，报警有用吗_.md
  
   - 09_致创业_谁动了我的股权_.md
  
   - 10_又见猝死！工“殇”究竟是不是工伤_.md
  
   - 11_期权的“前世今生”.md
  
   - 12_裁员面前，你能做的还有什么_.md
  
   - 13_抄袭、盗图为什么做不得_.md
  
   - 14_加班、工资、休假，你知道多少_.md
  
   - 15_受贿原来这么“容易”.md
  
   - 16_今天你用“VPN”了吗_.md
  
   - 17_漏洞在眼前，可以悄悄破解吗_.md
  
   - 18_“爬虫”真的合法吗_.md
  
   - 19_非法集资到底是个啥_.md
  
   - 20_黄色网站_不仅仅是“黄色”罪名.md
  
   - 21_谁修改了我的积分资产_.md
  
   - 22_外挂真能大吉大利吗_.md
  
   - 23_如何看待“从删库到跑路”_.md
  
   - 24_“伪基站”是你的避风港吗_.md
  
   - 25_“网络诈骗”真的离你很远吗_.md
  
   - 26_智斗中介_“北上广”租房图鉴.md
  
   - 27_买买买！买房的“避坑”指南.md
  
   - 28_闪婚又闪离，彩礼怎么理_.md
  
   - 29_离婚还想和平_你要这么做.md
  
   - 30_遗产继承的爱恨情仇.md
  
   - 31_骗术升级_假结婚、假离婚的那些事儿.md
  
   - 32_孩子学校受伤，谁之过_.md
  
   - 33_如何让欠债还钱真正“天经地义”_.md
  
   - 34_从透支到盗刷_人人须知的银行卡纠纷.md
  
   - 35_远离“套路贷”的套路大全.md
  
   - 36_危险！酒驾为什么被罚那么重_.md
  
   - 37_老人倒地，“扶”“不服”_.md
  
   - 38_“能动手就别吵吵”，代价你真的知道吗_.md
  
   - 39_发生交通事故，如何处理_.md
  
   - 40_交通事故综合法宝.md
  
   - 41_婚姻家庭综合法宝.md
  
   - 42_买卖房屋综合法宝.md
  
   - 结束语_法律，不会终止的篇章.md
  
   - 一键直达_法律专栏“食用”指南.md
  
   - 加餐_“新冠肺炎”影响下，17个常见法律问题解答.md
  
   - 结课测试_这些法律知识，你都掌握了吗_.md
  