site_name: 云时代的JVM原理与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜云时代来临，如何学好JVM应对未来的挑战_.md
  
   - 01｜重识JVM_JVM的起源、特性与系统构成.md
  
   - 02｜挑战与趋势_云原生时代JVM的演进之路.md
  
   - 03｜工作台_JVM运行时数据区的内部机制是怎样的_.md
  
   - 04｜从JIT到AOT_JVM编译器的云原生演进之路.md
  
   - 05｜机器与语言_JVM中的字节码.md
  
   - 06｜类加载子系统（上）_类加载的流程与机制.md
  
   - 07｜类加载子系统（下）_如何打造一个属于你的类加载器_.md
  
   - 08｜反射机制_给你一把打开JVM后门的钥匙.md
  
   - 09｜SPI机制_如何打造一个属于你的SPI程序_.md
  
   - 10｜对象模型_JVM对象的内部机制和存在方式是怎样的_.md
  
   - 11｜对象创建_JVM中的对象是怎么生产出来的_.md
  
   - 12｜对象创建全家桶_JVM中对象创建的模式及最佳实践.md
  
   - 13｜对象回收（上）_如何定位待回收的对象_.md
  
   - 14｜垃圾回收（下）_揭秘垃圾回收中的算法.md
  
   - 15｜垃圾回收器_为什么G1被叫做GC中的王者_.md
  
   - 16｜垃圾回收器（下）_面向未来的ZGC、Shenandoah.md
  
   - 17｜偷龙转凤_JVM中的扩展之道.md
  
   - 18｜被忽视的变量_带你全面认识JVM中的变量.md
  
   - 19｜云时代的线程模型_领略线程与虚拟线程的风采.md
  
   - 20｜JMM_如何打造一个线程安全的程序_.md
  
   - 21｜伪共享_如何用伪共享打造高并发、高性能的系统_.md
  
   - 22｜Volatile_深入解析JVM中的轻量级同步机制.md
  
   - 23｜一致性演进_Volatile与RAFT有何异同_.md
  
   - 24｜Synchronized_同步锁的原理及应用.md
  
   - 25｜锁家族的裂变_如何打造一个锁程序_.md
  
   - 26｜ThreadLocal（上）_线程安全的另类实现思路.md
  
   - 27｜ThreadLocal（下）_ThreadLocal家族成员及应用指南.md
  
   - 28｜线程池_不同场景下如何合理地选择线程池_.md
  
   - 29｜编程范式_云原生时代函数式编程为何能占据主流_.md
  
   - 30｜函数式语法糖_如何使用Function、Stream来编写函数式程序_.md
  
   - 31｜当装饰器遇上函数式_打造一个函数式装饰器模式的程序.md
  
   - 32｜当策略模式遇上函数式_打造一个函数式策略模式的程序.md
  
   - 33｜环境_基于GraalVM的JVM云原生环境搭建.md
  
   - 34｜工具_学会使用从内存分析到性能测试等各种常用工具.md
  
   - 35｜实现_基于JDK17、SpringBoot3、Spring6打造云原生Java应用.md
  
   - 36｜性能_百万级TPS系统的性能优化之道.md
  
   - 结束语｜学习是一生的旅程.md
  
   - 结课测试｜来赴一场满分之约吧！.md
  