site_name: Java核心技术面试精讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_以面试题为切入点，有效提升你的Java内功.md
  
   - 第1讲_谈谈你对Java平台的理解_.md
  
   - 第2讲_Exception和Error有什么区别_.md
  
   - 第3讲_谈谈final、finally、finalize有什么不同_.md
  
   - 第4讲_强引用、软引用、弱引用、幻象引用有什么区别_.md
  
   - 第5讲_String、StringBuffer、StringBuilder有什么区别_.md
  
   - 第6讲_动态代理是基于什么原理_.md
  
   - 第7讲_int和Integer有什么区别_.md
  
   - 第8讲_对比Vector、ArrayList、LinkedList有何区别_.md
  
   - 第9讲_对比Hashtable、HashMap、TreeMap有什么不同_.md
  
   - 第10讲_如何保证集合是线程安全的_ConcurrentHashMap如何实现高效地线程安全_.md
  
   - 第11讲_Java提供了哪些IO方式_NIO如何实现多路复用_.md
  
   - 第12讲_Java有几种文件拷贝方式_哪一种最高效_.md
  
   - 第13讲_谈谈接口和抽象类有什么区别_.md
  
   - 第14讲_谈谈你知道的设计模式_.md
  
   - 第15讲_synchronized和ReentrantLock有什么区别呢_.md
  
   - 第16讲_synchronized底层如何实现_什么是锁的升级、降级_.md
  
   - 第17讲_一个线程两次调用start()方法会出现什么情况_.md
  
   - 第18讲_什么情况下Java程序会产生死锁_如何定位、修复_.md
  
   - 第19讲_Java并发包提供了哪些并发工具类_.md
  
   - 第20讲_并发包中的ConcurrentLinkedQueue和LinkedBlockingQueue有什么区别_.md
  
   - 第21讲_Java并发类库提供的线程池有哪几种_分别有什么特点_.md
  
   - 第22讲_AtomicInteger底层实现原理是什么_如何在自己的产品代码中应用CAS操作_.md
  
   - 第23讲_请介绍类加载过程，什么是双亲委派模型_.md
  
   - 第24讲_有哪些方法可以在运行时动态生成一个Java类_.md
  
   - 第25讲_谈谈JVM内存区域的划分，哪些区域可能发生OutOfMemoryError_.md
  
   - 第26讲_如何监控和诊断JVM堆内和堆外内存使用_.md
  
   - 第27讲_Java常见的垃圾收集器有哪些_.md
  
   - 第28讲_谈谈你的GC调优思路_.md
  
   - 第29讲_Java内存模型中的happen-before是什么_.md
  
   - 第30讲_Java程序运行在Docker等容器环境有哪些新问题_.md
  
   - 第31讲_你了解Java应用开发中的注入攻击吗_.md
  
   - 第32讲_如何写出安全的Java代码_.md
  
   - 第33讲_后台服务出现明显“变慢”，谈谈你的诊断思路_.md
  
   - 第34讲_有人说“Lambda能让Java程序慢30倍”，你怎么看_.md
  
   - 第35讲_JVM优化Java代码时都做了什么_.md
  
   - 第36讲_谈谈MySQL支持的事务隔离级别，以及悲观锁和乐观锁的原理和应用场景_.md
  
   - 第37讲_谈谈SpringBean的生命周期和作用域_.md
  
   - 第38讲_对比Java标准NIO类库，你知道Netty是如何实现更高性能的吗_.md
  
   - 第39讲_谈谈常用的分布式ID的设计方案_Snowflake是否受冬令时切换影响_.md
  
   - 周末福利_谈谈我对Java学习和面试的看法.md
  
   - 周末福利_一份Java工程师必读书单.md
  
   - 结束语_技术没有终点.md
  
   - 结课测试_Java核心技术的这些知识，你真的掌握了吗_.md
  