site_name: AI大模型系统实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 第二季回归｜我带着LLaMA3新课回来了！.md
  
   - 开篇词｜漫游未来，一起开启AI大模型系统修炼之旅.md
  
   - 01｜认知升级_你心中的AI大模型长啥样_.md
  
   - 02｜具身智能_OpenAI真正的野心是什么_.md
  
   - 03｜原型系统_开源工具自建AI大模型底座.md
  
   - 04｜游目骋怀_工业级的大模型系统强在哪_.md
  
   - 05｜策略建模_为什么AI系统能够猜你所想_.md
  
   - 06｜特征工程_数据点石成金，给你的系统赋予灵魂.md
  
   - 07｜模型工程_算法三大门派，取众家之长为我所用.md
  
   - 08_数据算法_因材施教，为你的系统选好老师.md
  
   - 09｜系统构建（一）_AI系统的弹药库——离线系统.md
  
   - 10｜系统构建（二）_AI系统的冲锋队——在线系统.md
  
   - 答疑课堂｜前两章思考题答案.md
  
   - 11｜地球往事_为什么CV领域首先引领预训练潮流_.md
  
   - 12｜博观约取_重走NLP领域预训练模型的长征路.md
  
   - 13｜厚积薄发_如何让模型更好地理解人类语言_.md
  
   - 14｜变形金刚_Transformer是如何让模型变大的_.md
  
   - 15_GPT1-3_技术爆炸，深入解析LLM的核心技术.md
  
   - 16｜ChatGPT_是什么让LLM走向舞台中央_.md
  
   - 17｜LLM展望_死神永生，LLM会带人们驶向何处_.md
  
   - 18｜策略建模_取众家所长的工业级的AIGC系统.md
  
   - 19｜提示语工程（一）_为什么说提示语引擎是“智能体本体”_.md
  
   - 20｜提示语工程（二）_LLM的护卫舰队有哪些_.md
  
   - 21｜提示语工程（三）_如何帮助智能体更好地管理记忆_.md
  
   - 国庆策划｜赛程过半，检验一下你的学习成果吧！.md
  
   - 22｜提示语工程（四）_如何让智能体学会反思过去和规划未来_.md
  
   - 23｜提示语工程（五）_构建你自己的西部世界——AI小镇搭建实战.md
  
   - 24｜提示语工程（六）_超越智能，让你的AI系统成为全知超人.md
  
   - 25｜模型工程（一）_如何让你的训练数据无中生有_.md
  
   - 26｜模型工程（二）_算力受限，如何为“无米之炊”_.md
  
   - 27｜模型工程（三）_低成本领域模型方案，小团队怎么做大模型_.md
  
   - 28｜总体回顾_工业级AI大模型系统的庐山真面目.md
  
   - 29｜从创业到被收购，OpenAI经历了哪些关键阶段_.md
  
   - 30｜藏宝图_大模型产业全景图，新业态带来哪些新机遇_.md
  
   - 31｜发展趋势_生成式AI系统的未来发展趋势是什么_.md
  
   - 32｜职场规划_面试准备，如何做大模型时代下的长远规划_.md
  
   - 答疑课堂（二）｜后三章思考题答案.md
  
   - 结束语｜AI大模型，技术人的双城记.md
  
   - 结课测试｜来赴一场满分之约.md
  