site_name: 从0开始学架构

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 旅程再启｜架构师该如何适应新的技术浪潮_.md
  
   - 微服务架构技巧篇_接口类设计技巧.md
  
   - 微服务架构技巧篇_分布式事务.md
  
   - 开篇词_照着做，你也能成为架构师！.md
  
   - 01_架构到底是指什么_.md
  
   - 02_架构设计的历史背景.md
  
   - 03_架构设计的目的.md
  
   - 04_复杂度来源_高性能.md
  
   - 05_复杂度来源_高可用.md
  
   - 06_复杂度来源_可扩展性.md
  
   - 07_复杂度来源_低成本、安全、规模.md
  
   - 08_架构设计三原则.md
  
   - 09_架构设计原则案例.md
  
   - 10_架构设计流程_识别复杂度.md
  
   - 11_架构设计流程_设计备选方案.md
  
   - 12_架构设计流程_评估和选择备选方案.md
  
   - 13_架构设计流程_详细方案设计.md
  
   - 14_高性能数据库集群_读写分离.md
  
   - 15_高性能数据库集群_分库分表.md
  
   - 16_高性能NoSQL.md
  
   - 17_高性能缓存架构.md
  
   - 18_单服务器高性能模式_PPC与TPC.md
  
   - 19_单服务器高性能模式_Reactor与Proactor.md
  
   - 20_高性能负载均衡_分类及架构.md
  
   - 21_高性能负载均衡_算法.md
  
   - 22_想成为架构师，你必须知道CAP理论.md
  
   - 23_想成为架构师，你必须掌握的CAP细节.md
  
   - 24_FMEA方法，排除架构可用性隐患的利器.md
  
   - 25_高可用存储架构_双机架构.md
  
   - 26_高可用存储架构_集群和分区.md
  
   - 27_如何设计计算高可用架构_.md
  
   - 28_业务高可用的保障_异地多活架构.md
  
   - 29_异地多活设计4大技巧.md
  
   - 30_异地多活设计4步走.md
  
   - 31_如何应对接口级的故障_.md
  
   - 32_可扩展架构的基本思想和模式.md
  
   - 33_传统的可扩展架构模式_分层架构和SOA.md
  
   - 34_深入理解微服务架构_银弹or焦油坑_.md
  
   - 35_微服务架构最佳实践-方法篇.md
  
   - 36_微服务架构最佳实践-基础设施篇.md
  
   - 37_微内核架构详解.md
  
   - 38_架构师应该如何判断技术演进的方向_.md
  
   - 39_互联网技术演进的模式.md
  
   - 40_互联网架构模板_“存储层”技术.md
  
   - 41_互联网架构模板_“开发层”和“服务层”技术.md
  
   - 42_互联网架构模板_“网络层”技术.md
  
   - 43_互联网架构模板_“用户层”和“业务层”技术.md
  
   - 44_互联网架构模板_“平台”技术.md
  
   - 45_架构重构内功心法第一式_有的放矢.md
  
   - 46_架构重构内功心法第二式_合纵连横.md
  
   - 47_架构重构内功心法第三式_运筹帷幄.md
  
   - 48_再谈开源项目_如何选择、使用以及二次开发_.md
  
   - 49_谈谈App架构的演进.md
  
   - 50_架构实战_架构设计文档模板.md
  
   - 51_如何画出优秀的软件系统架构图_.md
  
   - 架构专栏特别放送_“华仔，放学别走！”第1期.md
  
   - 架构专栏特别放送_“华仔，放学别走！”第2期.md
  
   - 如何高效地学习开源项目_“华仔，放学别走！”第3期.md
  
   - 架构师成长之路_“华仔，放学别走！”第4期.md
  
   - 架构师必读书单_“华仔，放学别走！”第5期.md
  
   - 新书首发_《从零开始学架构》.md
  
   - 致「从0开始学架构」专栏订阅用户.md
  
   - 第二季回归_照着做，你也能顺利晋升！.md
  
   - 加餐｜单服务器高性能模式性能对比.md
  
   - 加餐｜扒一扒中台皇帝的外衣.md
  
   - 加餐｜业务架构实战营开营了.md
  
   - ChatGPT来临，架构师何去何从_.md
  
   - 结束语_坚持，成就你的技术梦想.md
  
   - 结课测试｜这些架构技能你都掌握了吗_.md
  