site_name: 研发效率破局之道

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_为什么你要关注研发效能_.md
  
   - 01_效能模型_如何系统地理解研发效能_.md
  
   - 02_效能度量_效果不好甚至有副作用，怎么回事_.md
  
   - 03_效能度量_如何选对指标与方法，真正提升效能_.md
  
   - 04_流程优化_怎样才能让敏捷、精益真正为我所用_.md
  
   - 05_代码入库前_Facebook如何让开发人员聚焦于开发_.md
  
   - 06_代码入库到产品上线_Facebook如何使用CI_CD满足业务要求_.md
  
   - 07_分支管理_Facebook的策略，适合我的团队吗_.md
  
   - 08_DevOps、SRE的共性_应用全栈思路打通开发和运维.md
  
   - 09_信息流通_让团队高效协同，让产品准确击中目标.md
  
   - 10_答疑篇_反对996并不是反对奋斗.md
  
   - 11_研发环境_Facebook怎样让开发人员不再操心环境_.md
  
   - 12_代码审查_哪种方式更适合我的团队_.md
  
   - 13_代码审查_学习Facebook真正发挥代码审查的提效作用.md
  
   - 14_质量与速度的均衡_让“唯快不破”快得更持久.md
  
   - 15_开源_从Phabricator的开源历程看开源利弊.md
  
   - 16_高效上云_如何用云计算来提高效能_.md
  
   - 17_测试左移_测试如何应对新的开发模式_.md
  
   - 18_蓝绿红黑灰度发布_这些五颜六色的发布到底怎么用_.md
  
   - 19_不再掉队，研发流程、工程方法趋势解读和展望.md
  
   - 20_答疑篇_如何平衡短期收益和长期收益_.md
  
   - 21_高效工作_Facebook的10x程序员效率心法.md
  
   - 22_深度工作_聚焦最有价值的事儿.md
  
   - 23_效率工具_选对用对才能事半功倍.md
  
   - 特别放送_每个开发人员都应该学一些VIM.md
  
   - 24_VIM_如何高性价比地学习VIM的实用技巧_.md
  
   - 25_玩转Git_五种提高代码提交原子性的基本操作.md
  
   - 26_Facebook怎样实现代码提交的原子性_.md
  
   - 27_命令行_不只是酷，更重要的是能提高个人效能.md
  
   - 28_从工作场景出发，寻找炫酷且有效的命令行工具.md
  
   - 29_1+1=2，灵活的工具组合及环境让你的工作效率翻倍.md
  
   - 30_答疑篇_关于价值导向和沟通.md
  
   - 31_业务目标和技术目标两手抓_怎样打造高效团队_.md
  
   - 32_从Netflix公开的著名PPT谈硅谷公司文化.md
  
   - 33_Facebook企业文化_工程师文化是创造力引擎.md
  
   - 34_Facebook工程师文化实践三大支柱之一做感兴趣的事.md
  
   - 35_Facebook工程师文化实践三大支柱之二拥有信息和权限.md
  
   - 36_Facebook工程师文化实践三大支柱之三绩效调节.md
  
   - 结束语_超越昨天的自己，享受成长的快乐.md
  
   - 结课测试_关于研发效率的这些知识，你都掌握了吗_.md
  