site_name: 数据结构与算法之美

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_从今天起，跨过“数据结构与算法”这道坎.md
  
   - 01_为什么要学习数据结构和算法_.md
  
   - 02_如何抓住重点，系统高效地学习数据结构与算法_.md
  
   - 03_复杂度分析（上）_如何分析、统计算法的执行效率和资源消耗_.md
  
   - 04_复杂度分析（下）_浅析最好、最坏、平均、均摊时间复杂度.md
  
   - 05_数组_为什么很多编程语言中数组都从0开始编号_.md
  
   - 06_链表（上）_如何实现LRU缓存淘汰算法_.md
  
   - 07_链表（下）_如何轻松写出正确的链表代码_.md
  
   - 08_栈_如何实现浏览器的前进和后退功能_.md
  
   - 09_队列_队列在线程池等有限资源池中的应用.md
  
   - 10_递归_如何用三行代码找到“最终推荐人”_.md
  
   - 11_排序（上）_为什么插入排序比冒泡排序更受欢迎_.md
  
   - 12_排序（下）_如何用快排思想在O(n)内查找第K大元素_.md
  
   - 13_线性排序_如何根据年龄给100万用户数据排序_.md
  
   - 14_排序优化_如何实现一个通用的、高性能的排序函数_.md
  
   - 15_二分查找（上）_如何用最省内存的方式实现快速查找功能_.md
  
   - 16_二分查找（下）_如何快速定位IP对应的省份地址_.md
  
   - 17_跳表_为什么Redis一定要用跳表来实现有序集合_.md
  
   - 18_散列表（上）_Word文档中的单词拼写检查功能是如何实现的_.md
  
   - 19_散列表（中）_如何打造一个工业级水平的散列表_.md
  
   - 20_散列表（下）_为什么散列表和链表经常会一起使用_.md
  
   - 21_哈希算法（上）_如何防止数据库中的用户信息被脱库_.md
  
   - 22_哈希算法（下）_哈希算法在分布式系统中有哪些应用_.md
  
   - 23_二叉树基础（上）_什么样的二叉树适合用数组来存储_.md
  
   - 24_二叉树基础（下）_有了如此高效的散列表，为什么还需要二叉树_.md
  
   - 25_红黑树（上）_为什么工程中都用红黑树这种二叉树_.md
  
   - 26_红黑树（下）_掌握这些技巧，你也可以实现一个红黑树.md
  
   - 27_递归树_如何借助树来求解递归算法的时间复杂度_.md
  
   - 28_堆和堆排序_为什么说堆排序没有快速排序快_.md
  
   - 29_堆的应用_如何快速获取到Top10最热门的搜索关键词_.md
  
   - 30_图的表示_如何存储微博、微信等社交网络中的好友关系_.md
  
   - 31_深度和广度优先搜索_如何找出社交网络中的三度好友关系_.md
  
   - 32_字符串匹配基础（上）_如何借助哈希算法实现高效字符串匹配_.md
  
   - 33_字符串匹配基础（中）_如何实现文本编辑器中的查找功能_.md
  
   - 34_字符串匹配基础（下）_如何借助BM算法轻松理解KMP算法_.md
  
   - 35_Trie树_如何实现搜索引擎的搜索关键词提示功能_.md
  
   - 36_AC自动机_如何用多模式串匹配实现敏感词过滤功能_.md
  
   - 37_贪心算法_如何用贪心算法实现Huffman压缩编码_.md
  
   - 38_分治算法_谈一谈大规模计算框架MapReduce中的分治思想.md
  
   - 39_回溯算法_从电影《蝴蝶效应》中学习回溯算法的核心思想.md
  
   - 40_初识动态规划_如何巧妙解决“双十一”购物时的凑单问题_.md
  
   - 41_动态规划理论_一篇文章带你彻底搞懂最优子结构、无后效性和重复子问题.md
  
   - 42_动态规划实战_如何实现搜索引擎中的拼写纠错功能_.md
  
   - 43_拓扑排序_如何确定代码源文件的编译依赖关系_.md
  
   - 44_最短路径_地图软件是如何计算出最优出行路径的_.md
  
   - 45_位图_如何实现网页爬虫中的URL去重功能_.md
  
   - 46_概率统计_如何利用朴素贝叶斯算法过滤垃圾短信_.md
  
   - 47_向量空间_如何实现一个简单的音乐推荐系统_.md
  
   - 48_B&#43;树_MySQL数据库索引是如何实现的_.md
  
   - 49_搜索_如何用A_搜索算法实现游戏中的寻路功能_.md
  
   - 50_索引_如何在海量数据中快速查找某个数据_.md
  
   - 51_并行算法_如何利用并行处理提高算法的执行效率_.md
  
   - 52_算法实战（一）_剖析Redis常用数据类型对应的数据结构.md
  
   - 53_算法实战（二）_剖析搜索引擎背后的经典数据结构和算法.md
  
   - 54_算法实战（三）_剖析高性能队列Disruptor背后的数据结构和算法.md
  
   - 55_算法实战（四）_剖析微服务接口鉴权限流背后的数据结构和算法.md
  
   - 56_算法实战（五）_如何用学过的数据结构和算法实现一个短网址系统_.md
  
   - 不定期福利第一期_数据结构与算法学习书单.md
  
   - 不定期福利第二期_王争_羁绊前行的，不是肆虐的狂风，而是内心的迷茫.md
  
   - 不定期福利第三期_测一测你的算法阶段学习成果.md
  
   - 不定期福利第四期_刘超_我是怎么学习《数据结构与算法之美》的_.md
  
   - 总结课_在实际开发中，如何权衡选择使用哪种数据结构和算法_.md
  
   - 《数据结构与算法之美》学习指导手册.md
  
   - 春节7天练_Day1_数组和链表.md
  
   - 春节7天练_Day2_栈、队列和递归.md
  
   - 春节7天练_Day3_排序和二分查找.md
  
   - 春节7天练_Day4_散列表和字符串.md
  
   - 春节7天练_Day5_二叉树和堆.md
  
   - 春节7天练_Day6_图.md
  
   - 春节7天练_Day7_贪心、分治、回溯和动态规划.md
  
   - 用户故事_Jerry银银_这一年我的脑海里只有算法.md
  
   - 用户故事_zixuan_站在思维的高处，才有足够的视野和能力欣赏“美”.md
  
   - 结束语_送君千里，终须一别.md
  
   - 第2季回归_这一次，我们一起拿下设计模式！.md
  
   - 结课测试｜这些数据结构与算法，你真的掌握了吗_.md
  
   - 课程迭代｜全新交付71讲音频.md
  
   - 打卡召集令_60天攻克数据结构与算法.md
  
   - 打卡召集令_第一阶段知识总结.md
  
   - 打卡召集令_第二阶段知识总结.md
  
   - 打卡召集令_第三阶段知识总结.md
  
   - 打卡召集令_第四阶段知识总结.md
  