site_name: 跟月影学可视化

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_不写网页的前端工程师，还能干什么_.md
  
   - 预习_Web前端与可视化到底有什么区别_.md
  
   - 01_浏览器中实现可视化的四种方式.md
  
   - 02_指令式绘图系统_如何用Canvas绘制层次关系图_.md
  
   - 03_声明式图形系统_如何用SVG图形元素绘制可视化图表_.md
  
   - 04_GPU与渲染管线_如何用WebGL绘制最简单的几何图形_.md
  
   - 05_如何用向量和坐标系描述点和线段_.md
  
   - 06_可视化中你必须要掌握的向量乘法知识.md
  
   - 07_如何用向量和参数方程描述曲线_.md
  
   - 08_如何利用三角剖分和向量操作描述并处理多边形_.md
  
   - 09_如何用仿射变换对几何图形进行坐标变换_.md
  
   - 10_图形系统如何表示颜色_.md
  
   - 11｜图案生成_如何生成重复图案、分形图案以及随机效果_.md
  
   - 12_如何使用滤镜函数实现美颜效果_.md
  
   - 13_如何给简单的图案添加纹理和复杂滤镜_.md
  
   - 14_如何使用片元着色器进行几何造型_.md
  
   - 15_如何用极坐标系绘制有趣图案_.md
  
   - 16_如何使用噪声生成复杂的纹理_.md
  
   - 17_如何使用后期处理通道增强图像效果_.md
  
   - 18_如何生成简单动画让图形动起来_.md
  
   - 19_如何用着色器实现像素动画_.md
  
   - 20_如何用WebGL绘制3D物体_.md
  
   - 21_如何添加相机，用透视原理对物体进行投影_.md
  
   - 22_如何用仿射变换来移动和旋转3D物体_.md
  
   - 23_如何模拟光照让3D场景更逼真_（上）.md
  
   - 24_如何模拟光照让3D场景更逼真_（下）.md
  
   - 25_如何用法线贴图模拟真实物体表面.md
  
   - 26_如何绘制带宽度的曲线_.md
  
   - 27_案例_如何实现简单的3D可视化图表_.md
  
   - 28_Canvas、SVG与WebGL在性能上的优势与劣势.md
  
   - 29_怎么给Canvas绘制加速_.md
  
   - 30｜怎么给WebGL绘制加速_.md
  
   - 31_针对海量数据，如何优化性能_.md
  
   - 32_数据之美_如何选择合适的方法对数据进行可视化处理_.md
  
   - 33_数据处理（一）_可视化数据处理的一般方法是什么_.md
  
   - 34_数据处理（二）_如何处理多元变量_.md
  
   - 35_设计（一）_如何让可视化设计更加清晰_.md
  
   - 36_设计（二）_如何理解可视化设计原则_.md
  
   - 37_实战（一）_如何使用图表库绘制常用数据图表_.md
  
   - 38_实战（二）_如何使用数据驱动框架绘制常用数据图表_.md
  
   - 39_实战（三）_如何实现地理信息的可视化_.md
  
   - 40_实战（四）_如何实现3D地球可视化（上）_.md
  
   - 41_实战（五）_如何实现3D地球可视化（下）_.md
  
   - 42_如何整理出我们自己的可视化工具集_.md
  
   - 国庆策划_假期别闲着，一起来挑战“手势密码”.md
  
   - 国庆策划_快来看看怎么用原生JavaScript实现手势解锁组件.md
  
   - 加餐1_作为一名程序员，数学到底要多好_.md
  
   - 加餐2_SpriteJS_我是如何设计一个可视化图形渲染引擎的_.md
  
   - 用户故事_非前端开发，我为什么要学可视化_.md
  
   - 加餐3_轻松一刻_我想和你聊聊前端的未来.md
  
   - 加餐4_一篇文章，带你快速理解函数式编程.md
  
   - 加餐5｜周爱民_我想和你分享些学习的道理.md
  
   - 结束语_可视化工程师的未来之路.md
  
   - 有奖征集倒计时4天！你填写毕业问卷了吗_.md
  