site_name: 高并发系统设计40问

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_为什么你要学习高并发系统设计_.md
  
   - 01_高并发系统_它的通用设计方法是什么_.md
  
   - 02_架构分层_我们为什么一定要这么做_.md
  
   - 03_系统设计目标（一）_如何提升系统性能_.md
  
   - 04_系统设计目标（二）_系统怎样做到高可用_.md
  
   - 05_系统设计目标（三）_如何让系统易于扩展_.md
  
   - 06_面试现场第一期_当问到组件实现原理时，面试官是在刁难你吗_.md
  
   - 07_池化技术_如何减少频繁创建数据库连接的性能损耗_.md
  
   - 08_数据库优化方案（一）_查询请求增加时，如何做主从分离_.md
  
   - 09_数据库优化方案（二）_写入数据量增加时，如何实现分库分表_.md
  
   - 10_发号器_如何保证分库分表后ID的全局唯一性_.md
  
   - 11_NoSQL_在高并发场景下，数据库和NoSQL如何做到互补_.md
  
   - 12_缓存_数据库成为瓶颈后，动态数据的查询要如何加速_.md
  
   - 13_缓存的使用姿势（一）_如何选择缓存的读写策略_.md
  
   - 14_缓存的使用姿势（二）_缓存如何做到高可用_.md
  
   - 15_缓存的使用姿势（三）_缓存穿透了怎么办_.md
  
   - 16_CDN_静态资源如何加速_.md
  
   - 加餐_数据的迁移应该如何做_.md
  
   - 17_消息队列_秒杀时如何处理每秒上万次的下单请求_.md
  
   - 18_消息投递_如何保证消息仅仅被消费一次_.md
  
   - 19_消息队列_如何降低消息队列系统中消息的延迟_.md
  
   - 20_面试现场第二期_当问到项目经历时，面试官究竟想要了解什么_.md
  
   - 用户故事_从“心”出发，我还有无数个可能.md
  
   - 期中测试_10道高并发系统设计题目自测.md
  
   - 21_系统架构_每秒1万次请求的系统要做服务化拆分吗_.md
  
   - 22_微服务架构_微服务化后系统架构要如何改造_.md
  
   - 23_RPC框架_10万QPS下如何实现毫秒级的服务调用_.md
  
   - 24_注册中心_分布式系统如何寻址_.md
  
   - 25_分布式Trace_横跨几十个分布式组件的慢请求要如何排查_.md
  
   - 26_负载均衡_怎样提升系统的横向扩展能力_.md
  
   - 27_API网关_系统的门面要如何做呢_.md
  
   - 28_多机房部署_跨地域的分布式系统如何做_.md
  
   - 29_ServiceMesh_如何屏蔽服务化系统的服务治理细节_.md
  
   - 30_给系统加上眼睛_服务端监控要怎么做_.md
  
   - 31_应用性能管理_用户的使用体验应该如何监控_.md
  
   - 32_压力测试_怎样设计全链路压力测试平台_.md
  
   - 33_配置管理_成千上万的配置项要如何管理_.md
  
   - 34_降级熔断_如何屏蔽非核心系统故障的影响_.md
  
   - 35_流量控制_高并发系统中我们如何操纵流量_.md
  
   - 36_面试现场第三期_你要如何准备一场技术面试呢_.md
  
   - 37_计数系统设计（一）_面对海量数据的计数器要如何做_.md
  
   - 38_计数系统设计（二）_50万QPS下如何设计未读数系统_.md
  
   - 39_信息流设计（一）_通用信息流系统的推模式要如何做_.md
  
   - 40_信息流设计（二）_通用信息流系统的拉模式要如何做_.md
  
   - 结束语_学不可以已.md
  
   - 结课问卷获奖用户名单.md
  
   - 春节特别策划_高并发下如何发现和排查问题_.md
  
   - 春节特别策划_我们如何准备抵抗流量峰值_.md
  
   - 结课测试_高并发系统设计的相关知识，你都掌握了吗_.md
  